### ISSUE TITLE
Writing the "env" variable inside "catch2TestExplorer.executables" overwrittes system environment variables

### ISSUE THREAD

**Issue by zrno** [matepek/vscode-catch2-test-adapter#100]
**Describe the bug** (A clear and concise description of what the bug is.)
Using windows. I have a system environment variable called "Path" that has several entries. Example from my settings.json:
`    
"catch2TestExplorer.executables": [
        {
            "name": "${filename}",
            "pattern": "C:/Projects/CMakeBuild/vscode/NSW-51770/Visual Studio Professional 2019 - x86/Debug/**/*{test,Test,TEST}*/*.exe",
            "dependsOn": ["C:/Projects/CMakeBuild/vscode/NSW-51770/Visual Studio Professional 2019 - x86/Debug/"],
            "env": {"Path": "C:/SDKs/Qt/Qt5.6.0-msvc2015/5.6/msvc2015/bin"}
        }
    ],
`
Test executables are not recognized because they fail to run as they are missing a bunch of libraries that are listed in my Path environment variable.

**Expected behavior** (A clear and concise description of what you expected to happen.)
System environment variables are not overwritten but only expanded by appending.

**Additional context** Add any other context about the problem here.
Or is there some other way to expand the environment for the executables? Also is it expected that vscode variables like ${env:Path} cannot be used inside the "env" in "catch2TestExplorer.executables" ?
Also is there a way to add multiple entries to one "env" variable like "Path" from the example. Something like 
`
"env": {"Path": "C:/path1; C:/path2"}
`
?

**Comment by matepek** [comment]
Hello,

1. I see, you are using the `dependsOn` feature with a directory. What is the effect? How does it  work for you? In which cases does does a change event fires?

2. `${env}` appending system variables. That would cause a lot of trouble for others and I think there are better ways like a new property `"envAppend": {...}` or more likely your suggestion `${env:Path}`.
I like this idea.

3. I'm not sure I understand last part: multiple entries. Environment variables are strings. `Path` is a string too but used like an array separated with semicolon. 
Is the following would solve your problem: 
`"env": { "Path": "${env:Path}; C:/path1; C:/path2" }` ?

Note: Some of my users are generating wrappers (batch files `.bat`) and doing some magic. So if you need to do something complex, there is a way. However this `${env:Path}` is a good idea. I think I will add it today.

**Comment by zrno** [comment]
Hi, thanks for the super fast answer.
1. I haven't tested it much since I got it working. I'll describe my folder structure.
Keep in mind, all is on windows. This is my cmake output directory simplified:
-C:/Projects/CMakeBuild/Debug   <----- this is where `dependsOn` points to
-C:/Projects/CMakeBuild/Debug/Project1/project1.exe
-C:/Projects/CMakeBuild/Debug/Project1/Test/project1UnitTest.exe
-C:/Projects/CMakeBuild/Debug/Project2/project2.exe
-C:/Projects/CMakeBuild/Debug/Project2/Test/project2UnitTest.exe
The autorun triggers correctly for each unit test. If I make a change to Project2 it only runs project2UnitTest.exe. The same goes for Project1. It also work if I build many different projects at once.

2. Sounds nice. So you would be able to use the vscode variable ${env:Path} in your settings also?

3. If your example would work that would solve all my problems. My question was that I didn't know how to add multiple entries in one string. So the correct way is to to use one string with semicolon separated entries?

**Comment by matepek** [comment]
1. I thought only files can be watched. Maybe "Gaze" supports directories. Whatever.

2. It's done and released: `${os_env:<varname>}`

3. On Windows the [PATH environment variaable](https://en.wikipedia.org/wiki/PATH_(variable)#DOS,_OS/2,_and_Windows) it is a semicolon separated list. (all envs are strings). Type `echo %PATH%` to cmd to see.
So if you want new paths to the PATH env variable you do the following:
```
"env": { "PATH": "${os_env:PATH};C:/mypath1;C:/mypath2" }
```

**Comment by zrno** [comment]
Great. Thanks. That was the fastest fix ever on GitHub.
On number 3. My error was a space after the first semicolon.
This works:
`"env": { "PATH": "${os_env:PATH};C:/mypath1;C:/mypath2" }`
This doesn't:
`"env": { "PATH": "${os_env:PATH}; C:/mypath1; C:/mypath2" }`

**Comment by zrno** [comment]
Unrelated question but it could help me. Is there any way to output the values of https://github.com/matepek/vscode-catch2-test-adapter#variables-which-can-be-used-in-name-description-cwd-and-env-of-executables ?

**Comment by matepek** [comment]
What do you mean output? To where?

You can do the following: "env": { "execpath": "${absPath}" }.

**Comment by zrno** [comment]
Output them to the console or to the log file so I can easier find where my mistake is? 
vscode offers an example how to output values of variables from settings.json by using 
`{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo ${command:cmake.launchTargetDirectory}",
            "problemMatcher": []
        }
    ]
}`

**Comment by matepek** [comment]
Everything is logged: Use `catch2TestExplorer.logpanel`.
