### ISSUE TITLE
Enable configurable timeout for test discovery

### ISSUE THREAD

**Issue by jsamuel1** [matepek/vscode-catch2-test-adapter#106]
**Is your feature request related to a problem? Please describe.**
While trying populate the list of tests using the refresh button, my project continually fails to populate.    Upon enabling logging of the extension, I found that the test file was found, but was timing out after 5 seconds when trying to load tests.

**Describe the solution you'd like**
It would be absolutely awesome if the 2 x places where there a timeout specified on the async call with a timeout specified of "5000", in Catch2TestSuiteInfo.js and RunningTestExecutableInfo.js was a configurable value.  Especially useful for people with slower machines or large projects.

**Describe alternatives you've considered**
Alternatively, increasing those timeouts to 15000 manually in the code worked for me, so I (but perhaps not others) would be happy for this default to just be increased in the code to a value that "works for me". :)

**Additional context**
I'm running on Linux, using the code-insiders build.
My same project running on Windows did not hit the timeout and worked fine.

**Comment by matepek** [comment]
catch2TestExplorer.defaultExecParsingTimeoutSec <-- ver2.6
