### ISSUE TITLE
Enable a way to use environment variables in pattern

### ISSUE THREAD

**Issue by Mightrider** [matepek/vscode-catch2-test-adapter#108]
**Is your feature request related to a problem? Please describe.**
I try to find my tests related to the environment variable SOFTTEMP.
``` json
{
    "catch2TestExplorer.executables": [
        {
            "name": "${filename}",
            "description": "${absDirpath}/",
            "pattern": "${SOFTTEMP}/Debug/SomeProject/*{test,Test,TEST}*"
        }
    ]
}
```
Unfortunately these settings do not detect any tests.

**Describe the solution you'd like**
The pattern should be able to detect all tests in this 

> ${SOFTTEMP}/Debug/SomeProject
folder.

**Describe alternatives you've considered**
If I use hardcoded strings it works but I want to use the settings on different machines with different options.
I also tried to set the cwd to the folder:
``` json
"cwd": "${os_env:SOFTTEMP}/Debug/SomeProject"
"pattern": "*{test,Test,TEST}*",
```

**Comment by matepek** [comment]
Resolution for `"cwd"` should work. Can you confirm it?

**Comment by Mightrider** [comment]
No unfortunately I can not confirm this. 
It does not work for both cases: `"cwd": "${os_env:SOFTTEMP}/Debug/SomeProject"` and `"cwd": "ActualPath/Debug/SomeProject"`.
I would guess that cwd is applied after the pattern because as you mention in your documentation `cwd Can contains variables related to pattern`.

**Comment by matepek** [comment]
In version 2.6.1 the `${os_env:<varname>}` is resolved in the case of `pattern` and `cwd` too. (just cheked it on OSX).
Please file a proper bug report if you still experience the issue.

**Comment by Mightrider** [comment]
I double checked the version and it works now with `"pattern": "${SOFTTEMP}/Debug/SomeProject/*{test,Test,TEST}*"`. Thank you very much for your support.

**Comment by matepek** [comment]
That is weird, because only `${os_env:...}` should work. I guess you meant that.

**Comment by Mightrider** [comment]
yes :smile:
