### ISSUE TITLE
Executables are not found if they are inside folders listed in VS Code `files.exclude` option

### ISSUE THREAD

**Issue by deitry** [matepek/vscode-catch2-test-adapter#113]
I have test executables inside `build/`. I added this folder to `files.exclude` in order to hide it from explorer tree, but my test executables are also become hidden. Executables are not shown even if I pass relative or absolute path instead of globbing pattern.

Is there a possibility to resolve executables pattern even if it intersects with 'files.exclude'?

**Comment by matepek** [comment]
I'm using the [findFiles](https://code.visualstudio.com/api/references/vscode-api) endpoint to query files. According to the [documentation](https://code.visualstudio.com/api/references/vscode-api) if the second parameter is null, it should not use the default exclusion pattern. I interpret this that it should work, because I am passing null as second parameter. 

I might misinterpret the documentation or there is vscode bug.

**Comment by deitry** [comment]
Thanks for the quick reply!
I found related issue: https://github.com/Microsoft/vscode/issues/48674
It seems that `files.exclude` IS default exclusion path.

I guess the easiest way to have both of feature would be to add `exclude` option to this extension which would be passed instead of null.

**Comment by matepek** [comment]
Nore that “undefined” and “null” are different values in JavaScript. 
Since you are talking about “undefined”, you might missed that. If not then I am missing something, please explain what do you mean.

**Comment by deitry** [comment]
I'm bad in JS so I talk only about files detection dependency on `files.exclude` option. `undefined` is discussed in the VS Code issue which I suppose to be related.

I guess this issue could be called a feature request to have independent `exclude` configuration entry.

**Comment by matepek** [comment]
Disagree:
> When undefined only default excludes will apply, when null no excludes will apply.

(See [doc](https://code.visualstudio.com/api/references/vscode-api))
According to the documentation null would work, and I using it. So if it is not working it is a vscode bug related to null, not undefined.

**Comment by deitry** [comment]
Oh, I get it now.

**Comment by deitry** [comment]
https://github.com/microsoft/vscode/commit/c467419e0e3023668b8f031d3be768b79eeb1eb7
> When `null`, no search excludes will apply, but `files.exclude` will still apply.

This is current behaviour, but I hope there would be discussion on changing it:
https://github.com/microsoft/vscode/issues/77813

**Comment by matepek** [comment]
For default exclude there is `undefined` value.

They reopened your issue 👍

I will close this if you don't mind and hope that vscode fixes its API.
