### ISSUE TITLE
Find tests executable not work for "cin" used in main function

### ISSUE THREAD

**Issue by bigmanvip** [matepek/vscode-catch2-test-adapter#120]
**Checklist** (You can delete this section, don't have to be the part of your issue.)

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug** (A clear and concise description of what the bug is.)
The tests executables can't be found if I add a cin funtion in the main function.
**To Reproduce** (Steps to reproduce the behavior.)

1. write a single googleTest sample with VSCode;
2. add a "cin" fuction in the main funtion and build everything;
3. Open Tests Explorer tab;
4. See that there is no tests, see first screenshot.
5.if you delete the "cin" fuction and build everything again, you will find the tests in the Tests Explorer tab;

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![1](https://user-images.githubusercontent.com/11270576/63003461-c3c9a280-beaa-11e9-8af5-dd05cf308788.png)
![2](https://user-images.githubusercontent.com/11270576/63003565-fe333f80-beaa-11e9-842c-0285eb508af3.png)

**Desktop**

- Extension Version [2.14.1]
- VS Code Version [1.37. 0]
- Catch2/Google Test Version [2.6.5]
- OS Type and Version:Windows 10, 64 Bit

**Log** (Attach log. (optional, Set: `catch2TestExplorer.logfile` and reproduce the bug.) _Warning_: Log probably contains file and test names too.)

**Comment by matepek** [comment]
Hello,

I liked your bug report, so informative with screenshots. 👍

About the `cin`

Test executables usually not expect any input since that limits the automatisation. (Developers use the argument to add new options if there is a need for that.)

I would not suggest to use `cin` when you write tests.
