### ISSUE TITLE
Doesn't find tests

### ISSUE THREAD

**Issue by CDEguia** [matepek/vscode-catch2-test-adapter#125]
- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [X] The latest version of the extension was used.

Description:
Catch2 tests not populating the Test side panel.

**To Reproduce** (Steps to reproduce the behavior.)

1. Go to 'settings.json'
2. use default pattern:
```
"catch2TestExplorer.executables":[
        {
            "name": "${filename}",
            "description": "${relDirpath}/",
            "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*"
        }
    ],
```
3. Click the `Test Explorer: Reload Tests`

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![Screenshot from 2019-08-25 23-11-42](https://user-images.githubusercontent.com/16065545/63669069-e05cb900-c78d-11e9-96a7-7cd7ef9ab60c.png)

**Desktop**

- Extension Version 2.7
- VS Code Version 1.37.1
- Catch2/Google Test Version 2.7
- OS Linux Fedora 30

**Log** Is a separate issue as I can't get it to write. Error is:
```
Couldn't write log file ~/logs/Catch.log: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
```
I will write another bug if I cant find a solution soon

**Comment by matepek** [comment]
Have you tried not to use `~` ?

Also check log output window.

Without the logs I have no information to wokr with.

**Comment by CDEguia** [comment]
Solve: (kinda)
My CMakeList.txt compiles the exe without adding `test` or any other tag to the program name.
So I have to set the ```"catch2TestExplorer.executables": ``` directly to the ```"./build/exeName"```

**Comment by matepek** [comment]
CMake names the executable after the target name:
`add_executable(<targetname>)` will result in `<tagetname>.exe` for sure.

BTW:

You can easly change the target name to something `<targetname>.test`, dont you?

Or you can set the target's property: [RUNTIME_OUTPUT_NAME](https://cmake.org/cmake/help/latest/prop_tgt/RUNTIME_OUTPUT_NAME.html#prop_tgt:RUNTIME_OUTPUT_NAME) to the wished name.
