### ISSUE TITLE
Is it possible to call cmake build before run?

### ISSUE THREAD

**Issue by xgdgsc** [matepek/vscode-catch2-test-adapter#127]
**Is your feature request related to a problem? Please describe.**
Currently when I change code and want to test and click run. It runs the old binary.

**Describe the solution you'd like**
Call cmake build first before run.

**Comment by matepek** [comment]
It works the other way around. You build your binary and the extension detects it an re-run it.
Check [this conversation](https://github.com/matepek/vscode-catch2-test-adapter/issues/116#issuecomment-524634913) for further details.
![enable autorun](https://user-images.githubusercontent.com/16504598/63651515-b00e1e00-c77f-11e9-81f6-ca04537e8b0f.png)

For building from vscode: [check this](https://code.visualstudio.com/docs/editor/tasks).

Here is my tasks.json for example:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "clean rebuild (debug)",
            "type": "shell",
            "group": "none",
            "command": " rm -rf debug; mkdir debug; cd debug; cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../.. && ninja",
            "options": {
                "cwd": "${workspaceFolder}/out"
            },
            "windows": {
                "command": "cmd.exe",
                "args": [
                    "/C",
                    "cd . && cd debug && del /S /Q /F * >NUL && vcvarsall.bat amd64 && cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ../.. && cd ."
                ]
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": []
        },
        {
            "label": "ninja (debug)",
            "type": "process",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "command": "ninja",
            "options": {
                "cwd": "${workspaceFolder}/out/debug"
            },
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": true,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}/out/debug"
                ]
            },
        }
    ]
}
```

**Comment by xgdgsc** [comment]
OK. Thanks.

**Comment by matepek** [comment]
In case somebody find their way here: https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md

**Comment by yudi-azvd** [comment]
@xgdgsc I found a way to run tests automatically. Install the extension [Trigger Task on Save](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave). Configure it to trigger a task with the label, let's say, "Build tests" when files are saved. You can choose which files with patterns (`src/*.cpp`, `tests/*.cpp`).

Then create a task in `.vscode/tasks.json` labeled "Build tests" which will build your tests by calling make, g++ or something else you use in your project. I'm using something like this and it's working fine for now:

```json
{
      "label": "Build tests",
      "type": "shell",
      "presentation": {
        "echo": false,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": false,
        "clear": true
      },
      "command": "make tests", //shell/terminal command to build tests
      "problemMatcher": []
    }
```

And make sure to have autorun from the Test Explorer enabled like matepek mentioned.

Hope it useful.

**Comment by George-Gi** [comment]
I am looking for a way to first build the tests, if a source file has changed, and then run the tests. Ideally this sequence taking place by hitting the "Run Tests" icon. In the TestMate version 4.3.5 I don't see the option "Enable Autorun". Any suggestions?

**Comment by appden** [comment]
Just in case this helps, I have it setup to build my tests with cmake before running tests in the UI.

My `settings.json` includes this:
```json
    "testMate.cpp.test.advancedExecutables": [
        {
            ...
            "runTask": {
                "before": [
                    "build tests",
                ],
            },
        },
    ],
```

And `tasks.json` leverages CMake Tools extension to run the build:
```json
        {
            "label": "build tests",
            "type": "cmake",
            "command": "build",
            "group": "build",
            "targets": [
                "test/all"
            ]
        },
```

**Comment by matepek** [comment]
`${absPathArrayFlat}` and `${absPathConcatWithSpace}` is available as variable.

BUT I cannot tell enough times, this extension follows a logic which is the other way around.
One selects the interesting tests, enables "continuous run" on them then when an executable is rebuilt (changed) the extension will run the tests related to the changed exectuables.

So basically the task one should run is a compilation/build, rest should be automatic.
