### ISSUE TITLE
Size of vsix in version 2.7.3

### ISSUE THREAD

**Issue by aey76** [matepek/vscode-catch2-test-adapter#129]
Hi,
The size of the current version (2.7.3) vsix file size is 1.87MB, the size of version 2.7.1 was around 800K.
There was increase of 1MB between 2.7.1 to 2.7.3, Is it OK ?

**Comment by matepek** [comment]
I added a new package. I can easily imagine that the new package's dependencies caused this increase. So yes. Do you have any issue with this?

**Comment by aey76** [comment]
It's totally fine, just wanted to make sure, thank you.
