### ISSUE TITLE
Add option to run test cases in parallel for single executable

### ISSUE THREAD

**Issue by jwtocient** [matepek/vscode-catch2-test-adapter#131]
I can use the `catch2TestExplorer.workerMaxNumber` setting to run executables in parallel. This is useful, but I have some executables that take much longer than others. 

As motivation, imagine a set of test executables that need to be run. In this set, there is a single executable that will take many hours longer than all other executables combined when run in serial, while the other executables run in minutes/seconds. It can be batched and run in parallel in minutes. Any user who wanted to use vscode-catch2-test-adapter extension would never be able to run the test executables in an timely fashion.

I would like to run mutually exclusive subsets of tests from a single executable in parallel. I would like to add a entry to `catch2TestExplorer.executables` with a field that indicates how to split tests contained in matching executables. 

I would prefer if it was something along the lines of `"testExecutableInParallel: { "defaultBatchSize": 10, "egregiousFixture": 1 }"` to indicate that a matching executable should have no more than 10 tests assigned to a worker thread and a fixture matching the substring/prefix "egregiousFixture" should have no more than 1 test running per worker thread.

While some might say that the user group needs to emit more executables or reduce test runtimes, the reality of the situation is that the user group will not use this extension because the costs of changing build systems and test infrastructure are high and they already have a solution that runs on the order of minutes.

**Comment by matepek** [comment]
I'm thinking about a `suiteFilterRegex` for splitting. I think splitting by suite name should be enough.

Please note how to use the same fixture with different name: 
```
TEST_F(Fixture1, ...) {...}
using Fixture2 = Fixture1;
TEST_F(Fixture2, ...) {...}
```

Example:
```
catch2TestExplorer.executables = {
  {
     "pattern": "exec1",
     "suiteFilterRegex: "^Fixture1$"
  },
  {
     "pattern": "exec1",
     "suiteFilterRegex: "^Fixture2$"
  },
  "catch2TestExplorer.workerMaxNumber": 2
}
```

I know this misses your grouping, but it more simple than you proposal and could be developed in the near future. On the other hand, yours would require a bigger change.

Would my proposal help you?
