### ISSUE TITLE
Karma pops up with reloading tests

### ISSUE THREAD

**Issue by ambitslix** [matepek/vscode-catch2-test-adapter#132]
![Screenshot from 2019-09-18 12-08-49](https://user-images.githubusercontent.com/3694590/65180449-beafc400-da11-11e9-9327-780f9ef0c529.png)
This is a pretty terrible bug. When clicking the test extension icon(flask) on one of my projects that have no test cases the spinner continuously spins while spewing browser pop-ups of karma and multiple npm and browser processes. It's like massive DOS attack and it's difficult to even type anything anywhere. It uses all CPU cores to hog at 100% and the only way to stop it is to go to external console and killall vscode/npm/firefox.

**Comment by matepek** [comment]
Hey there,

Sorry to hear that.

If the pattern is too general like out/**/*test*, it could cause unexpected executable or script execution (with --help argument) which would not just increase the test-loading duration but also could have other unexpected effects. I suggest to have a stricter file-name convention and a corresponding pattern like out/**/*.test.* or out/**/Test.*

If that doesn’t help, please share your log file to investigate the issue. Thanks.

**Comment by ambitslix** [comment]
Hello,

As I said there are no test cases at all in the vscode workspace where this happens, please clarify what you mean by pattern? Happy to provide the log where is it?
