### ISSUE TITLE
Colourized output

### ISSUE THREAD

**Issue by marti32997** [matepek/vscode-catch2-test-adapter#134]
I've noticed that when i run the test from the test adapter, the output wont be colored as opposed to running the executable itself. Would like a colourized output.

**Comment by matepek** [comment]
Which OS?
Which test framework?
Which part of the output you would like to be colorised?

**Comment by marti32997** [comment]
Oh, and also, for bdd, how to configure the output so that it would show up just like in the command interface, instead of appearing in one line in the output? 

This is what I meant

In output, the bdd scenario appears in one continous line
![Screenshot_20191001_081751](https://user-images.githubusercontent.com/53231928/65927469-fc561900-e423-11e9-95e3-b338d464bec4.png)

whereas in the ci interface of catch2, it will appear in multiple line
![Screenshot_20191001_081839](https://user-images.githubusercontent.com/53231928/65927509-27406d00-e424-11e9-8637-c67e485b4759.png)

**Comment by matepek** [comment]
I'm using the XML reporter which is easier to parse, so colouring could be done by manual which is a notable change. I don't think I will have time in the near future. :(

But I can create the multiline stuff.

**Comment by matepek** [comment]
VSCode doe not supports it. https://github.com/microsoft/vscode/issues/571

**Comment by matepek** [comment]
Used some other approach. Some colorization is possible.
It's the first iteration, but still gives something.
