### ISSUE TITLE
Test Name is too long problem

### ISSUE THREAD

**Issue by marti32997** [matepek/vscode-catch2-test-adapter#135]
![Screenshot_20190925_131234](https://user-images.githubusercontent.com/53231928/65574082-ab16d700-df96-11e9-96ca-2c2b433109ce.png)

When doing bdd style test with catch2, if the test name is too long, the test adapter wont list the test at all. Tried to #define CATCH_CONFIG_CONSOLE_WIDTH 300 but it didnt fix the issue. The limit seems to be 68 character, more than that, the test adapter will think it's too long.

**Comment by matepek** [comment]
A common mistake to define this after you include the catch2 header.
It has to be defined before. I suggest defining it through compiler
Or create a wrapper:
catc2wrapper.hpp:
```c++
#define CATCH_CONFIG_CONSOLE_WIDTH 300
#include "catch2.hpp"
```

**Comment by matepek** [comment]
I assume my comment helped and this issue is not relevant anymore.
Feel free to reopen it with detailed bug report (versions, logs, etc..)
