### ISSUE TITLE
Missing "go to source" button in the tests sidebar, and sources are not highlighted

### ISSUE THREAD

**Issue by dan1994** [matepek/vscode-catch2-test-adapter#136]
- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [X] The latest version of the extension was used.

**Describe the bug** (A clear and concise description of what the bug is.)
The extension recognizes the test executable and is able to run tests from the sidebar.
There are 2 problems though:

- In the sidebar, the little icon that links to the source files is missing.
![image](https://user-images.githubusercontent.com/6225230/66692378-a9196d00-ec52-11e9-91f8-935afe331ef8.png)

- There is no highlighting of passed/failed tests in the test sources.

**To Reproduce** (Steps to reproduce the behavior.)
I have a project with the following hierarchy:

```
src/
include/
test/
-- BiMap/
    -- BiMapTests.cpp
build/
-- test/
    -- gtest
```

I haven't changed the default configuration at all.

**Desktop**

- Extension Version 2.7.5
- VS Code Version 1.38.1
- Catch2/Google Test Version [Not sure]
- OS Type and Version Ubuntu 18.04

**Comment by matepek** [comment]
Hello,

That two symptoms probably has the same source.
Please set: `catch2TestExplorer.logfile` or `catch2TestExplorer.logpanel`  and reproduce the bug, then send me the log.

**Comment by dan1994** [comment]
[catch2.log](https://github.com/matepek/vscode-catch2-test-adapter/files/3720265/catch2.log)

The log file was populated by a refresh to the tests and running them.
Opening the source file didn't seem to affect anything.
I did notice the following line which seemed suspicious:

```
[2019-10-12 06:08:34.585] [INFO] [at LogWrapper.info (/home/dan/.vscode/extensions/matepek.vscode-catch2-test-adapter-2.7.5/out/src/LogWrapper.js:22:22)] Couldn't parse output file. Possibly it is an older version of Google Test framework. It is trying to parse the output
```

Thanks!

**Comment by matepek** [comment]
Yeas, so if you are using an older version of google test framework, which doesn't produce an xml output, the extension cannot know the source file's location.

You can verify it with calling your test exec with `--gtest_list_tests --gtest_output=xml:testlist.xml`

**Comment by dan1994** [comment]
I received the following output: 
```
$ build/test/gtest --gtest_list_tests --gtest_output=xml:testlist.xml
Running main() from gtest_main.cc
BiMap.
  AccessNotExistingT
  AccessNotExistingU
  InsertionToEmptyBiMap
  ValidInsertion
  AccessExistingT
  AccessExistingU
  ConflictInsertionPair
  ConflictInsertionT
  ConflictInsertionU
```

**Comment by dan1994** [comment]
Just installed gtest 1.10 from source and the problem was solved!
Apparently the version in the Ubuntu repos is 1.8, which I guess is too old...
