### ISSUE TITLE
Files are opened with name changed to lowercase

### ISSUE THREAD

**Issue by evakili** [matepek/vscode-catch2-test-adapter#141]
- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [x] The latest version of the extension was used.

In the test explorer click on a test that resides in a file with a name such as `TestClass.cpp`. Then the editor opened with name `testcase.cpp`. This cause some problems for example if the file was opened, there we have two tabs for one file, and intellisense will be disabled in second file, and...

- Extension Version [e.g. 2.7.6]
- VS Code Version [e.g. 1.40.1]
- Google Test Version [e.g. 1.8]
- OS Type and Version: Windows 10 x64 1909

**Comment by matepek** [comment]
Hey,

I see your problem. This extension reads the data from the test framework, it does not bother normalizing it. It could, but since it just forwards the info to another extension (on which this was built upon) I think the proper solution would be to do some normalization there: https://github.com/hbenl/vscode-test-explorer

I created an [issue](https://github.com/hbenl/vscode-test-explorer/issues/101). Thanks for letting us know about this.

**Comment by evakili** [comment]
Thanks!

**Comment by matepek** [comment]
@evakili Just wondering which compiler do you use? msvc I guess.

**Comment by evakili** [comment]
@matepek Yes! MSVC.

**Comment by matepek** [comment]
Related: 
- https://developercommunity.visualstudio.com/content/problem/211662/-file-macro.html
- https://docs.microsoft.com/en-us/cpp/build/reference/fc-full-path-of-source-code-file-in-diagnostics?view=vs-2019

**Comment by evakili** [comment]
After a few search about the problem, I think this issue is neither tools like msvc++ nor vscode extension. It's vscode issue that opens same file in two tabs.

**Comment by matepek** [comment]
Found [it](https://github.com/microsoft/vscode/issues/12448).

**Comment by evakili** [comment]
Our project is compiled with Visual C++ 2015. I test it with Visual C++ 2019 and the paths generated by `gtest` (that in fact are __FILE__ macro expansions) are with right case, so the issue is not seen in VC++ 2019.

**Comment by matepek** [comment]
I assume you just mentioning this for the sake of completeness.
Otherwise I don't understand what is your intention. :)

**Comment by evakili** [comment]
You are correct ;)
