### ISSUE TITLE
stop running tests after printf function

### ISSUE THREAD

**Issue by MilanBacaCz** [matepek/vscode-catch2-test-adapter#142]
If the google test or any function inside google test contains **printf** or **std::cout** functions,
```
printf("Is True");
```
 it ends as unexpected error and all next test will stop running.
But if the printf command will have new line symbol at the end of text 
```
printf("Is True \n");
```
next tests are continue running as expected
**this fail**
```
TEST_F(Temp, setTemp)
{
        printf("Is True");
}
```
**this is OK**
```
TEST_F(Temp, setTemp)
{
        printf("Is True \n");
}
```

**Comment by matepek** [comment]
fixed in v2.7.7
