### ISSUE TITLE
Easier select build kit test

### ISSUE THREAD

**Issue by xgdgsc** [matepek/vscode-catch2-test-adapter#145]
**Is your feature request related to a problem? Please describe.**
I have multiple buildkit inside cmake to switch between compilers like GCC and Clang, there are build folders for both and Debug/Release. Currently there' s no way I can know which executable to run when I click the Run|Debug inside code.

**Describe the solution you'd like**
I want to set the executable of kit easier, and then click on the button inside code.

**Describe alternatives you've considered**
 Now I have to click the Test Explorer and run Debug from there.

**Comment by matepek** [comment]
Hello,

If my understanding is correct, you can run all the variations with the text explorer from the tree view. What you want is that running it from the code (button above the test name), right?

Here is the thing. This extension has built upon the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer).
What I do I gather all the tests and pass them to it. 

More than 1 of your tests refer to the same line of code but the Test Explorer UI don't handle it just shows one of it.

I suggest you to open an issue in that repo and link this issue there. I cannot solve it in this repo due I have no control over that part.
