### ISSUE TITLE
Use working directory specified for Catch2 in CMakeLists.txt

### ISSUE THREAD

**Issue by TheButlah** [matepek/vscode-catch2-test-adapter#150]
**Is your feature request related to a problem? Please describe.**
I am using Catch2, CMake, and CTest. I specify the working directory that my Catch2 tests should run in in the CMakeLists.txt file via the `catch_discover_tests` command. This command registers the Catch2 tests with CMake's tests, and properly configures the desired working directory. However, this setting is ignored by this VSCode extension.

**Describe the solution you'd like**
I would like the extension to use the configuration specified by the `catch_discover_tests` command, specifically the `WORKING_DIRECTORY` property.

**Describe alternatives you've considered**
It is possible that this is out of scope of this extension and I would be better off using the CMake Test Explorer, since my approach is already to register all Catch2 tests with CMake. However, I believe that there is no reason not to include this feature.

**Additional context**
My CMakeLists looks something like the following:
```CMake
# ..... A bunch of other targets here ....

# Test artifact
add_executable(realsense_test
  realsense_test.cpp)
target_link_libraries(realsense_test
  PRIVATE
    Catch2::Catch2
    nlohmann_json::nlohmann_json
    realsense_lib)

# Integrate catch2 tests into CTest
include(Catch)
# Adopt convention of always referring to paths with respect to project root
catch_discover_tests(realsense_test WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
```

**Comment by matepek** [comment]
Hello,
First of all I haven't used this feature so I might wrong about how it works so feel free to correct my assumptions.

The biggest problem with this: How exactly should the extension get the working directory from cmake? I don't see any convenient way to do it. (It could parse the cmake file but nobody wants that.)

**Comment by matepek** [comment]
Tell me more about your project directory structure. (Where is the exec, where are the resources..)
You might can use `cwd` to solve your problem.

Worst case scenario, you can define multiple entries with different `cwd`s like:
```
"catch2TestExplorer.executables": [
	{
		"pattern": "test1",
		"cwd": "cwd1"
	},
	{
		"pattern": "test2",
		"cwd": "cwd2"
	}
]
```

**Comment by matepek** [comment]
I improved variable resolution. Check [it](https://github.com/matepek/vscode-catch2-test-adapter#faq).
I think it will solve your problem.

**Comment by lordmauve** [comment]
> How exactly should the extension get the working directory from cmake?

`ctest` spits out its registry of tests, working directories etc, with `ctest --show-only=json-v1`
