### ISSUE TITLE
Absolute beginner help

### ISSUE THREAD

**Issue by sreekanthr** [matepek/vscode-catch2-test-adapter#152]
Hi team,
     I have no clue why my test cases are not visible in the test explorer.
I am new to unit testing in vs code, and it seems I am missing something very basic.
Could you please help me with a step by step hello world example, on how to setup google unit test cases with this test adapter/explorer.

**settings.json**
cat /Users/sree/work/samples/algos/.vscode/settings.json
{
    "catch2TestExplorer.executables": "/Users/sree/work/test/",
    "catch2TestExplorer.logfile": "~/work/test/vs_test_ext.log"
}

**google test executable**:
/Users/sree/work/test/bst_test 
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from basic_bst_test
[ RUN      ] basic_bst_test.init_test
[       OK ] basic_bst_test.init_test (0 ms)
[----------] 1 test from basic_bst_test (0 ms total)

[----------] 1 test from basic_bst_test2
[ RUN      ] basic_bst_test2.init_test
[       OK ] basic_bst_test2.init_test (0 ms)
[----------] 1 test from basic_bst_test2 (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 2 tests.

**Comment by matepek** [comment]
Did you solve it?

**Comment by sreekanthr** [comment]
> Did you solve it?

No - Not yet

**Comment by matepek** [comment]
The `catch2TestExplorer.executables` expects a glob pattern not a directory.
Like: `"catch2TestExplorer.executables": "/Users/sree/work/test/*",`
