### ISSUE TITLE
ability to force using a binary

### ISSUE THREAD

**Issue by MrZaus** [matepek/vscode-catch2-test-adapter#155]
Please do allow to force using a binary as a valid gtest binary. Chromium uses wrappers around gtest, so those binaries are not recognized by the plugin due to different help string.

**Comment by matepek** [comment]
I don’t get it. Please explain

**Comment by matepek** [comment]
Okay I got it. Let me think of a solution

**Comment by MrZaus** [comment]
You might allow to override from config the string with hardcoded 'This
program contains tests written using Google Test.'

czw., 30 sty 2020 o 10:40 Mate Pek <notifications@github.com> napisał(a):

**Comment by matepek** [comment]
have fun
