### ISSUE TITLE
test output not shown

### ISSUE THREAD

**Issue by dvirtz** [matepek/vscode-catch2-test-adapter#158]
**Describe the bug** (A clear and concise description of what the bug is.)

After running some tests, the test explorer shows a red triangle sign with the message "Check the test output message for detail" but no output is shown.

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/7661709/74144827-21df0480-4c06-11ea-99a5-9e5951d87480.png)

**Desktop**

- Extension Version: 2.8.5
- VS Code Version: 1.42.0
- Catch2/Google Test Version: gtest 1.7.0
- OS Type and Version: MacOs Catalina

**Log**
https://gist.github.com/dvirtz/293406f4865bbcb9c216a0de033739e9

**Comment by matepek** [comment]
Hey,
I improved the logging. So the next version's log might would help. Until you might can send the executable or a minified executable whit I can reproduce the issue.

**Comment by matepek** [comment]
By the way have you selected the test by clicking on it?

**Comment by dvirtz** [comment]
Yes. Unfortunately I wasn't able to generate a minimal reproducer and I'm
not able to share my code.
When the next version will be released?

**Comment by matepek** [comment]
And what was the content of the output window?

**Comment by MilanBacaCz** [comment]
Hi I have same problem. Unfortunately I can't share any of the code :-(

**Comment by matepek** [comment]
How about the log? `catch2TestExplorer.logpanel: true`

**Comment by MilanBacaCz** [comment]
[2020-02-17 06:42:34.073] [INFO] reloadChildren dclicomponents_integration_test GoogleTest Promise { undefined } /home/Build/SharedLibrary/components/integration_test
[2020-02-17 06:42:34.102] [WARN] reloadChildren -> googleTestListOutput.stderr:  {
  pid: 93135,
  output: [
    null,
    'GetHandler.\n  UploadFailes\n  InstanceReuse\n',
    '2020-02-17T07:42:34.089521+0100 ALWAYS ' +
      '[Log]: Setting logger output stream to ' +
      '/dev/null.\n'
  ],
  stdout: 'GetHandler.\n  UploadFailes\n  InstanceReuse\n',
  stderr: '2020-02-17T07:42:34.089521+0100 ALWAYS ' +
    '[Log]: Setting logger output stream to ' +
    '/dev/null.\n',
  status: 0,
  signal: null,
  error: undefined,
  closed: true,
  process: ChildProcess {
    _events: [Object: null prototype] { error: [Function], close: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 3,
    connected: false,
    signalCode: null,
    exitCode: 0,
    killed: false,
    spawnfile: '/home/Build/SharedLibrary/components/integration_test',
    _handle: null,
    spawnargs: [
      '/home/Build/SharedLibrary/components/integration_test',
      '--gtest_list_tests',
      '--gtest_output=xml:/home/Build/SharedLibrary/components/integration_test.cache.xml'
    ],
    pid: 93135,
    stdin: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: true,
        emitClose: false,
        autoDestroy: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object]
      },
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(asyncId)]: 28669,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: false,
        emitClose: false,
        autoDestroy: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      _events: [Object: null prototype] {
        end: [Function: onReadableStreamEnd],
        close: [Function],
        data: [Function]
      },
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object]
      },
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 28670,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 47,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: false,
        emitClose: false,
        autoDestroy: false,
        destroyed: true,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
      },
      readable: false,
      _events: [Object: null prototype] {
        end: [Function: onReadableStreamEnd],
        close: [Function],
        data: [Function]
      },
      _eventsCount: 3,
      _maxListeners: undefined,
      _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object]
      },
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 28671,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 96,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [
      Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        [Symbol(asyncId)]: 28669,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        write: [Function: writeAfterFIN],
        [Symbol(asyncId)]: 28670,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 47,
        [Symbol(kBytesWritten)]: 0
      },
      Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        write: [Function: writeAfterFIN],
        [Symbol(asyncId)]: 28671,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 96,
        [Symbol(kBytesWritten)]: 0
      }
    ]
  }
}
[2020-02-17 06:42:34.103] [INFO] load finished 7

**Comment by MilanBacaCz** [comment]
I hope it helps to you

**Comment by matepek** [comment]
The problem in your case @MilanBacaCz is that your executable emits a message to stderr:
```
2020-02-17T07:42:34.089521+0100 ALWAYS [Log]: Setting logger output stream to /dev/null.
```
The adapter notices it and assumes that there is some problem.

This is the test listing phase. The executable called with `--gtest_list_tests`

**Comment by MilanBacaCz** [comment]
If i run the executable from command line it works.  How can i configure it?

**Comment by matepek** [comment]
The command line don't parse the output.

When you listing tests you might don't need to redirect logger output stream and you don't have to write to *stderr*. That would soulve your problem.

Just guessing:
> Redirect from *SetUp*, don't redirect from constructor.

**Comment by MilanBacaCz** [comment]
The logs are somewhere in the code. Not directly in tests. If this is no Issue of adapter, so it is very bad for me :-( i have to leave from visualcode and have to using qt creator. Where the tests work ok.

S pozdravem,
Milan Bača

**Comment by matepek** [comment]
Usually something on stderr indicates some issue which should not be ignored. That's why I wouldn't change the current behavior. But a switch can be added to ignore that in the future.

**Comment by dvirtz** [comment]
It's the same issue for me - test writes to stderr.
Fortunately, I can modify the test to disable the output when listing tests and now I can run them with the extension. Thanks.

**Comment by matepek** [comment]
@MilanBacaCz check documentation for `ignoreTestEnumerationStdErr`. That should workaround your issue. But I don't consider this as a good approach because if there are other errors emitted by the framework those won't be noticed. So **before you report another bug, please make sure, it is not related to this.**
