### ISSUE TITLE
TEST_P not correctly recognized

### ISSUE THREAD

**Issue by NINI1988** [matepek/vscode-catch2-test-adapter#159]
**Describe the bug**
When using TEST_P, the test adapter only recognize the first test correctly.
The second test has no menu bar in the code window (first screenshot).
Also in the Test Explorer(side window) the button "Show source" jumps only to the first test case.

In the Test Explorer(side window) the tests are listed correctly (second screenshot).

The unittest code is from https://github.com/google/googletest/blob/master/googletest/samples/sample7_unittest.cc

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![InCode](https://user-images.githubusercontent.com/2767665/74750276-c77c1e80-526b-11ea-84bf-3454023fb098.PNG)

![TestExplorer](https://user-images.githubusercontent.com/2767665/74751902-35c1e080-526e-11ea-9b6b-39e87e27076c.PNG)

**Desktop**

- Extension Version [2.8.5]
- VS Code Version [1.42.1]
- Catch2/Google Test Version [1.8.1]
- Windows 10

**Comment by matepek** [comment]
Hello,
Excellent bug report 💙

However the issue is related to Google Test framework.
If you call the executable with `--gtest_list_tests --gtest_output=xml:x.xml` parameters you will get something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="6" name="AllTests">
  <testsuite name="OnTheFlyAndPreCalculated/PrimeTableTestSmpl7" tests="6">
    <testcase name="ReturnsFalseForNonPrimes/0" value_param="0x10958da30" file="../../x.test.cpp" line="79" />
    <testcase name="ReturnsFalseForNonPrimes/1" value_param="0x10958da70" file="../../x.test.cpp" line="79" />
    <testcase name="ReturnsTrueForPrimes/0" value_param="0x10958da30" file="../../x.test.cpp" line="79" />
    <testcase name="ReturnsTrueForPrimes/1" value_param="0x10958da70" file="../../x.test.cpp" line="79" />
    <testcase name="CanGetNextPrime/0" value_param="0x10958da30" file="../../x.test.cpp" line="79" />
    <testcase name="CanGetNextPrime/1" value_param="0x10958da70" file="../../x.test.cpp" line="79" />
  </testsuite>
</testsuites>
```

This is what the extension processes. It might worth to let google know about this but most probably it is a known limitation.

**Comment by NINI1988** [comment]
Thank you for your really fast reply.
I have opened a googletest issue:
https://github.com/google/googletest/issues/2717

**Comment by matepek** [comment]
I saw your PR 👍
