### ISSUE TITLE
File is not created when run test

### ISSUE THREAD

**Issue by MilanBacaCz** [matepek/vscode-catch2-test-adapter#160]
Hi, I have strange issue.
I have test as belov

```
TEST_F(CertificateStorageHandlerTest, makeCertTest)
{
    FILE* fp;
    std::string command("openssl ecparam "
                        "-genkey "
                        "-name prime256v1 "
                        "| openssl ec "
                        "-aes-128-cbc "
                        "-out /tmp/pokus/pokus.key");

    fp = popen(command.c_str(), "r");
    int closeResult = pclose(fp);
    std::cout << closeResult;
}
```
when i run this test from commandline or from qtcreator, the file is created. But Run this test from this extension - the file is not created.

output of test
```[ RUN      ] PokusTest.makeTest
read EC key
Segmentation fault
unable to load Key
140555366383680:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:686:Expecting: ANY PRIVATE KEY
256[       OK ] PokusTest.makeTest (13 ms)
```

**Comment by matepek** [comment]
Hello. Please attach some log. Check the development branch’s readme to
check how to.

**Comment by MilanBacaCz** [comment]
[2020-02-21 08:07:43.491] [INFO] proc starting componnents_unit_test [
  '--gtest_color=no',
  '--gtest_filter=PokusUnitTest.makePokusTest',
  '--gtest_also_run_disabled_tests'
]
[2020-02-21 08:07:43.500] [INFO] proc started: componnents_unit_test {
  path: '/home/pokus/space/Build/SharedLibrary/componnents/componnents_unit_test',
  options: {
    cwd: '/home/pokus/space/Build/SharedLibrary/componnents',
    env: {
      ELECTRON_RUN_AS_NODE: '1',
      HTTPS_PROXY: 'http://127.0.0.1:3128/',
      USER: 'pokus',
      no_proxy: 'localhost,127.0.0.1,localaddress,.localdomain.com',
      LC_TIME: 'en_US.UTF-8',
      XDG_SEAT: 'seat0',
      XDG_SESSION_TYPE: 'x11',
      SSH_AGENT_PID: '1637',
      HOME: '/home/pokus',
      NO_PROXY: 'localhost,127.0.0.1,localaddress,.localdomain.com',
      DESKTOP_SESSION: 'default',
      LC_MONETARY: 'en_US.UTF-8',
      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/1000/bus',
      https_proxy: 'http://127.0.0.1:3128/',
      LOGNAME: 'pokus',
      http_proxy: 'http://127.0.0.1:3128/',
      XDG_SESSION_CLASS: 'user',
      USERNAME: 'pokus',
      XDG_SESSION_ID: '2',
      WINDOWPATH: '2',
      PATH: '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games',
      _JAVA_OPTIONS: '-Djava.net.useSystemProxies=true',
      GDM_LANG: 'en_US.UTF-8',
      ftp_proxy: 'http://127.0.0.1:3128/',
      XDG_RUNTIME_DIR: '/run/user/1000',
      DISPLAY: ':0',
      LANG: 'en_US.UTF-8',
      XDG_SESSION_DESKTOP: 'default',
      XAUTHORITY: '/run/user/1000/gdm/Xauthority',
      SSH_AUTH_SOCK: '/run/user/1000/keyring/ssh',
      SHELL: '/bin/bash',
      GDMSESSION: 'default',
      QT_ACCESSIBILITY: '1',
      LC_MEASUREMENT: 'en_US.UTF-8',
      GPG_AGENT_INFO: '/run/user/1000/gnupg/S.gpg-agent:0:1',
      XDG_VTNR: '2',
      PWD: '/home/pokus',
      FTP_PROXY: 'http://127.0.0.1:3128/',
      XDG_DATA_DIRS: '/usr/share/gnome:/usr/local/share/:/usr/share/',
      HTTP_PROXY: 'http://127.0.0.1:3128/',
      LC_NUMERIC: 'en_US.UTF-8',
      LC_PAPER: 'en_US.UTF-8',
      XDG_CURRENT_DESKTOP: 'GNOME',
      GNOME_DESKTOP_SESSION_ID: 'this-is-deprecated',
      XDG_MENU_PREFIX: 'gnome-',
      QT_QPA_PLATFORMTHEME: 'qgnomeplatform',
      SESSION_MANAGER: 'local/pokusdebpokus.tech.emea.pokus.biz:@/tmp/.ICE-unix/1588,unix/pokusdebpokus.tech.emea.pokus.biz:/tmp/.ICE-unix/1588',
      GIO_LAUNCHED_DESKTOP_FILE: '/usr/share/applications/code.desktop',
      GIO_LAUNCHED_DESKTOP_FILE_PID: '1829',
      GJS_DEBUG_OUTPUT: 'stderr',
      GJS_DEBUG_TOPICS: 'JS ERROR;JS LOG',
      NO_AT_BRIDGE: '1',
      CHROME_DESKTOP: 'code-url-handler.desktop',
      VSCODE_NLS_CONFIG: '{"locale":"en-us","availableLanguages":{},"_languagePackSupport":true}',
      VSCODE_NODE_CACHED_DATA_DIR: '/home/pokus/.config/Code/CachedData/c47d83b293181d9be64f27ff093689e8e7aed054',
      VSCODE_LOGS: '/home/pokus/.config/Code/logs/20200221T050155',
      VSCODE_IPC_HOOK: '/run/user/1000/vscode-ed584bc5-1.42.1-main.sock',
      VSCODE_PID: '1829',
      LS_COLORS: '',
      SHLVL: '1',
      _: '/usr/share/code/code',
      AMD_ENTRYPOINT: 'vs/workbench/services/extensions/node/extensionHostProcess',
      PIPE_LOGGING: 'true',
      VERBOSE_LOGGING: 'true',
      VSCODE_IPC_HOOK_EXTHOST: '/tmp/vscode-ipc-a37da844-82b4-4506-951c-69432493e55f.sock',
      VSCODE_HANDLES_UNCAUGHT_ERRORS: 'true',
      VSCODE_LOG_STACK: 'false',
      APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL: 'true',
      LD_LIBRARY_PATH: '/opt/pokus/debian-sysroot/usr/lib:/opt/pokus/debian-sysroot/lib'
    }
  },
  additionalRunArguments: []
} [
  '--gtest_color=no',
  '--gtest_filter=PokusUnitTest.makePokusTest',
  '--gtest_also_run_disabled_tests'
];
[2020-02-21 08:07:43.510] [INFO] Test PokusUnitTest.makePokusTest has started.
[2020-02-21 08:07:43.579] [INFO] Test  PokusUnitTest.makePokusTest has finished.
[2020-02-21 08:07:43.582] [DEBUG] proc close: componnents_unit_test [ 0, null ]
[2020-02-21 08:07:43.582] [INFO] proc finished: /home/pokus/space/Build/SharedLibrary/componnents/componnents_unit_test

**Comment by MilanBacaCz** [comment]
[ RUN      ] PokusUnitTest.makePokusTest
Segmentation fault
Exit code:1
Segmentation fault
Exit code:1
Segmentation fault
Exit code:1
Segmentation fault
Exit code:1
read EC key
unable to load Key
Segmentation fault
139918139719744:error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:686:Expecting: ANY PRIVATE KEY
256[       OK ] PokusUnitTest.makePokusTest (69 ms)

**Comment by matepek** [comment]
Okay, thanks.
The log seems fine.
Try to set `cwd` like this:
```
"catch2TestExplorer.executables": [
            {
                 "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
                 "cwd": "${absDirpath}"
            }
]
```

**Comment by MilanBacaCz** [comment]
I have it already as you suggest.

**Comment by matepek** [comment]
Probably some env related stuff. check `set` output and compare with you can see in the log. You should find some openssl related stuff. This is my guess

**Comment by MilanBacaCz** [comment]
Hi, you have right. All it is Ok now. I do not know where the problem was :-( I am appologize for this false bug.

S pozdravem,
Milan Bača

**Comment by matepek** [comment]
No worries,
Happy to help.

My 2 pennies that you started the vscode from command line now. But before you started in a different way.
