### ISSUE TITLE
Ability to run only failing tests

### ISSUE THREAD

**Issue by helloworldhello762976h9f7tb34y8t7** [matepek/vscode-catch2-test-adapter#168]
**Is your feature request related to a problem? Please describe.**
Running only failed tests is cumbersome.

**Describe the solution you'd like**
Another play button specifically for failed tests only

**Comment by matepek** [comment]
Hello,

UI related errors and requests please report [here](https://github.com/hbenl/vscode-test-explorer)

**Comment by matepek** [comment]
Btw failing tests can be misleading. For example let's say you have 3 tests testing the same function.
Number 1,2 are ok but 3 is failing.
If you change your function and rerun only the #3 then there is no guarantee that #1 and #2 will remain ok.

So you have to run all the test executables related to that function.
When you hit build your build tool will recompile only the modified executables. (hopefully)
That change will be detected by this extension and will mark the related test suite as outdated.

With the "Enable autorun" feature (see screenshot in readme) those tests will be rerun automatically. Yes it can rerun a tons of different tests too which share the same executable. Splitting executables would solve this too.
