### ISSUE TITLE
Doctest 2.3.7 show source does not work.

### ISSUE THREAD

**Issue by rurabori** [matepek/vscode-catch2-test-adapter#169]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug**

Show code when using `doctest` fails with error shown in Log. The issue seems to arise from value of macro `__FILE__` being exactly what the extension tries to open. As the path is relative this won't work, it has to adjust the path according to build dir itself (or rather path to `build.ninja`). The same setup with Catch2 works just fine so you probably have this resolved anyway.

**To Reproduce**
Setup: CMake 3.16 & Ninja

1. Create folder `build`.
2. From `build` folder configure cmake and build the tests (I'm using add_test to enable CTest but that should not matter).
2. In test explorer click on show code.

**Desktop**

- Extension Version: 2.8.12
- VS Code Version: 1.43.2
- Catch2 / Google Test / DOCTest Version: 2.3.7
- OS Type and Version: Windows 10 19582 also tried on WSL2 (Ubuntu 20.04)

**Log** (optional but recommended)

```Error running command test-explorer.show-source: cannot open file:///../tests/unit/test_keystore.cpp. Detail: Unable to read file '\..\tests\unit\test_keystore.cpp' (Error: Unable to resolve non-existing file '\..\tests\unit\test_keystore.cpp'). This is likely caused by the extension that contributes test-explorer.show-source.```

**Comment by rurabori** [comment]
I think it may be caused by not having `pathlib.normalize(file)` in the DOCtest version. But I do not know TypeScript at all so take that with a grain of salt.

**Comment by matepek** [comment]
It works for me on macOS.
I use path.normalize [everywhere](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/AbstractTestInfo.ts#L31).

Try clone this repo and
```
cd <thisrepo>
cd out
mkdir mycpptest
cd mycpptest
cmake -G Ninja ../../test/cpp
ninja
```

Then try those tests.

Note: DOCTest version is currently set to 2.3.6. You can change that in DOCTest.cmake but I don't think that will make a difference.

**Comment by rurabori** [comment]
@matepek You're absolutely correct. I gave you wrong reproduction steps. I use `CMake Tools`  so I didn't configure CMake by hand as I said. To really reproduce then:
1. Checkout your repo.
2. Get `CMake Tools extension` (ms-vscode.cmake-tools).
2.1. Set `Cmake Default: Generator` to `Ninja` in your settings, or in `settings.json`
```
"cmake.generator": "Ninja"
```
3. Add this `CMakeLists.txt` to root of your repo:
```
project(Test)

add_subdirectory(test/cpp)
```
4. Open command pallete and run `CMake: Configure`
5. Open command pallete and run `CMake: Build`

The difference between the two (if you inspect `build.ninja`) is, that the manual cmake configuration passes full paths to cpp files, but the `CMake Tools` versions passes relative paths. GTest works in this scenario, doctest doesnt.

> I use path.normalize everywhere.

Sorry, I tried to figure out what was wrong on my own and that was the only difference I saw on the first glance. As I said, never used TypeScript in my life.

**Comment by rurabori** [comment]
@matepek I've checked out your repository, built the module and debugged this myself. The issue isn't in the normalize. You were correct. The issue is, that, in Catch2 and GTest, you're using `_findFilePath` but not in `doctest`. I've created #171 to fix the issue.

**Comment by matepek** [comment]
Nice. Thanks.
Will be released in the next version.

**Comment by rurabori** [comment]
> Nice. Thanks.
> Will be released in the next version.

No problem mate, awesome extension 👍

**Comment by matepek** [comment]
I was just wondering that is the error gutters are working or not. Because the advanced path resolution `_findPath` is only applied in case of the executable. If yes, I'm wondering how. If not then it is something what should be fixed.
Let me know if you see other errors.
