### ISSUE TITLE
How to get meson and msys2/mingw64 tests to show in Test Explorer

### ISSUE THREAD

**Issue by BrendanSimon** [matepek/vscode-catch2-test-adapter#174]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug**

I doubt this is a bug, but I can't get any tests to show up in the Test Explorer.

I'm using the meson build system to build my test exes, and I can run them fine from the CLI (MSYS2 bash console).

I suspect it's something to do with msys2/mingw64 DLLs and search paths, as I can't run the exes from an DOS prompt (Windows 10 Pro).

I've added the `C:\msys64\mingw64\bin` to my path, so the exes now run from a standard DOS prompt.

**To Reproduce**

    1. Create a directory called `test`
    2. Place in the `doctest.h` or `catch.hpp` header files
    3. Add the `doctest.cpp` or `catch.cpp` tutorial sample for factorial test.
    4. Create a `meson.build` file and run `meson build`, then `ninja -C build`
    5. Try to refresh Test Explorer (also tried restarting vscode too)
    6. Run exes in the build directory directly or via `ninja -C build test`

** Output **

NOTE: I inserted an intentional fail in my test cases :)

```
D:\Brendan\XXX\test>build\doctest_test.exe
[doctest] doctest version is "2.3.7"
[doctest] run with "--help" for options
===============================================================================
../doctest_test.cpp:28:
TEST CASE:  testing the factorial function

../doctest_test.cpp:34: ERROR: CHECK( factorial(10) == 3628801 ) is NOT correct!
  values: CHECK( 3628800 == 3628801 )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |      0 skipped
[doctest] assertions:      5 |      4 passed |      1 failed |
[doctest] Status: FAILURE!
```

```
D:\Brendan\XXX\test>build\catch_test.exe

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
catch_test.exe is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
Factorials are computed
-------------------------------------------------------------------------------
../catch_test.cpp:28
...............................................................................

../catch_test.cpp:34: FAILED:
  REQUIRE( factorial(10) == 3628801 )
with expansion:
  3628800 (0x375f00) == 3628801 (0x375f01)

===============================================================================
test cases: 1 | 1 failed
assertions: 5 | 4 passed | 1 failed
```

**Screenshots** (optional)

- Extension Version: 2.17.0 (Test Explorer UI)
- VS Code Version: 1.44.0
- Catch2 / Google Test / DOCTest Version: 2.8.13
- OS Type and Version: Windows 10 Pro

**Log** (optional but recommended)

[meson-log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/4469751/meson-log.txt)

**Comment by BrendanSimon** [comment]
Ok, I had to modify the `executables` setting and prepend it with `**/`.

```
"catch2TestExplorer.executables": [ "**/{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*" ]
```

I assume that most projects wouldn't have the `build` directory at the root, so I figured the preset settings should work for any depth of the `build/**/test`, but not the case.

Is my assumption wrong?

Maybe the preset configuration should be tweaked to prepend the `**/` for any directory depth?

**Comment by matepek** [comment]
Hello,

The [default](https://github.com/matepek/vscode-catch2-test-adapter#configuration) value is 
`"{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*"`
This is equivalent to 
`"${workspaceDirectory}/{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*"`.
(`${workspaceDirectory}` is the "root" directory of the vscode project)

You say that 
> I assume that most projects wouldn't have the build directory at the root,

But in your example you have build directory at the root:
> D:\Brendan\XXX\test>build\doctest_test.exe

I don't understand you.
(I assumed your workspace directory is `D:\Brendan\XXX\test`)

**Comment by BrendanSimon** [comment]
Yeah, sorry about that.  I edited the paths to make it simpler.  The real path is:
```
D:\Brendan\MyProject\SW\App1\test\build\doctest_test.exe
```

The workspace is at:
```
D:\Brendan\MyProject\
```

**Comment by matepek** [comment]
If `D:\Brendan\MyProject\` is your workspace directory
```
code D:\Brendan\MyProject\
```
then your executable is under the `.\SW\App1\test\build\doctest_test.exe` relative path.

In this case the default value 
(`"{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*"`) wont find it of course because there is no `build` directory in the root.

You solved it the issue for your self figuring out whats wrong so I will close this.

About tweaking the default..
The stricter patter is the better because then less directories and files are scanned for test executables. This fastens the load time. It is recommended for everybody to customise it though I had to provide a default value which works in most of the cases. Your suggestion would work too and it would be more general than the current one but my experience is that the build directory is usually in the root.
Until a lot of people mention this I would rather not change.

Anyhow thanks. Feel free to ask any questions.

**Comment by BrendanSimon** [comment]
No worries.

The way we use git at my work place is to have one git repo for each project, and most projects have PCB directory for PCB design files (could be many), and a SW directory for software (which could include embedded software for user, or production, and PC software for users and production, test, etc).

Maybe a note int the documentation to customise it (and where?  workspace settings.json? or .vscode/settings.json?), and maybe a some examples for deeper build directories.

**Comment by matepek** [comment]
If most of you are using vscode then I would put the modified setting to .vscode/settings.json.
With this you would share the configuration. If only you are using vscode then the global settings.json seems a proper place. (In this case I guess you gitignore the .vscode directory anyway)

I have this documentation:
- https://github.com/matepek/vscode-catch2-test-adapter#configuration
- https://github.com/matepek/vscode-catch2-test-adapter#catch2testexplorerexecutables

Would you be more specific about what do you miss please. :)

**Comment by BrendanSimon** [comment]
Sorry for late reply.  All I was thinking was a statement regarding this in the documentation.

Something along the lines of:

Many projects have a `build` directory at the top level, thus the default setting to search for tests is:

```
"catch2TestExplorer.executables": [ "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*" ]
```

If your build directory is located elsewhere, then you will need to modify the setting.

If you have multiple build directories then modify to use recursive directory search path.  Example:
 
```
"catch2TestExplorer.executables": [ "**/{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*" ]
```

NOTE: The settings file can reside in a `.vscode` directory and/or vscode workpace directory.  Choose what makes the most sense for your use case (shared or non-shared settings).
