### ISSUE TITLE
Tree-view based on catch2 tags ?

### ISSUE THREAD

**Issue by t3fi** [matepek/vscode-catch2-test-adapter#175]
**Is your feature request related to a problem? Please describe.**
I've too many scenarions without naming convention in single catch2 executable. Scenario names are also too long, making the tags to go outside the explorer view. I was hoping "testExplorer.mergeSuites" to solve my problem, but no. 

**Describe the solution you'd like**
A way to configure catch2 tags to beginning of line, preferably also ordered in tree-hierarchy similar as in the case of gtests (also in example shown in front page of this extension)

**Describe alternatives you've considered**
- renaming scenarios is not plausible as not all developers use the extension

**Comment by matepek** [comment]
Well the main issue with this approach is that one cannot build a tree from labels in every case.
For example.
`[label1]` and `[label2]` can be applied together too.

How about grouping by source file?
Or we can do grouping by every combination of the labels. Yeah.. Okay. Thats actually might works and useful.

**Comment by matepek** [comment]
Hey. Good new: update to version 2.9
https://github.com/matepek/vscode-catch2-test-adapter/blob/master/CHANGELOG.md#added

**Comment by t3fi** [comment]
Big thanks matepek! Wasn't expecting anything so soon, awesome. 

btw. You had weird looking example in changelog that doesn't work out of the box. But following gives quite exactly what I was hoping. 

`
    "catch2TestExplorer.executables": [
        {
            "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
            "catch2" : {
                "testGrouping": {
                    "groupBySource" : "[-1:]",
                    "groupByTags": true
                }
            }
        }
    ],
`

**Comment by matepek** [comment]
What does not not work?

**Comment by t3fi** [comment]
More evaluation if I may :) 

groupBySource splitting only worked on Linux for me and Windows gave absolute source paths.

I also happen to have scenario where **/Tests/* repeats in subfolders of different depths. So e.g. "[-3:]" starts to look weird as it goes partly below the project root. "[:-1]" looks cool as it organizes the top-level from all separate directories with test sources. The minor minus is that you then loose the filenames from the view. Therefore I started to miss a variable to say "[${workingDirectoryDepth}:]" 

Or am I just overlooking some option that is already there ?

**Comment by matepek** [comment]
> groupBySource splitting only worked on Linux for me and Windows gave absolute source paths.

Yeah, fixed but not tested.

Let's say you have this directory structure: `/a/b/c/d/workspace/src/test/x.cpp`.
You want `src/test/x.cpp`, right?

You can cut the first 5 part with `[5:]`

It's work like [slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice).
But also supports minus values too if you know the length from the other direction.

It uses absPath but I think I will modify it to relative path to workspace

**Comment by t3fi** [comment]
Yes, that was my intent with $workingDirectoryDepth variable that would get substituted to `[5:]` in your example

**Comment by matepek** [comment]
I'm trying to not to introduce a new variable for this.

I'm thinking about converting 
`/a/b/c/d/workspace/src/test/x.cpp` -> `workspace/src/test/x.cpp` and then applying the indexing.

**Comment by t3fi** [comment]
Yes, that was my intent with $workingDirectoryDepth variable that would get substituted to `[5:]` in your example. Its just to support different workspace locations without manual update. Maybe relative path is good compromize for all.

So, with structure :
```
/a/b/c/d/workspace/tests/x.cpp
/a/b/c/d/workspace/external/some-library/tests/x.cpp
```
with `[5:-1]` and `groupByTags: true` gives :
```
tests/
   [tag1]
   [tag2]
external/some-library/tests/
   [tag3]
```
This gives minimalistic view that I like.

**Comment by matepek** [comment]
I think I will cut out what is before the workspace and then `[1:-1]`will do it.

**Comment by matepek** [comment]
An advanced grouping version is on the way. It give a huge flexibility. (It's an overkill, but I cannot play outside 🦠🙃) version 2.9.2

It will break you settings (probably).
If you share what you have now I translate it for you.

**Comment by t3fi** [comment]
Thanks,

I took your new example and modified the sourceRelPath. This works for me.
```
            "catch2" : {
                "testGrouping": {
                    "groupByExecutable": {
                        "label": "${filename}",
                        "description": "${relDirpath}/",
                        "groupBySource": {
                          "label": "${sourceRelPath[:-1]}",
                          "groupByTags": {
                            "tags": [],
                            "label": "[${tag}]",                            
                          }
                        }
                    }
                }
            }
```
As I previosly wrote, one problem with this view is that it's missing the source-filenames. 

This is one option I found to work, but its a slight overkill.
```
            "catch2" : {
                "testGrouping": {
                    "groupByExecutable": {
                        "label": "${filename}",
                        "description": "${relDirpath}/",
                        "groupBySource": {
                          "label": "${sourceRelPath[:-1]}",
                          "groupByTags": {
                            "tags": [],
                            "label": "[${tag}]",
                            "groupBySource" : {
                                "label": "${sourceRelPath[-1:]}",
                            }
                          }
                        }
                    }
                }
            }
```

I would like to say `"description" : "(${sourceRelPath[-1:]})"` within groupByTags or alternatively  just `label" = "[$tag] ($sourceRelPath[-1:])` within groupBySource. But I realize this would require more complex zip-iterator over both sources and tags. So, don't let me interfere with your work too much, the feature is already solving my original problem very well, thank you!

**Comment by matepek** [comment]
"label" and "description" of "groupByExecutable" are optional. It will resolve to that automatically.
(unless you filled "name" or "description" next to "pattern").

> As I previosly wrote, one problem with this view is that it's missing the source-filenames.

I don't get it.. Source file name is `${sourceRelPath[-1:]}`

**Comment by t3fi** [comment]
Ok.

>> As I previosly wrote, one problem with this view is that it's missing the source-filenames.

> I don't get it.. Source file name is ${sourceRelPath[-1:]}

Yes it is within groupBySources, but such a variable is not available when grouping by tags nested to it. 
```
            "catch2" : {
                "testGrouping": {
                    "groupByExecutable": {
                        "label": "${filename}",
                        "description": "${relDirpath}/",
                        "groupBySource": {
                          "label": "${sourceRelPath[:-1]}",
                          "groupByTags": {
                            "tags": [],
                            "label": "[${tag}]",
                            "description": "[${sourceRelPath[-1:]}]"   // <<< HERE  $sourceFilename can be more than just one file                                           }
                        }
                    }
                }
            }
```
This felt obviously wrong and asking for grouping by zip-iterated labels `"[$tag] ($sourceRelPath[-1:])"`

**Comment by matepek** [comment]
Yeah it is conceptually a bit different. But I think I made some generalization which might solved it.

In 2.9.3 (which will be released as fast as CI/CD works) it might works.

Changes:
- `${tag}` -> `${tags}`
- `${tags}` can be used in any level
- any file/tag/source related variables can be used anywhere

Note: groups with same label but different description are not equal.

Try this in the new version:
```
"catch2" : {
    "testGrouping": {
        "groupByExecutable": {
            "groupByTags": {
                // "tagFormat": "!${tag} "
                "label": "${tags}",
                "description": "${sourceRelPath[-1:]}"
            }
        }
    }
}
```

**Comment by t3fi** [comment]
thanks, I'll be using the following from now on. 
```
                    "groupByExecutable": {
                        "label": "${filename}",
                        "description": "${relDirpath}/",
                        "groupBySource": {
                          "label": "${sourceRelPath[:-1]}",
                          "groupByTags": {
                            "tags": [],
                            "label": "${sourceRelPath[-1:]}",
                            "description": "${tags}"
                          }
                        }
                      }
```
btw, tag made hidden with prefix dot e.g. `"[.tagname]"` expands to `[!hide][.][tagname]` which I find 
a bit annoying, any change you could filter those out ? you have descriptive icons for the same info, right ?

**Comment by matepek** [comment]
Good thought. Added in next version. (10 minutes)

**Comment by matepek** [comment]
hello, attach logs pls
