### ISSUE TITLE
Unknown flag "--reporter" when debugging gtest

### ISSUE THREAD

**Issue by hellishfire** [matepek/vscode-catch2-test-adapter#184]
Starting from ver 2.9.2 of this plugin, debugging gtest test cases will fail due to "unknown command line flag: reporter"

I checked the source code and found the culprit in src/framework/GoogleRunnable.ts
There's a line of code added in getDebugParams() which breaks gtest debugging:
params.push('--reporter', 'console');

I don't know why it's added there. For now, I reverted back to ver 2.9.1

**Comment by matepek** [comment]
Mybad.
Fixing soon.

**Comment by hellishfire** [comment]
Thanks for instant reply
