### ISSUE TITLE
Feature Request: Write test output to a JSON file

### ISSUE THREAD

**Issue by ryanpholt** [matepek/vscode-catch2-test-adapter#205]
Feature Request:

Could the extension have a setting to write the test output to some kind of log (JSON?) file (in addition to the Output pane in VSCode)? I have some tooling which does post processing on the test results. For example, when a test fails, I have a VSCode task that will run a script which automatically updates the test source file with the new expected result.

**Comment by matepek** [comment]
Hello,

I'm not sure that would be that good.

Why don't you customize your [test's main](https://github.com/google/googletest/blob/master/googletest/docs/primer.md#writing-the-main-function) function by redirecting stdout?

That is a more flexible way for you to do anything you want.

Maybe you found [this](https://github.com/matepek/vscode-catch2-test-adapter/tree/master/documents/examples/test_wrapper) helpful.

**Comment by ryanpholt** [comment]
Thanks, I'll take a look.

**Comment by matepek** [comment]
>  I have a VSCode task that will run a script which automatically updates the test source file with the new expected result.

That sounds nasty. :D
Why do you wanna do that. Tests to verify that the functionality isn't changed.
Anyway it not a big work to write such kind of tool if necessary based on [this](https://github.com/hbenl/vscode-example-test-controller)

**Comment by ryanpholt** [comment]
Many of our unit tests are stringified for readability. There can be a lot of churn in the string output, however. So, rather than always manually copy/pasting the new result into the source, I have a script which does it for me (using clang). Obviously, we diff the output vs the expected before running the script to make sure it is still correct :).
