### ISSUE TITLE
Not working with Test explorer live share

### ISSUE THREAD

**Issue by zrno** [matepek/vscode-catch2-test-adapter#209]
I am unable to see or run unit tests as a guest in a live share session. We tried joining the live share session from different pc and even from two VS Code instances on the same PC but the tests are not visible in the guest instance. I am not sure is the problem in the "Test explorer live share" extension or in this extension. When running a test on the host VS Code then the guest VS Code shows these messages reported by "Test explorer live share":
```
[2020-07-03 02:53:11.040] [DEBUG] Received TestRun event for adapter #1: {"testRunId":"6296","type":"started","tests":["60"]}
[2020-07-03 02:53:11.040] [WARN] The TestRun event was sent by an unknown adapter
[2020-07-03 02:53:11.460] [DEBUG] Received TestRun event for adapter #1: {"testRunId":"6296","type":"finished"}
[2020-07-03 02:53:11.460] [WARN] The TestRun event was sent by an unknown adapter
```

**Comment by zrno** [comment]
Scrap that. It seems to start correctly after restarting VSCode completely and starting a new live session. But now another problem, the tests on the guest VS Code instance are taking forever to load and the test explorer is till empty after more than 15 mins. We have a fair amount of tests but not more than about 1000. The loading arrow in the test explorer is still making circles. 
![image](https://user-images.githubusercontent.com/13214299/86427915-95151e80-bd3f-11ea-8f31-0c3dcf299465.png)

**Comment by matepek** [comment]
I would try with a smaller set of tests. (Just one executable with few tests.) Is that working. 
Though I don't think its this extensions issue I will check the logs if you attach.

**Comment by zrno** [comment]
I have tried with only 3 very simple and small tests. Still don't show up in the guest instance of VSCode. Log attached
[liveshare_log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/4875968/liveshare_log.txt)

**Comment by hbenl** [comment]
I see in the Test Explorer Live Share log [here](https://github.com/hbenl/vscode-test-explorer-liveshare/issues/4#issuecomment-653957181) that a `TestLoadStartedEvent` is passed on without a corresponding `TestLoadFinishedEvent`. Could it be due to line 4 (`[DEBUG] reloadTests was skipped due to mtime`) in the log referenced here?

**Comment by matepek** [comment]
I've double checked the code and although I cannot state that I'm sending the finished event I believe I do.

The screenshot about the LiveShare is not in sync with the attached log. Also the attached log is not a full log. It might missing some important lines.

Sorry, but I don't have enough information investigate further. :(

**Comment by matepek** [comment]
My adapter sends the load finished events.
