### ISSUE TITLE
Test parsing fail to handle linebreak in Catch2 output

### ISSUE THREAD

**Issue by copelnug** [matepek/vscode-catch2-test-adapter#21]
**Describe the bug**
By default, Catch2 will split some lines after 80 characters (CATCH_CONFIG_CONSOLE_WIDTH). The problem is that this extension expect the Test Name, Description or Tags to be on one line only. Thus a test having those properties will cause an error like:
  ERR Illegal argument: line must be non-negative : Error: Illegal argument: line must be non-negative

**To Reproduce**
1. Create a TEST_CASE with a list of tags longer than 80 characters.
2. Compile the executable.
3. Add the executable in the list of tests supported by the plugin.
4. The executable won't appear in the list (in fact, the list won't refresh).
5. Display developper console to see error.

**Expected behavior**
The executable and the test should appear in the list.

It should work in all the following case:
1. Test name longer than 80
2. File name longer than 80
3. Description longer than 80
4. Total length of tags longer than 80
5. A tag longer than 80

**Desktop (please complete the following information):**
 - Extension Version: 2.0.1
 - VS Code Version: 1.29.1
 - Catch v2.0.1

**Additional context**
I've encountered the problem with a list of tag longer than 80 and I've found a solution for those in C2TestSuiteInfo.ts (by changing the "if" for the tags to a while and appending to the tags array).

But, I don't see how it would be possible to handle case 1 and 4 specifically. Those give the following output:
__A very long test name that should be longer than 80 characters to cause a
____line split
____PATH_TO_FILE.cpp:LINE
____(NO DESCRIPTION)
__Long tags
____PATH_TO_FILE.cpp:LINE
____(NO DESCRIPTION)
______[A_very_long_test_name_that_should_be_longer_than_80_characters_to_cause-
------_a_line_split]

I think it would be possible to support the long tags (it seems the tags have 6 spaces) but I don't see any way to differentiate between the title continuing and the path to the file.

**Suggestion**
Request a parameter to Catch2 allowing to disable the linebreaks. This would allow to keep the current parsing by simply giving that option.

**Comment by matepek** [comment]
Hello,

I opened an [issue](https://github.com/catchorg/Catch2/issues/1447) for Catch2.
Let's see what they react.
