### ISSUE TITLE
Not a supported test executable with google-test

### ISSUE THREAD

**Issue by thecalicojack** [matepek/vscode-catch2-test-adapter#210]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.

**Describe the bug**

TestMate writes [Error: Not a supported test executable:] but it is a valid google-test excecutable

- Extension Version: 3.2.8
- VS Code Version: 1.43.2
- Catch2 / Google Test / DOCTest Version: Google Test Git Hash: e588eb1f
- OS Type and Version: local Win7, remote Debian 4.9
- Using remote-ssh/docker/wsl?: remote-ssh

**Log** (optional but recommended)
TestMate outout:
[TestMate.log](https://github.com/matepek/vscode-catch2-test-adapter/files/4869610/TestMate.log)

Google Test excecutable output:
[gtest_output.log](https://github.com/matepek/vscode-catch2-test-adapter/files/4869617/gtest_output.log)

**Comment by matepek** [comment]
what is the output if you call with `--help` argument?

**Comment by thecalicojack** [comment]
output of gtest --help:
[gtest_help_log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/4869804/gtest_help_log.txt)

**Comment by matepek** [comment]
It should be fine.
Try to setting up cwd.

https://github.com/matepek/vscode-catch2-test-adapter/issues/201

**Comment by thecalicojack** [comment]
It works now, it seems that setting cwd to ${absDirpath} didn't work.
Setting the path hard-coded worked.
