### ISSUE TITLE
gtest test list cache not updated when using test wrapper scripts

### ISSUE THREAD

**Issue by Trass3r** [matepek/vscode-catch2-test-adapter#211]
The cache is probably based on file modification times and of course if these wrapper scripts are only created once it won't get updated, leading to CodeLens on the wrong lines over time.
Any ideas for how to fix this in a non-invasive way (can't change the build system)?

**Comment by matepek** [comment]
Let's clarify what is the issue here. Is it about that: after you recompile the binary the CodeLens isn't updated?

**Comment by Trass3r** [comment]
Yes if you add lines to the test code for example.

**Comment by matepek** [comment]
I see. Do you use vscode task to trigger the compilation?
If yes or you willing to use I might have a solution for you.

**Comment by Trass3r** [comment]
Yes that's the only solution I can think of too. I'd have to use `dependsOn` as there's no opposite property.

**Comment by matepek** [comment]
Yeah, dependsOn another task which `touch` the wrapper.

**Comment by Trass3r** [comment]
But only if the test exe has changed. Using `date -r` and some magic.

**Comment by matepek** [comment]
Uh, yeah. 
Unfortunate you have no control over the build system.

**Comment by matepek** [comment]
the functionality exists to call any task before the tests are run: [advancedExecutables](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md)'s `runTask`.

This might good to `touch` the wrapper and detect new tests. But probably unnecessary if you use the previously discussed solution.
