### ISSUE TITLE
test-explorer.run-all command is not working in sequence

### ISSUE THREAD

**Issue by janeusz2000** [matepek/vscode-catch2-test-adapter#217]
**ISSUE:** test-explorer.run-all command is not working in sequence tasks 
**VERSION:** I'm using 3.4.0 of TestMate

**  task.json **
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Prepare test",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": "Refresh test",
            "command": "echo ${command:test-explorer.run-all}",
        },
        {
            "label": "Refresh test",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": "Perform test",
            "command": "echo ${command:test-explorer.reload}",
        },
        {
            "label": "Perform test",
            "type": "shell",
            "command": "bazel test ... ",
        },
    ]
}
```

**keybindings.json**
```json 
{
        "key": "ctrl+t",
        "command": "workbench.action.tasks.runTask",
        "args": "Prepare test"
}
```

**Details:** When ctrl + t is pressed , bazel performs test, then test in TestExplorer is refreshing and then nothing happens. When I type command >test-explorer.run-all - all test run sucessfully. After executing ctrl + t I need to click run all, and all tests in test explorer run with sucess. This is what happens when I press ctr + t:
![image](https://user-images.githubusercontent.com/45213495/89478598-ba5ad980-d790-11ea-87b3-a63407ead3e3.png)

After clicking run-all:

![image](https://user-images.githubusercontent.com/45213495/89478338-f5a8d880-d78f-11ea-93e8-d08749e0a4e6.png)
![image](https://user-images.githubusercontent.com/45213495/89478346-fe99aa00-d78f-11ea-8a93-c2e8acc44dea.png)
![image](https://user-images.githubusercontent.com/45213495/89478353-05282180-d790-11ea-92c5-fd229d9c1953.png)

Let me know if you need additional info.

**Comment by matepek** [comment]
Hello,

I see the problem. I can reproduce. I will check exactly whats wrong later but for first guess I would say you refresh and run but refresh finishes after run called. So it might be a concurrency issue.

My question? Why do you need to call reload? Run-all should recognise timestamp changes and reload automatically if the exec has changed. ?

**Comment by matepek** [comment]
Pretty sure thats the case because this works for me:
```json
    "tasks": [
        {
            "label": "Prepare test",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": "Delay",
            "command": "echo ${command:test-explorer.run-all}",
        },
        {
            "label": "Delay",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": "Refresh test",
            "command": "sleep 2",
        },
        {
            "label": "Refresh test",
            "type": "shell",
            "dependsOrder": "sequence",
            "command": "echo ${command:test-explorer.reload}",
        }
    ]
```

**Comment by matepek** [comment]
Reload returns with a future. vscode task doesn't respect that. That can be interpreted as a vscode bug.

**Comment by janeusz2000** [comment]
> Hello,
> 
> I see the problem. I can reproduce. I will check exactly whats wrong later but for first guess I would say you refresh and run but refresh finishes after run called. So it might be a concurrency issue.
> 
> Why do you need to call reload? Run-all should recognise timestamp changes and reload automatically if the exec has changed. ?

I don't know, but in my case I need to reload the test to be exectuted befroe run. WIthout reloading after ctrl +T test is failed and GUI is not updated. 
![image](https://user-images.githubusercontent.com/45213495/89716314-1fd6e200-d9ac-11ea-9aeb-e0b5e1b23c68.png)

**Comment by janeusz2000** [comment]
> > Hello,
> > I see the problem. I can reproduce. I will check exactly whats wrong later but for first guess I would say you refresh and run but refresh finishes after run called. So it might be a concurrency issue.
> > Why do you need to call reload? Run-all should recognise timestamp changes and reload automatically if the exec has changed. ?
> 
> I don't know, but in my case I need to reload the test to be exectuted befroe run. WIthout reloading after ctrl +T test is failed and GUI is not updated.
> 
> {
> "version": "2.0.0",
> "tasks": [
> {
> "label": "Prepare test",
> "type": "shell",
> "dependsOrder": "sequence",
> "dependsOn": "Refresh test",
> "command": "echo ${command:test-explorer.run-all}",
> },
> {
> "label": "Refresh test",
> "type": "shell",
> "dependsOrder": "sequence",
> "dependsOn": "Perform test",
> "command": "sleep 2",
> },
> {
> "label": "Perform test",
> "type": "shell",
> "command": "bazel test ... ",
> },
> ]
> }
> 
> ![image](https://user-images.githubusercontent.com/45213495/89716314-1fd6e200-d9ac-11ea-9aeb-e0b5e1b23c68.png)



> Reload returns with a future. vscode task doesn't respect that. That can be interpreted as a vscode bug.

ok. Thank you very much ;)

**Comment by matepek** [comment]
I take the "vscode" bug part back. It's a bit more complicated.

Anyhow, when you recompile you executable the file system watcher should notify the extension that the tests should be reloaded. I don't understand why you need this special handling.

Try the following:
- run bazel test
- reload the tests
- run the tests
- add a new test case
- build (or run bazel test whatever it does)

Do you see the new test case?

**Comment by janeusz2000** [comment]
> I take the "vscode" bug part back. It's a bit more complicated.
> 
> Anyhow, when you recompile you executable the file system watcher should notify the extension that the tests should be reloaded. I don't understand why you need this special handling.
> 
> Try the following:
> 
> * run bazel test
> * reload the tests
> * run the tests
> * add a new test case
> * build (or run bazel test whatever it does)
> 
> Do you see the new test case?

unfortunatly I dont see new test case. I need to refresh and run them all again. Its not a big deal... I can live without GUI updating itself 👍

**Comment by matepek** [comment]
Is the output directory part of the workspace (directory)?
