### ISSUE TITLE
Show test output while running cases

### ISSUE THREAD

**Issue by lostfalter** [matepek/vscode-catch2-test-adapter#218]
**Is your feature request related to a problem? Please describe.**
I have some test cases which could run for a long time and I would like to see their output while running.
Currently, test mate could only show test output after running/stopping cases.
And I couldn't find a switch in test mate/test explorer to enable immediate outputting.

**Describe the solution you'd like**
Add a switch in settings to enable immediate log output.

**Comment by matepek** [comment]
Which framework do you use?

**Comment by lostfalter** [comment]
I use google test.

**Comment by matepek** [comment]
It wont happen in the near future but the need is reported.
Thanks again. I'm closing this now.
