### ISSUE TITLE
support resolving ${command:...}

### ISSUE THREAD

**Issue by Trass3r** [matepek/vscode-catch2-test-adapter#219]
I tried the `launch.json` [feature](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md) but it does not resolve command substitution like:
```json
"setupCommands": [
				{ "text": "set exec-wrapper ${command:cmake.buildDirectory}/...." },
```
`${workspaceFolder}` works. I think this is also true for other places like the settings.

**Comment by matepek** [comment]
added in ver > v3.5.3
