### ISSUE TITLE
Difficulty getting tests to appear

### ISSUE THREAD

**Issue by joncard1** [matepek/vscode-catch2-test-adapter#223]
Please tell me if this is the wrong place to ask the question. I'm not sure where else to ask it. My project is complicated, so perhaps I'm asking the app to do something it can't do, outside of your control.

I have a project that is running BDD tests through multiple languages to test whether the back-end changes are compatible with all of the front-end APIs we offer. For various reasons, I'm also migrating to VS Code for the first time as part of this from Eclipse. I have set up a multi-root workspace, one for each of the languages through which I am making calls. Two of these languages are Node.js and C++. To generate test reports, I am running the Node.js tests through Mocha and the C++ tests through Catch2. I thought to use Test Mate to aggregate all of the tests in one place. The Node.js tests are showing up in the Test Explorer, but the C++ tests are not. I finally got a binary to build and the debugger to run, but the tests are not showing up. I changed the value testMate.cpp.test.executables to cplusplus/build/testxxxnnncpp, both with and without the leading "cplusplus" folder, and I changed this in both the folder settings containing the C++ tests and in the workspace settings, just in case that mattered. It may or may not be relevant that the DYLD_LIBRARY_PATH environment variable needs to be set to for the debugger and linker to work, and I saw no place for Test Explorer UI or C++ Test Mate to set a library path and don't know if that's related.

The executable is (from the multi-root workspace) at cplusplus/build/testxxxnnncpp

My source file, cplusplus/src/xxxnnncpp.cpp, looks like:

#define CATCH_CONFIG_MAIN
#include "myhfile.h"
#include "catch.hpp"

SCENARIO( "My connect", "[connect]" ) {
     ...
    REQUIRE( rtn == MY_SUCCESS );
    GIVEN( "A connection" ) {
        ...
      	WHEN("performing a Get of a $list($double())") {
	    THEN("it succeeds.") {
                ...
                REQUIRE(...)
                ...
                REQUIRE(...)
                ...
                REQUIRE(...)
            }
        }
        ...
    }
}

I didn't know if maybe the pattern-matching over the file doesn't recognize SCENARIO as a test?
I didn't know if there's a C++ tool required to make inspection of the executable possible?
I didn't know if more than one Test Explorer UI extension is capable of running in one workspace at a time?

I am on Mac using clang++.
I do not see any output under "Output -> Test Explorer".
I have activated "Discovery: Strict Pattern" and do not see any output anywhere, though I don't know where it should appear.

Thank you.

**Comment by matepek** [comment]
Hello,
Text Explorer's github page is more suitable but I might can give you some answers.

> I didn't know if maybe the pattern-matching over the file doesn't recognize SCENARIO as a test?

`cplusplus/build/testxxxnnncpp` wont be recognised.
You can customise the pattern-matching. See the README.md for details. Also you can see the log output. For that check [SUPPORT.md](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md).
If you need to set `DYLD_LIBRARY_PATH` check [test.advancedExecutables](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md).

> I didn't know if there's a C++ tool required to make inspection of the executable possible?

No further tool or extension is required for this extension to work.

> I didn't know if more than one Test Explorer UI extension is capable of running in one workspace at a time?

Yes it is.

Happy testing,
