### ISSUE TITLE
Doctest test cases with a comma in the name are skipped

### ISSUE THREAD

**Issue by wilhem-meignan** [matepek/vscode-catch2-test-adapter#224]
**Checklist**

- [X] The issue is about this extension and NOT about a fork.
- [X] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

Test cases containing a comma in the name are skipped.

**To Reproduce**

Use those test cases:

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("example")
{
    CHECK(true);
}

TEST_CASE("example,")
{
    CHECK(true);
}

Open the "Test" view from the Menu Bar. Click on the play icon at the top to run all tests.

Expected: all tests are run.
Observed: the second test with a comma in the name is skipped.

- Extension Version: 3.4.1
- VS Code Version: 1.49.2
- Catch2 / Google Test / DOCTest Version: 2.3.7 (also happens with 2.4.0)
- OS Type and Version: Windows Locally / Linux Remotely
- Using remote-ssh/docker/wsl?: Remote SSH

**Log** (optional but recommended)

**Comment by matepek** [comment]
Hello,

It seems to me doctest doesn't support escaping `,` which is a [special character](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md)

I will release a workaround but its not bulletproof. If you really need this feature request it from doctest developer at first.

Thanks for the report though.

**Comment by wilhem-meignan** [comment]
Hi Mate,

Thanks for the quick feedback. When running the test binary from the command line I get:

`[doctest] test cases:      2 |      2 passed |      0 failed |      0 skipped`

Both tests are run and none are skipped. So I though this must be an issue specific to the VS Code Extension.

**Comment by matepek** [comment]
Yeah, I see that. For parallelization the extension directly calls the test by name and since the `,` is the separator it has to be escaped. I released a quick fix but that unable to make a difference between `exmaple,` and `exampleX`. So if you run the first it will run both.

**Comment by wilhem-meignan** [comment]
Wow, that was fast! Thanks for the update!
