### ISSUE TITLE
Test discovery fails with very large number of test cases

### ISSUE THREAD

**Issue by hkaimio** [matepek/vscode-catch2-test-adapter#225]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

I have a GTest executable with very large number (~150000) tests (actually most of them are different parameter combinations for a single parameterized test). Test explorer just shows the rotating "reload tests" arrow but nothing happens. If I build the test executable without this particular test, it works just find.

**To Reproduce**

Create a test exectauble with a test with 150000 parameterized variants
Try to use it in VScode

**Desktop**

- Extension Version: 3.4.2
- VS Code Version: 1.50 insider
- Catch2 / Google Test / DOCTest Version: Googletest 1.7
- OS Type and Version: Ubuntu 20.04
- Using remote-ssh/docker/wsl?: no

**Log** (optional but recommended)

The log file ends with this line (I can provide full log via email if needed)
[2020-10-07 13:52:57.292] [INFO] Couldn't parse output file. Possibly it is an older version of Google Test framework. It is trying to parse the output

**Comment by matepek** [comment]
Hello,

Please fill the `Catch2 / Google Test / DOCTest Version:` information.

I need more information..

Please run you executable with `--gtest_list_tests --gtest_output=xml:tests.xml > stdout.txt 2>stderr.txt` and send me the generated 2 or 3 files.

**Comment by hkaimio** [comment]
we are using gtest 1.7.
I sent the stdout.txt  tou you via email (stderr.txt was empty and tests.xml was not produced)

**Comment by matepek** [comment]
I haven't received any emails. 🤷‍♂️
Try sending it on [gitter](https://gitter.im/CppTestMate/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) as PM.

**Comment by matepek** [comment]
Hello,

I test it. It actually works just takes a lot of time to parse it.

**Comment by matepek** [comment]
Hey,
Any news on this? I did some small optimisation. I would like to hear your feedback.
