### ISSUE TITLE
Add support for google benchmark?

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#226]
**Is your feature request related to a problem? Please describe.**
We use google test and also google benchmark. Its often true that a bug happens in either tests or benchmarks. It would be very good and helpful if developers could execute tests and benchmarks from the same integration.

**Describe the solution you'd like**
Support running executables created with google benchmark. Currently it seems they are not detected, at least I can not see them when I add them to the pattern.

**Describe alternatives you've considered**
Currently I can not find any extension that supports google benchmark.

**Comment by emmenlau** [comment]
Dear @matepek can I ask why this was closed? Is it not interesting?

I think adding google benchmark may be relatively little effort and would add a whole new domain to your project.

**Comment by matepek** [comment]
Hey, It's done. I added.

**Comment by emmenlau** [comment]
@matepek Really??? This is so cool!!! I can't wait to test!

**Comment by emmenlau** [comment]
It works so perfect, thanks a lot! Great work!!!
