### ISSUE TITLE
How to see stderr of a test executable?

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#228]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

We are overall very happy with this extension, thanks a lot for the great work!

There is one problem that is plaguing us: Many tests for us write to `stderr` in case of problems, not `stdout`. This output is not showing in the `OUTPUT` tab of VSCode for us. Is there an option to enable capturing stderr, or this is a bug?

We do see the output coming from `stdout`, and when changing a message to print to stdout instead of `stderr` everything works. But especially the important messages are on `stderr`, so this is very unfortunate.

**To Reproduce**

Example:
    1. Implement a test that prints to stderr, like `std::cerr << "Hello world" << std::endl;`
    2. Run the test from this extension
    3. Click on the test in this extension, to see the `OUTPUT` tab
    4. There are all the "standard" messages from `stdout`, like `[ RUN      ]` and `[  FAILED  ]` from GTest. But the message from stderr is not printed.

**Desktop**

- Extension Version: 3.4.2
- VS Code Version: 1.50.0
- Catch2 / Google Test / DOCTest Version: Google Test v1.10.0
- OS Type and Version: Linux Ubuntu 20.04
- Using remote-ssh/docker/wsl?: No

**Comment by matepek** [comment]
Hey,
stderr is handled but it arrives too late. Need a bit bigger refactoring (if it even possible) to circumvent the issue.

**Comment by emmenlau** [comment]
Thanks, thats very interesting! Usually stderr is faster because its not buffered so heavily, but I can see that for an extension it might be different...

**Comment by matepek** [comment]
I subscribe for [stderr](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/framework/GoogleRunnable.ts#L373) and when I debug I can see the error arriving but the "[ FAILED ]" line has already arrived from stdout and processed so I cannot associate like this. Have to google more about NodeJS.

**Comment by matepek** [comment]
It's nodejs stuff. Wont happen soon. :/

**Comment by matepek** [comment]
Workaround from version > 3.6.0:
```
"executionWrapper": {
  "path": "/bin/sh",
  "args": [ "-c", "${cmd} ${argsStr} 2>&1" ]
}
```
