### ISSUE TITLE
debug.configTemplate ignores advancedExecutables.gtest.prependTestRunningArgs

### ISSUE THREAD

**Issue by allight** [matepek/vscode-catch2-test-adapter#229]
**Describe the bug**

When using debug.configTemplate the arguments passed down do not include any of the configured arguments from advancedExecutables. This can cause debugged tests to run differently than expected.

For example most of the AOSP gtests will use a custom runner that will try to run multiple tests concurrently. This breaks the debugger since the test is actually run in a whole different process. [See here](https://cs.android.com/android/platform/superproject/+/master:system/testing/gtest_extras/IsolateMain.cpp?q=IsolateMain&ss=android%2Fplatform%2Fsuperproject) and [here](https://cs.android.com/android/platform/superproject/+/master:art/test/common/gtest_main.cc;l=40?q=gtest_main&ss=android%2Fplatform%2Fsuperproject).

**To Reproduce**

1. Use advancedExecutables to prepend an argument

1. Debug

1. Look for the argument

**Screenshots** (optional)

**Desktop**

- Extension Version: v3.4.2
- VS Code Version: 1.15.0
- Catch2 / Google Test / DOCTest Version:
- OS Type and Version: linux Debian 5.7.17
- Using remote-ssh/docker/wsl?: remote-ssh

**Log** (optional but recommended)

**Comment by matepek** [comment]
Thanks,

Fixed in next release (3.4.3)
