### ISSUE TITLE
Test Adapter cannot find executable on Windows

### ISSUE THREAD

**Issue by benoxoft** [matepek/vscode-catch2-test-adapter#23]
**Describe the bug**
When clicking on the "play" button to run the test, it fail silently with the following error in the chrome console:
```
  ERR spawn c:\Users\Benoit\github\Catch2Test\build\tests\catch2_test.exe ENOENT: Error: spawn c:\Users\Benoit\github\Catch2Test\build\tests\catch2_test.exe ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

**To Reproduce**

I created a small test project here: https://github.com/benoxoft/Catch2Test

1. Clone the project
2. Compile it with cmake (I use CMakeTools in VSCode with the VS2017 compiler and a recent version of cmake. I also installed catch2 with cmake)
3. Open the Developer Tools to see the console
4. Click Play to run the test executable in the Test Explorer UI
5. Notice the error I posted above in the console
6. Copy and paste the full path of the executable in a cmd and notice that the executable exists.

**Expected behavior**
Executable should be found and tests are run

**Screenshots**
Here is a screenshot showing VS Code. I compiled the executable with cmake. We can see the error in the chrome console. If I copy and paste the executable in the terminal below, we can see that the executable exists.

![image](https://user-images.githubusercontent.com/64457/48734573-c943d600-ec13-11e8-9b4c-eb17ee551cc6.png)

**Desktop (please complete the following information):**

- Extension Version 2.0.2
- VS Code Version 1.29.1
- Catch2 Version latest from master
- OS Type and Version Windows 10

**Additional context**

**Comment by benoxoft** [comment]
If I put an empty string as the cwd in settings.json it works.

```
    "catch2TestExplorer.executables": [
        {
            "name": "${relPath} (${relDirpath}/)",
            "path": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
            "cwd": "",
            "env": {
                "C2TESTEXECUTABLEPATH": "${absPath}"
            }
        }
    ]
```

**Comment by matepek** [comment]
Weird.
Try something for me pls.
Set `"catch2TestExplorer.logfile": "log.txt"` in settings and try to reproduce the bug then send the log over.

**Comment by benoxoft** [comment]
[log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/2597587/log.txt)
@matepek

**Comment by matepek** [comment]
@benoxoft got it. there is no variable: `${absDirname}`. It is a bug in package json.
Use `${absDirpath}`. It will work. Thanks for the issue. I'm gonna fix in in half an hour.

**Comment by matepek** [comment]
fixed in v.2.0.3
