### ISSUE TITLE
Add setting that enables test source file path mapping

### ISSUE THREAD

**Issue by eruanno123** [matepek/vscode-catch2-test-adapter#230]
**Is your feature request related to a problem? Please describe.**
I am building a Catch2 test suite under docker command invoked by a Run Build Task (tasks defined in `tasks.json`). Building under docker may have a consequence that absolute paths used by Catch2 (it uses `__FILE__` to annotate the test suites) do not match the project file paths. During test discovery these absolute paths seem to be used as a target path for a "Show source" command. Due to that I am unable to move directly to the source code/line where test is defined, because absolute path does not exist in the host system.

**Describe the solution you'd like**
Some way to map the source path to the destination path in a similar way it is done in GDB configuration (`launch.json` file). Example:

    "sourceFileMap": {
        "/usr/src/myproj": "${workspaceFolder}"
    },

**Describe alternatives you've considered**
Except obvious switching VSCode to Docker-Remote I was testing a simple wrapper script which did not work out. Let's assume I am building `unit-tests` executable file. I am creating `unit-tests-wrapper` with following content:

    #!/bin/sh
    ./tdm-unit-testing $@ | sed s+/usr/src/myproj+.+g

I also tested:

    #!/bin/bash
    ./tdm-unit-testing $@ | sed s+/usr/src/myproj+.+g
    exit ${PIPESTATUS[0]}

The TestMate is configured to recognize this wrapper file by setting proper search pattern. This _kind of_ works, i.e. the tests are discovered, and "Show source" command redirects to the correct source file. However this does not allow to run the test (no reaction on "play" button, no diagnostic logs in Output window).

I was also creating a symbolic link in the host system redirecting the container's path. This also works however VScode seems to think the referenced file does not belong to the project folder (which makes sense to me).

**Additional context**
None.

**Comment by matepek** [comment]
v3.5.1
