### ISSUE TITLE
Case-insensitive grouping for groupByRegex

### ISSUE THREAD

**Issue by crotaphytus** [matepek/vscode-catch2-test-adapter#232]
**Is your feature request related to a problem? Please describe.**
Currently, grouping for groupByRegex is case sensitive. Example: If I write a regex that matches on "test", "Test", and "TEST", this will result in three different groups. I would like to have the option to merge them all into the same group.

**Describe the solution you'd like**
Provide an option whether the regex should be interpreted case sensitive or not.

**Describe alternatives you've considered**
Possibility to denote that ${match} should be interpreted case-insensitive when creating the label.

**Additional context**
None

**Comment by matepek** [comment]
Why can't you just use label anyway?
```
"gtest": {
        "testGrouping": {
          "groupByRegex": {
            "regexes": ["Param", "Cas[0-9]"],
            "label": "x",
            "groupByTags": {
              "label": "${tags}",
              "tagFormat": "${tag}"
            },
          }
        }
      }
```

Everything will go under `x`.
(Okay, maybe label wasn't documented but actually it should work)

**Comment by crotaphytus** [comment]
It works, but only if we have just one regex. Consider something like this:

```
"gtest": {
        "testGrouping": {
          "groupByRegex": {
            "regexes": ["[Tt]est", "[Ff]oo"],
            "label": "???",
            "groupUngroupedTo": "other",
            "groupByTags": {
              "label": "${tags}",
              "tagFormat": "${tag}"
            },
          }
        }
      }
```

Where I would like to have SomeTest and Sometest grouped into "test", while Foo1 and foo2 should go under "foo". However, I can set only one label. 

I also couldn't resolve this with nesting, because then, the "groupUngroupedTo" will trigger too much. Do you see a solution how to do this with the current grouping options?

**Comment by matepek** [comment]
Okay I see your problem.

Btw regex can contain one `(...)` grouping/parenthesis.

v3.5.2

**Comment by crotaphytus** [comment]
Thanks! 

Minor comment: `"label": "Foo ${match}"` is doing what you would expect, `"label": "Foo ${match_upperfirst}"` is not replacing the placeholder for me (same for lowercased). I personally don't care, but maybe this is something to consider some time?

**Comment by matepek** [comment]
oh, right, thanks. fixed. The variable resolution/substitution is ready for a refactoring. :)

Thanks for the coffee. You were the first one.
Obviously I'm not doing this for the money but the appreciation is appreciated. ^^
