### ISSUE TITLE
Can not get a path pattern with multiple curly braces to work

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#233]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

I'm trying to load tests and benchmarks from different directories, because one is for `Debug` and one is for `Release` builds. My globbing pattern is `"pattern": "${os_env:BDASOFTTEMP}/{Debug,Release}/BDAImageAnalysis/*{Test,Benchmark}*",`. But that does not work, the adapter will not find _any_ tests or benchmarks. When I remove the first set of curly braces `{Debug,Release}` and replace it with only `Debug` or `Release`, everything works, but it finds only either the tests or the benchmarks (depending which folder I set). Is it possible that a pattern can not have more than one set of curly braces pattern? Is there a known workaround or a way to add both folders?

**To Reproduce**

Set the `settings.json` to
```
{
    "testMate.cpp.debug.breakOnFailure": false,
    "testMate.cpp.test.advancedExecutables": [
        {
            "name": "${filename}",
            "pattern": "${os_env:BDASOFTTEMP}/Debug/BDAImageAnalysis/*{test,Test,TEST}*",
        }
    ]
}
```

**Desktop**

- Extension Version: 3.5.0
- VS Code Version: 1.50.0
- Catch2 / Google Test / DOCTest Version: Google Test v1.10.0
- OS Type and Version: Linux Ubuntu 20.04
- Using remote-ssh/docker/wsl?: No

**Comment by matepek** [comment]
You didn't attached the full log so I'm just guessing but it might be a vscode limitation. I'm using `vscode.workspace.createFileSystemWatcher`.

For workaround you can try this:
```
{
    "testMate.cpp.debug.breakOnFailure": false,
    "testMate.cpp.test.advancedExecutables": [
        {
            "name": "${filename}",
            "description": "(Debug)",
            "pattern": "${os_env:BDASOFTTEMP}/Debug/BDAImageAnalysis/*Test*",
        },
        {
            "name": "${filename}",
            "description": "(Release)",
            "pattern": "${os_env:BDASOFTTEMP}/Release/BDAImageAnalysis/*Test*",
        },
        {
            "name": "${filename}",
            "description": "(Debug)",
            "pattern": "${os_env:BDASOFTTEMP}/Debug/BDAImageAnalysis/*Benchmark*",
        },
        {
            "name": "${filename}",
            "description": "(Release)",
            "pattern": "${os_env:BDASOFTTEMP}/Release/BDAImageAnalysis/*Benchmark*",
        }
    ]
}
```

**Comment by matepek** [comment]
I'm closing, let me know if it didn't slove.

**Comment by emmenlau** [comment]
Awesome, thanks again for all the great help!

**Comment by emmenlau** [comment]
It works perfect, thanks!
