### ISSUE TITLE
Show Source appears broken with remote-ssh in recent change

### ISSUE THREAD

**Issue by allight** [matepek/vscode-catch2-test-adapter#234]
**Describe the bug**

Until recently (last 2-3 days)  I could use the 'show source' button next to tests to go to the test definition. This does not work anymore. Pressing the button causes an error box to appear saying 

> Error running command test-explorer.show-source: cannot open vscode-remote://ssh-remote%2Bme/art/compiler/optimizing/execution_subgraph_test.cc. Detail: Unable to read file 'vscode-remote://ssh-remote+me/art/compiler/optimizing/execution_subgraph_test.cc' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+me/art/compiler/optimizing/execution_subgraph_test.cc'). This is likely caused by the extension that contributes test-explorer.show-source.

The test is still able to run without issue.

Assert/expect failure highlighting does not seem to work.

Debugging seems to work.

**To Reproduce**

1. Setup a project using remote-ssh.
2. Add some gtests
3. Try to use the 'show source' to jump to the test source.

**Desktop**
- Extension Version: v3.5.3
- VS Code Version: Version: 1.50.1
- Catch2 / Google Test / DOCTest Version:
- OS Type and Version: Darwin x64 19.6.0 (ssh-ing to Debian 5.7.17 x86_64 GNU/Linux)
- Using remote-ssh/docker/wsl?: vscode-ssh

**Log** (optional but recommended)

[cpptestmate.log](https://github.com/matepek/vscode-catch2-test-adapter/files/5467884/cpptestmate.log)

**Comment by matepek** [comment]
Hello,

What is the correct path for `vscode-remote://ssh-remote+me/art/compiler/optimizing/execution_subgraph_test.cc`?

**Comment by matepek** [comment]
If you restart vscode does the navigation work at first? If yes, I found the issue.

**Comment by allight** [comment]
Even immediately after starting/restarting VSCode navigation still does not work.

The path is `${workspaceDir}/art/compiler/optimizing/execution_subgraph_test.cc`

**Comment by matepek** [comment]
Will be fixed in ver>v3.5.3
