### ISSUE TITLE
Debugging error: 'cppdbg' is not supported

### ISSUE THREAD

**Issue by vladipus** [matepek/vscode-catch2-test-adapter#239]
I've used lldbg which was autodetected (no template used) and worked fine before the yesterday's update. Now when starting it wants to install cppdbg:
![image](https://user-images.githubusercontent.com/468323/101013683-ba6bba00-3575-11eb-8516-78a5705537fe.png)

I've tried and installed the cpptools extension but it still doesn't work, showing only:
![image](https://user-images.githubusercontent.com/468323/101013581-91e3c000-3575-11eb-8820-6189895df527.png)

Great project! Please, fix.

**Comment by matepek** [comment]
Let me know if the latest version haven't fixed it.
