### ISSUE TITLE
[CATCH2] CPPDBG Debug a single test does not trigger breakpoints anymore since 3.6.7

### ISSUE THREAD

**Issue by NovarisOberion** [matepek/vscode-catch2-test-adapter#240]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

I am using microsoft's cpp extension and a launch.json setup for their debugger. Since the version 3.6.8 the "debug this test" option does no longer work. With 3.6.7 I am able to start a single test section and constrain the debugger to only this test, With 3.6.8 onwards this does no longer work, the debugger starts but it does not enter the programm, it simply quits again with signal 0.

**To Reproduce**

- Create a CPP project
- use the following launch.json
```
        {
            "name": "GDB Debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}\\build\\bin\\debug\\test.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}\\build\\bin\\debug",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "MAKE debug"
        },
```
- implement a test, like this one:

#include <memory>

#include "catch.hpp"

TEST_CASE("name of the test case group")
{
    std::unique_ptr<int> pData = std::make_unique<int>();
    *pData                     = 1;

    SECTION("name of a single test")
    {
        *pData = 2;
        CHECK(*pData == 2);
    }

    pData.release();
}

- place a breakpoint at the pointer assignment
- start the test, it should pass
- click the "debug" icon next to the TEST_CASE name in the test explorer
- the breakpoint is NOT hit, the programm simply closes

**Screenshots** (optional)

**Desktop**

- Extension Version: 3.6.11
- VS Code Version: 1.52.0insider
- Catch2 / Google Test / DOCTest Version: 2.13.3
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

With 3.6.7 the debugger works and the breakpoint is hit

- Last extension version in which the feature were working: 3.6.7

**Log** (optional but recommended)

**Comment by NovarisOberion** [comment]
As a side-comment, the latest version works with webfreak's debugger, its just microsoft's implementation that does not work

**Comment by matepek** [comment]
Are you sure your source is in sync with the binary?

**Comment by NovarisOberion** [comment]
Yes, I deleted all binaries and intermediate files and did a clean build

**Comment by NovarisOberion** [comment]
If I start the debugger from the debug terminal so it runs through all tests, it hits the breakpoint

**Comment by matepek** [comment]
Please enable logging, try to debug with the extension and attach the log

**Comment by NovarisOberion** [comment]
[log_3.6.11.log](https://github.com/matepek/vscode-catch2-test-adapter/files/5641780/log_3.6.11.log)
![start_debugger_from_debug_pannel](https://user-images.githubusercontent.com/75470954/101146920-f194a680-361b-11eb-809b-9cf5e10d21f1.png)
![debug_console_output_debug_panel](https://user-images.githubusercontent.com/75470954/101146928-f2c5d380-361b-11eb-9969-a05210c632b3.png)
![debug_console_output_testmate](https://user-images.githubusercontent.com/75470954/101146930-f3f70080-361b-11eb-8308-280e52f73dc2.png)

Here you are :) thanks for taking interest!

**Comment by NovarisOberion** [comment]
Another finding: adding this line to the settings.json the latest version also works again and finds the breakpoint:
"testMate.cpp.debug.configTemplate": {
        "type": "cppdbg",
        "MIMode": "gdb",
        "name": "${label} (${suiteLabel})",
        "program": "${exec}",
        "args": "${args}",
        "cwd": "${cwd}",
        "externalConsole": false,
        "environment": []
    }

**Comment by matepek** [comment]
Yeah, this is the intended fully customizable way of doing it. Everything else is an unexpected journey. Btw:
you want this instead of that:
```
"testMate.cpp.debug.configTemplate": {
  "program": "${exec}",
  "args": "${argsArray}",
  "cwd": "${cwd}",
  "environment": "${envObjArray}",
  "sourceFileMap": "${sourceFileMapObj}"
}
```
