### ISSUE TITLE
Excluded tests get executed when autorun is enabled

### ISSUE THREAD

**Issue by simone-gaiarin** [matepek/vscode-catch2-test-adapter#248]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

The excluded Catch2 tests (tagged with `[.]`) gets executed after a rebuild when autorun is enabled.

**To Reproduce**

1. Create a test and tag it with `[.][tag1]`
2. Create a second test and tag it with `[tag1]`
3. Enable autorun for all the tests
4. Rebuild the project

**Screenshots** (optional)

**Desktop**

- Extension Version: 3.6.17
- VS Code Version: 1.52.0
- Catch2 Version: 2.13.1
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)

**Comment by matepek** [comment]
Well this is a hard nut. I change the behaviour and will work for now.

**Comment by simone-gaiarin** [comment]
That was a really quick fix! Thanks for the great work.
