### ISSUE TITLE
Support ${workspaceFolderBasename} in pattern?

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#249]
**Is your feature request related to a problem? Please describe.**
We have literally hundreds of projects. Keeping the project configuration up-to-date for all projects is very tedious. This is even more true when a configuration has project-specific settings. To avoid project-specific settings for `testMate.cpp.test.advancedExecutables`, we would like to use `${workspaceFolderBasename}` instead of the real project name in `"pattern"`. So here is our preferred setting:
```
"pattern": "${os_env:BDASOFTTEMP_OSPATH}/Debug/${workspaceFolderBasename}/*Test*",
```
This currently does not work for me. From reading https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md#variables I understand that these variables are currently not supported in `pattern`?

**Describe the solution you'd like**
Support `${workspaceFolderBasename}` (and possibly other variables from https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables) in `pattern`.

**Describe alternatives you've considered**
Currently there is no alternative for us. We replace `${workspaceFolderBasename}` with `perl` in every project, which is very cumbersome :-(

**Comment by matepek** [comment]
What other variables?

**Comment by emmenlau** [comment]
Please ignore what I said about other variables. Supporting other variables probably makes not too much sense.

**Comment by matepek** [comment]
Ok, I thought I might miss something.
In the next release (in an hour) you can use `${workspaceFolder[-1]}` for that. (python array indexing)

**Comment by emmenlau** [comment]
Whoa, awesome! Thanks a lot!
