### ISSUE TITLE
Cannot find source file during gtest debug session

### ISSUE THREAD

**Issue by hellishfire** [matepek/vscode-catch2-test-adapter#250]
I'm using vscode-remote to develop c++ codes remotely. I upgraded to the latest version of this extension and found out that source files cannot be found any longer during gtest debug session. When a breakpoint is hit, vscode warns that source file path cannot be opened.

The last working version is 3.6.4, so I suspect this commit breaks the debug feature for me:
https://github.com/matepek/vscode-catch2-test-adapter/commit/df1404a93273917597b7391848f68bccb8ba0732

I'm not sure if it's a bug, or do I need to manually set sourceFileMapObj to some value?

**Comment by matepek** [comment]
What is the value of your `testMate.cpp.debug.configTemplate` ?
Which extension do you use for testing?

**Comment by hellishfire** [comment]
I use ms-vscode.cpptools 1.1.3
testMate.cpp.debug.configTemplate is not set.
Per doc https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md, I once tried to set testMate.cpp.debug.configTemplate to "extensionOnly", but to no avail.
I also tried to set it to:
"testMate.cpp.debug.configTemplate": {
  "type": "cppvsdbg",
  "linux": { "type": "cppdbg", "MIMode": "gdb" },
  "osx": { "type": "cppdbg", "MIMode": "lldb" },
  "windows": { "type": "cppvsdbg" },
  "program": "${exec}",
  "args": "${argsArray}",
  "cwd": "${cwd}",
  "env": "${envObj}",
  "environment": "${envObjArray}",
  "sourceFileMap": "${sourceFileMapObj}",
}

But the problem persists.

**Comment by matepek** [comment]
Try to delete the sourceFileMap line. If still persist I would need the log

**Comment by hellishfire** [comment]
Deleting the sourceFileMap line doesn't help.
I omitted some info from the log, but I suppose this should suffice.
[cpp.log](https://github.com/matepek/vscode-catch2-test-adapter/files/5713643/cpp.log)

**Comment by matepek** [comment]
Please clear your `testMate.cpp.debug.configTemplate` and reproduce it again and attach the log.

**Comment by hellishfire** [comment]
Cleared testMate.cpp.debug.configTemplate
[cpp.log](https://github.com/matepek/vscode-catch2-test-adapter/files/5713681/cpp.log)

**Comment by matepek** [comment]
Not much idea :(

try adding this to debugconfig
```
{
    type: 'cppdbg',
    program: '${exec}',
    args: '${argsArray}',
    stopAtEntry: false,
    cwd: '${cwd}',
    environment: '${envObjArray}',
    externalConsole: false,
    MIMode: 'gdb',
    setupCommands: [
      {
        description: 'Print subclass info',
        text: 'set print object',
        ignoreFailures: false
      },
      {
        description: 'Print subclass info',
        text: 'handle SIGUSR2 noprint nostop',
        ignoreFailures: false
      },
      {
        description: 'Pretty printer init',
        text: "python import sys;sys.path.insert(0, '/home/dev-name/libstdc++-printer/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
        ignoreFailures: false
      },
      {
        description: 'Enable pretty-printing for gdb',
        text: '-enable-pretty-printing',
        ignoreFailures: true
      }
    ],
    target: '${exec}',
    arguments: '${argsStr}',
    env: '${envObj}'
  }
}
```

**Comment by hellishfire** [comment]
After playing around with different config combinations, I solved this failure by adding this config:
    "testMate.cpp.debug.configTemplate": {
        "type": "cppvsdbg",
        "linux": { "type": "cppdbg", "MIMode": "gdb" },
        "osx": { "type": "cppdbg", "MIMode": "lldb" },
        "windows": { "type": "cppvsdbg" },
        "program": "${exec}",
        "args": "${argsArray}",
        "env": "${envObj}",
        "environment": "${envObjArray}",
        **"cwd": "${workspaceFolder}",**
      }

The "cwd": "${workspaceFolder}" part fixed this problem. I don't know why though.
As a remainder, I'm debugging with vscode-remote.

**Comment by matepek** [comment]
happy to hear
