### ISSUE TITLE
start tests/view test results in code lens

### ISSUE THREAD

**Issue by hannamtt** [matepek/vscode-catch2-test-adapter#252]
**Is your feature request related to a problem? Please describe.**
not related to a problem

**Describe the solution you'd like**
The test explorer supports showing buttons and text through codelens, it would be nice to see test results and trigger test events from codelens instead of having to navigate to the test in the test explorer.

**Describe alternatives you've considered**
I cant find any alternatives to for c++ gtest unit test codelens support

**Additional context**
here is an example of how a java test adapter does it
![image](https://user-images.githubusercontent.com/24688453/104784327-e9607880-573c-11eb-9ce2-94a1a1b9369c.png)

**Comment by matepek** [comment]
Well it actually does have. If `testExplorer.codeLens` is enabled and the explorer were able to find the source file then it should be there.

**Comment by hannamtt** [comment]
> Well it actually does have. If `testExplorer.codeLens` is enabled and the explorer were able to find the source file then it should be there.

it doesn't seem to work for me with google test in c++, is there a way to check to see if the source files are being found, or tell it where to look for them?

**Comment by matepek** [comment]
There are ways even source fuel mapping (please check advancedExecutables
config)

Also bear in mind that old version of google test simply doesn’t provide
the file and line number information in which case the code lens doesn’t
work.

For detailed information check the logs.
