### ISSUE TITLE
Google Benchmark results wouldn't be parsed if there is output(in stderr) before/after the execution of the tests.

### ISSUE THREAD

**Issue by gigony** [matepek/vscode-catch2-test-adapter#253]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

Thank you for build this great extension! I enjoy using this extension for Catch2 tests but had a problem with google benchmarks.

I have a Google benchmark test binary that links a shared library that outputs something in the console when it is loaded.

When tests are executed by your extension, it would call the binary with the following arguments (assuming that target benchmark is `test_data/256`):
  `--benchmark_color=false --benchmark_format=json --benchmark_filter=test_data/256`

However, the benchmark binary would output something in terminal (it is a warning message in stderr) so it seems that the extension cannot recognize the output so no UI changes when I click a play button to run the benchmark.

```
FileDriver cannot be open. Falling back to use POSIX file IO APIs.
{
  "context": {
    "date": "2021-01-25 22:23:02",
    "host_name": "GIGONY-DESKTOP",
    "executable": "./build-debug/bin/test_benchmarks",
    "num_cpus": 12,
    "mhz_per_cpu": 3800,
    "cpu_scaling_enabled": false,
    "caches": [
      {
        "type": "Data",
        "level": 1,
        "size": 32768,
        "num_sharing": 2
      },
      {
        "type": "Instruction",
        "level": 1,
        "size": 32768,
        "num_sharing": 2
      },
      {
        "type": "Unified",
        "level": 2,
        "size": 524288,
        "num_sharing": 2
      },
      {
        "type": "Unified",
        "level": 3,
        "size": 16777216,
        "num_sharing": 12
      }
    ],
    "load_avg": [1.21,1.17,1.11],
    "library_build_type": "debug"
  },
  "benchmarks": [
    {
      "name": "test_data/256",
      "run_name": "test_data/256",
      "run_type": "iteration",
      "repetitions": 0,
      "repetition_index": 0,
      "threads": 1,
      "iterations": 315,
      "real_time": 2.1729444443259299e+03,
      "cpu_time": 2.1711490285714276e+03,
      "time_unit": "us"
    }
  ]
}
```

Could you please update the extension to parse JSON from only stdout?

**To Reproduce**

1. Compile a google benchmark code, replacing `BENCHMARK_MAIN();` with the following statements:
```c++
// BENCHMARK_MAIN();
int main(int argc, char** argv)
{
    ::benchmark::Initialize(&argc, argv);
    if (::benchmark::ReportUnrecognizedArguments(argc, argv))
        return 1;

    fprintf(stderr, "hello world\n");
    ::benchmark::RunSpecifiedBenchmarks();
}
```

**Screenshots** (optional)

**Desktop**

- Extension Version: v3.6.19
- VS Code Version:
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.21296
```
- Catch2 / Google Test / DOCTest Version: N/A
- OS Type and Version: VSCode on WSL2
- Using remote-ssh/docker/wsl?: yes (WSL2)

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)
[log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/5871642/log.txt)

**Comment by matepek** [comment]
should be fixed
