### ISSUE TITLE
Ugly (raw) output in Debug console from GTest

### ISSUE THREAD

**Issue by H-G-Hristov** [matepek/vscode-catch2-test-adapter#254]
When debugging the output in Debug console looks like this typically:

          @"Note: Google Test filter = SystemProfilerTest/SystemProfilerTestF.ItemCount/2\r\n"
          @"[==========] Running 1 test from 1 test suite.\r\n"
          @"[----------] Global test environment set-up.\r\n"
          @"[----------] 1 test from SystemProfilerTest/SystemProfilerTestF\r\n"
          @"[ RUN      ] SystemProfilerTest/SystemProfilerTestF.ItemCount/2\r\n"
          @"unknown file: Failure\r\n"
          @"\r\n"
          @"Unexpected mock function call - returning default value.\r\n"
          @"    Function call: SpawnProcess(@0x7ffeefbfe9e0 { \"system_profiler\", \"-xml\", \"SPMemoryDataType\" }, @0x7ffeefbfe978 8-byte object <00-87 93-03 00-00 00-00>)\r\n"
          @"          Returns: 72-byte object <00-00 00-00 00-00 00-00 E8-E8 B7-88 FF-7F 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>\r\n"
          @"Google Mock tried the following 1 expectation, but it didn't match:\r\n"
          @"\r\n"
          @"/Users/ffdf/Projects/GitHub/mfdfd-fdfd/test/data/hard/detail/SystemProfilerTest.cpp:28: EXPECT_CALL(*spawner, SpawnProcess(args, boost::posix_time::seconds(timeoutSeconds)))...\r\n"
          @"  Expected arg #0: is equal to { \"system_profiler\", \"-xml\", \"Undefined DataType\" }\r\n"
          @"           Actual: { \"system_profiler\", \"-xml\", \"SPMemoryDataType\" }\r\n"
          @"         Expected: to be called once\r\n"
          @"           Actual: never called - unsatisfied and active\r\n"

**Comment by matepek** [comment]
That's the debug extension's business

**Comment by H-G-Hristov** [comment]
@matepek Are you sure that the test extension isn't decorating the debug output as I get the following even with std::cerr when code is executed via a test when run on MacOS.

        @"/dev/afsc_type5\r\n"
        @"/dev/auditpipe\r\n"
        @"/dev/auditsessions\r\n"
        @"/dev/autofs\r\n"
        @"/dev/autofs_control\r\n"
        @"/dev/autofs_homedirmounter\r\n"
        @"/dev/autofs_notrigger\r\n"
        @"/dev/autofs_nowait\r\n"
        @"/dev/bpf0\r\n"
        @"/dev/bpf1\r\n"
        @"/dev/bpf2\r\n"
        @"/dev/bpf3\r\n"
        @"/dev/console\r\n"
        @"/dev/cu.Bluetooth-Incoming-Port\r\n"
        @"/dev/disk0\r\n"
        @"/dev/disk0s1\r\n"
        @"/dev/disk0s2\r\n"
        @"/dev/disk1\r\n"
        @"/dev/disk1s1\r\n"
        @"/dev/disk1s2\r\n"
        @"/dev/disk1s3\r\n"
        @"/dev/disk1s4\r\n"
        @"/dev/disk1s5\r\n"
        @"/dev/disk1s6\r\n"
        @"/dev/disk1s6s1\r\n"
        @"/dev/disk1s7\r\n"
        @"/dev/dtrace\r\n"
        @"/dev/dtracehelper\r\n"
        @"/dev/fbt\r\n"
        @"/dev/fd\r\n"
        @"/dev/fsevents\r\n"
        @"/dev/io8log\r\n"
        @"/dev/io8logmt\r\n"
        @"/dev/io8logtemp\r\n"
        @"/dev/klog\r\n"
        @"/dev/lockstat\r\n"
        @"/dev/machtrace\r\n"
        @"/dev/null\r\n"
        @"/dev/oslog\r\n"
        @"/dev/oslog_stream\r\n"
        @"/dev/pf\r\n"
        @"/dev/pfm\r\n"
        @"/dev/profile\r\n"
        @"/dev/ptmx\r\n"
        @"/dev/ptyp0\r\n"
        @"/dev/ptyp1\r\n"
        @"/dev/ptyp2\r\n"
        @"/dev/ptyp3\r\n"
        @"/dev/ptyp4\r\n"
        @"/dev/ptyp5\r\n"
        @"/dev/ptyp6\r\n"
        @"/dev/ptyp7\r\n"
        @"/dev/ptyp8\r\n"
        @"/dev/ptyp9\r\n"
        @"/dev/ptypa\r\n"
        @"/dev/ptypb\r\n"
        @"/dev/ptypc\r\n"
        @"/dev/ptypd\r\n"
        @"/dev/ptype\r\n"
        @"/dev/ptypf\r\n"
        @"/dev/ptyq0\r\n"
        @"/dev/ptyq1\r\n"
        @"/dev/ptyq2\r\n"
        @"/dev/ptyq3\r\n"
        @"/dev/ptyq4\r\n"
        @"/dev/ptyq5\r\n"
        @"/dev/ptyq6\r\n"
        @"/dev/ptyq7\r\n"
        @"/dev/ptyq8\r\n"
        @"/dev/ptyq9\r\n"
        @"/dev/ptyqa\r\n"
        @"/dev/ptyqb\r\n"
        @"/dev/ptyqc\r\n"
        @"/dev/ptyqd\r\n"
        @"/dev/ptyqe\r\n"
        @"/dev/ptyqf\r\n"
        @"/dev/ptyr0\r\n"
        @"/dev/ptyr1\r\n"
        @"/dev/ptyr2\r\n"
        @"/dev/ptyr3\r\n"
        @"/dev/ptyr4\r\n"
        @"/dev/ptyr5\r\n"
        @"/dev/ptyr6\r\n"
        @"/dev/ptyr7\r\n"
        @"/dev/ptyr8\r\n"
        @"/dev/ptyr9\r\n"
        @"/dev/ptyra\r\n"
        @"/dev/ptyrb\r\n"
        @"/dev/ptyrc\r\n"
        @"/dev/ptyrd\r\n"
        @"/dev/ptyre\r\n"
        @"/dev/ptyrf\r\n"
        @"/dev/ptys0\r\n"
        @"/dev/ptys1\r\n"
        @"/dev/ptys2\r\n"
        @"/dev/ptys3\r\n"
        @"/dev/ptys4\r\n"
        @"/dev/ptys5\r\n"
        @"/dev/ptys6\r\n"
        @"/dev/ptys7\r\n"
        @"/dev/ptys8\r\n"
        @"/dev/ptys9\r\n"
        @"/dev/ptysa\r\n"
        @"/dev/ptysb\r\n"
        @"/dev/ptysc\r\n"
        @"/dev/ptysd\r\n"
        @"/dev/ptyse\r\n"
        @"/dev/ptysf\r\n"
        @"/dev/ptyt0\r\n"
        @"/dev/ptyt1\r\n"
        @"/dev/ptyt2\r\n"
        @"/dev/ptyt3\r\n"
        @"/dev/ptyt4\r\n"
        @"/dev/ptyt5\r\n"
        @"/dev/ptyt6\r\n"
        @"/dev/ptyt7\r\n"
        @"/dev/ptyt8\r\n"
        @"/dev/ptyt9\r\n"
        @"/dev/ptyta\r\n"
        @"/dev/ptytb\r\n"
        @"/dev/ptytc\r\n"
        @"/dev/ptytd\r\n"
        @"/dev/ptyte\r\n"
        @"/dev/ptytf\r\n"
        @"/dev/ptyu0\r\n"
        @"/dev/ptyu1\r\n"
        @"/dev/ptyu2\r\n"
        @"/dev/ptyu3\r\n"
        @"/dev/ptyu4\r\n"
        @"/dev/ptyu5\r\n"
        @"/dev/ptyu6\r\n"
        @"/dev/ptyu7\r\n"
        @"/dev/ptyu8\r\n"
        @"/dev/ptyu9\r\n"
        @"/dev/ptyua\r\n"
        @"/dev/ptyub\r\n"
        @"/dev/ptyuc\r\n"
        @"/dev/ptyud\r\n"
        @"/dev/ptyue\r\n"
        @"/dev/ptyuf\r\n"
        @"/dev/ptyv0\r\n"
        @"/dev/ptyv1\r\n"
        @"/dev/ptyv2\r\n"
        @"/dev/ptyv3\r\n"
        @"/dev/ptyv4\r\n"
        @"/dev/ptyv5\r\n"
        @"/dev/ptyv6\r\n"
        @"/dev/ptyv7\r\n"
        @"/dev/ptyv8\r\n"
        @"/dev/ptyv9\r\n"
        @"/dev/ptyva\r\n"
        @"/dev/ptyvb\r\n"
        @"/dev/ptyvc\r\n"
        @"/dev/ptyvd\r\n"
        @"/dev/ptyve\r\n"
        @"/dev/ptyvf\r\n"
        @"/dev/ptyw0\r\n"
        @"/dev/ptyw1\r\n"
        @"/dev/ptyw2\r\n"
        @"/dev/ptyw3\r\n"
        @"/dev/ptyw4\r\n"
        @"/dev/ptyw5\r\n"
        @"/dev/ptyw6\r\n"
        @"/dev/ptyw7\r\n"
        @"/dev/ptyw8\r\n"
        @"/dev/ptyw9\r\n"
        @"/dev/ptywa\r\n"
        @"/dev/ptywb\r\n"
        @"/dev/ptywc\r\n"
        @"/dev/ptywd\r\n"
        @"/dev/ptywe\r\n"
        @"/dev/ptywf\r\n"
        @"/dev/random\r\n"
        @"/dev/rdisk0\r\n"
        @"/dev/rdisk0s1\r\n"
        @"/dev/rdisk0s2\r\n"
        @"/dev/rdisk1\r\n"
        @"/dev/rdisk1s1\r\n"
        @"/dev/rdisk1s2\r\n"
        @"/dev/rdisk1s3\r\n"
        @"/dev/rdisk1s4\r\n"
        @"/dev/rdisk1s5\r\n"
        @"/dev/rdisk1s6\r\n"
        @"/dev/rdisk1s6s1\r\n"
        @"/dev/rdisk1s7\r\n"
        @"/dev/sdt\r\n"
        @"/dev/stderr\r\n"
        @"/dev/stdin\r\n"
        @"/dev/stdout\r\n"
        @"/dev/systrace\r\n"
        @"/dev/tty\r\n"
        @"/dev/tty.Bluetooth-Incoming-Port\r\n"
        @"/dev/ttyp0\r\n"
        @"/dev/ttyp1\r\n"
        @"/dev/ttyp2\r\n"
        @"/dev/ttyp3\r\n"
        @"/dev/ttyp4\r\n"
        @"/dev/ttyp5\r\n"
        @"/dev/ttyp6\r\n"
        @"/dev/ttyp7\r\n"
        @"/dev/ttyp8\r\n"
        @"/dev/ttyp9\r\n"
        @"/dev/ttypa\r\n"
        @"/dev/ttypb\r\n"
        @"/dev/ttypc\r\n"
        @"/dev/ttypd\r\n"
        @"/dev/ttype\r\n"
        @"/dev/ttypf\r\n"
        @"/dev/ttyq0\r\n"
        @"/dev/ttyq1\r\n"
        @"/dev/ttyq2\r\n"
        @"/dev/ttyq3\r\n"
        @"/dev/ttyq4\r\n"
        @"/dev/ttyq5\r\n"
        @"/dev/ttyq6\r\n"
        @"/dev/ttyq7\r\n"
        @"/dev/ttyq8\r\n"
        @"/dev/ttyq9\r\n"
        @"/dev/ttyqa\r\n"
        @"/dev/ttyqb\r\n"
        @"/dev/ttyqc\r\n"
        @"/dev/ttyqd\r\n"
        @"/dev/ttyqe\r\n"
        @"/dev/ttyqf\r\n"
        @"/dev/ttyr0\r\n"
        @"/dev/ttyr1\r\n"
        @"/dev/ttyr2\r\n"
        @"/dev/ttyr3\r\n"
        @"/dev/ttyr4\r\n"
        @"/dev/ttyr5\r\n"
        @"/dev/ttyr6\r\n"
        @"/dev/ttyr7\r\n"
        @"/dev/ttyr8\r\n"
        @"/dev/ttyr9\r\n"
        @"/dev/ttyra\r\n"
        @"/dev/ttyrb\r\n"
        @"/dev/ttyrc\r\n"
        @"/dev/ttyrd\r\n"
        @"/dev/ttyre\r\n"
        @"/dev/ttyrf\r\n"
        @"/dev/ttys0\r\n"
        @"/dev/ttys000\r\n"
        @"/dev/ttys001\r\n"
        @"/dev/ttys002\r\n"
        @"/dev/ttys1\r\n"
        @"/dev/ttys2\r\n"
        @"/dev/ttys3\r\n"
        @"/dev/ttys4\r\n"
        @"/dev/ttys5\r\n"
        @"/dev/ttys6\r\n"
        @"/dev/ttys7\r\n"
        @"/dev/ttys8\r\n"
        @"/dev/ttys9\r\n"
        @"/dev/ttysa\r\n"
        @"/dev/ttysb\r\n"
        @"/dev/ttysc\r\n"
        @"/dev/ttysd\r\n"
        @"/dev/ttyse\r\n"
        @"/dev/ttysf\r\n"
        @"/dev/ttyt0\r\n"
        @"/dev/ttyt1\r\n"
        @"/dev/ttyt2\r\n"
        @"/dev/ttyt3\r\n"
        @"/dev/ttyt4\r\n"
        @"/dev/ttyt5\r\n"
        @"/dev/ttyt6\r\n"
        @"/dev/ttyt7\r\n"
        @"/dev/ttyt8\r\n"
        @"/dev/ttyt9\r\n"
        @"/dev/ttyta\r\n"
        @"/dev/ttytb\r\n"
        @"/dev/ttytc\r\n"
        @"/dev/ttytd\r\n"
        @"/dev/ttyte\r\n"
        @"/dev/ttytf\r\n"
        @"/dev/ttyu0\r\n"
        @"/dev/ttyu1\r\n"
        @"/dev/ttyu2\r\n"
        @"/dev/ttyu3\r\n"
        @"/dev/ttyu4\r\n"
        @"/dev/ttyu5\r\n"
        @"/dev/ttyu6\r\n"
        @"/dev/ttyu7\r\n"
        @"/dev/ttyu8\r\n"
        @"/dev/ttyu9\r\n"
        @"/dev/ttyua\r\n"
        @"/dev/ttyub\r\n"
        @"/dev/ttyuc\r\n"
        @"/dev/ttyud\r\n"
        @"/dev/ttyue\r\n"
        @"/dev/ttyuf\r\n"
        @"/dev/ttyv0\r\n"
        @"/dev/ttyv1\r\n"
        @"/dev/ttyv2\r\n"
        @"/dev/ttyv3\r\n"
        @"/dev/ttyv4\r\n"
        @"/dev/ttyv5\r\n"
        @"/dev/ttyv6\r\n"
        @"/dev/ttyv7\r\n"
        @"/dev/ttyv8\r\n"
        @"/dev/ttyv9\r\n"
        @"/dev/ttyva\r\n"
        @"/dev/ttyvb\r\n"
        @"/dev/ttyvc\r\n"
        @"/dev/ttyvd\r\n"
        @"/dev/ttyve\r\n"
        @"/dev/ttyvf\r\n"
        @"/dev/ttyw0\r\n"
        @"/dev/ttyw1\r\n"
        @"/dev/ttyw2\r\n"
        @"/dev/ttyw3\r\n"
        @"/dev/ttyw4\r\n"
        @"/dev/ttyw5\r\n"
        @"/dev/ttyw6\r\n"
        @"/dev/ttyw7\r\n"
        @"/dev/ttyw8\r\n"
        @"/dev/ttyw9\r\n"
        @"/dev/ttywa\r\n"
        @"/dev/ttywb\r\n"
        @"/dev/ttywc\r\n"
        @"/dev/ttywd\r\n"
        @"/dev/ttywe\r\n"
        @"/dev/ttywf\r\n"
        @"/dev/urandom\r\n"
        @"/dev/vboxdrv\r\n"
        @"/dev/vboxdrvu\r\n"
        @"/dev/vboxnetctl\r\n"
        @"/dev/xcpm\r\n"
        @"/dev/zero\r\n"

**Comment by matepek** [comment]
yep
