### ISSUE TITLE
Tests not appearing

### ISSUE THREAD

**Issue by rguinn2338** [matepek/vscode-catch2-test-adapter#255]
Without changing the extension settings, I have my test executable in out\Debug\test

The test explorer is not finding any tests, am I missing something?

**Comment by rguinn2338** [comment]
I built the examples in the repo and am still not seeing anything show up.

**Comment by rguinn2338** [comment]
calling the exe with --help matches the regex: Catch v(\d+)\.(\d+)\.(\d+)\s?

**Comment by matepek** [comment]
Please use https://github.com/matepek/vscode-catch2-test-adapter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
and I definitely need logs

**Comment by azyrus66** [comment]
Hi, I've been having the same problem and I think I found the culprit.
In one of my tests I have called system("pause"); at the end so I have to press a key to close it. It looks like TestMate hangs because of this.

**Comment by matepek** [comment]
> system("pause")

There is a 30 sec timeout for that in the code, so it shouldn't hang forever.

@rguinn2338,  I close the issue now but if I get more info I will reopen it so feel free to contribute.

**Comment by rguinn2338** [comment]
**Checklist**

- [x ] The issue is about this extension and NOT about a fork.
- [x ] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x ] The latest version of the extension was used.
- [x ] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**
 The extensions does not appear to be working for me.

**To Reproduce**
    1. Install Extension
    2. Open Test Panel

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/1013318/107896177-2d40cc00-6efb-11eb-866c-3dc1ebc278c0.png)
![image](https://user-images.githubusercontent.com/1013318/107896196-3b8ee800-6efb-11eb-8174-47d6047e5f0e.png)

**Desktop**
- Extension Version: Not sure what this refers to
- VS Code Version: 1.30.1
- Catch2 / Google Test / DOCTest Version: 2.9.12
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

The errors change that pop up change as I go back in time, for example, version 2.4.14:
![image](https://user-images.githubusercontent.com/1013318/108081364-819c9680-7036-11eb-85e4-54cfefb91d71.png)

- Last extension version in which the feature were working: none from what I can tell

**Log** (optional but recommended)

Logging doesn't work since the extension doesn't properly start

**Comment by rguinn2338** [comment]
Wow... my VS Code was not updated.

Works beautifully now, thank you!
