### ISSUE TITLE
How can I disable XML reporter for doctest and use the normal/console reporter?

### ISSUE THREAD

**Issue by yudi-azvd** [matepek/vscode-catch2-test-adapter#256]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X] The latest version of the extension was used.
- [X] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**
Disclaimer: to be honest, I'm not sure this a bug. Maybe I didn't followed the [testmate documentation on this](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md#framework-specific-settings) properly.

I want Testmate to use the console reporter for [doctest](https://github.com/onqtam/doctest) tests when debugging. With console reporter I mean the normal reporter, pretty printed to the console like it happens in this [GIF](https://user-images.githubusercontent.com/37981839/108603680-25b07580-7388-11eb-83cf-308fc416bfd6.png).

I use Testmate with Catch2 (v2.7.0) in another project of mine and the output is the pretty one. Out of curiosity, why isn't this the default behavior for doctest?

I tried the following in the file `./.vscode/settings.json` in my root directory.
```json
{
  "testMate.cpp.test.advancedExecutables": [
    {
      "pattern":"{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
      "doctest": {
        "prependTestListingArgs": [
          "--reporters", "console"
        ],
        "prependTestRunningArgs": [
          "--reporters", "console"
        ],
        "debug.enableOutputColouring": true
      }
    }
  ],
// ...
}
```
But it didn't work. The output is still XML:
![image](https://user-images.githubusercontent.com/37981839/108603752-82139500-7388-11eb-87a8-f5c82d1238c1.png)

**To Reproduce**

You can try cloning this [branch](https://github.com/yudi-azvd/sb-test/tree/branch-for-gh-issue) of the repo:
```sh
git clone --single-branch --branch branch-for-gh-issue https://github.com/yudi-azvd/sb-test
cd sb-test/
make
```
Then open VSCode and debug a `tests/test_a.cpp` or `tests/test_b.cpp` clicking `Debug` above the test case macro. You should see a result similar to the screenshot above.

**Desktop**

- Extension Version: 3.6.20
- VS Code Version: 1.53.2 / 622cb03f7e070a9670c94bae1a45d78d7181fbd4 / x64
- Catch2 / Google Test / DOCTest Version: 2.4.5
- OS Type and Version: Ubuntu 18.04.4 LTS
- Using remote-ssh/docker/wsl?: No

## By the way...
Awesome extension! Thanks for putting the effort.

**Comment by matepek** [comment]
changed to console in the next version. (v3.6.21)

**Comment by yudi-azvd** [comment]
Well, that was fast. 

It's working. Thanks :)
