### ISSUE TITLE
Run task *after* test run

### ISSUE THREAD

**Issue by pkuehne** [matepek/vscode-catch2-test-adapter#258]
**Is your feature request related to a problem? Please describe.**
My code and test code is instrumented so that I can collect test coverage numbers. Once the unit test executable has been run, I can print our the report via `gcovr`. I currently use a custom target in my cmake file for this. I have a coverage highlighter installed (Coverage Gutters), which is great, but requires two steps to be useful. I run the `make` command, which builds the test executable, and TestMate kicks off automatically, but then I still have to manually run the `make coverage` command to generate the xml file and see the coverage gutter update.

**Describe the solution you'd like**
Ideally add a way to run a task *after* the test run, just as there is a way to run one *before* currently.

**Describe alternatives you've considered**
An alternative is to have an action to build, run and collect coverage and use that instead of TestMate

**Comment by matepek** [comment]
It actually has but undocumented. But now I cannot find the documentation about the “before”. How do you know about it?

for “after”: 
> advancedExecutables -> runTask -> after

resolves
- ${absPathArrayFlat}
- ${absPathConcatWithSpace}

**Comment by pkuehne** [comment]
That worked beautifully, thanks! The `before` option isn't documented, but I gathered from other issues that `runTask` runs before the tests.

**Comment by matepek** [comment]
What is your config?

**Comment by pkuehne** [comment]
It looks like this:
```json
"testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "build/test/unit_test",
            "runTask": {
                "before": [
                    "Remove Coverage Files"
                ],
                "after": [
                    "Create Coverage Numbers"
                ]
            }
        }
    ]
```
