### ISSUE TITLE
Doctest only group by/collapse by tags

### ISSUE THREAD

**Issue by notzain** [matepek/vscode-catch2-test-adapter#259]
**Is your feature request related to a problem? Please describe.**
Test Explorer does not group test cases by its test suite with Doctest.

**Describe the solution you'd like**
I would like group all test cases under the name of a test suite. This is possible under gtest (as seen by the picture in the readme), but not in Doctest.

**Describe alternatives you've considered**
I have tried the settings on from the [documentation](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md#testgrouping). `groupByTags` works when it is nested inside `groupBySource`, but I only want to group by tag.

This does not work:
```json
"doctest": {
      "testGrouping": {
          "groupByExecutable": {
              "label": "${filename}",
              "description": "${relDirpath}/",
              "groupByTags": {
                  "tags": [],
                  "label": "${tag}"
              }
          }
      }
  },
```

**Additional context**
Lockdown boredom :)
![image](https://user-images.githubusercontent.com/14364167/110220412-e0329300-7ec5-11eb-8a1f-04db8f2ae97f.png)

**Comment by matepek** [comment]
Uh, that actually should work. It's a bug. Thanks for reporting. Will be fixed in the next release.

**Comment by yudi-azvd** [comment]
was this fixed? I'm having the same problem

![image](https://user-images.githubusercontent.com/37981839/120376659-8558de00-c2f2-11eb-9031-2e1a0f722a8e.png)

In my case, I'm testing the two formats of writing test suites in doctest: `TEST_SUITE()` and `TEST_SUITE_BEGIN()`. But none of them are detected by the test explorer. The picture doesn't show it, but the code using `TEST_SUITE()` has the closing bracket, it's just waay down in the file.

**Comment by matepek** [comment]
It's a typo in the documentation. `${tag}` -> `${tags}`. Thanks for the report. I will fix it.

**Comment by yudi-azvd** [comment]
Yeah, `${tags}` actually works. thanks 😃
