### ISSUE TITLE
testMate.cpp.log.logpanel: true docs

### ISSUE THREAD

**Issue by H-G-Hristov** [matepek/vscode-catch2-test-adapter#261]
In` vscode-catch2-test-adapter/documents/support.md`

> Set testMate.cpp.log.logpanel: true and check the VSCode oputput window. Change the window to "Test Explorer: ...". The log should be there.

Isn't the output in *"C++ Test Mate"*? *"Test Explorer"* is empty.

Is it possible when just using *"Run"* to view just my log messages? I use boost::logger?
With *"Debug"* I can see them easily in Debug Output. Is there something as Terminal output for loggers, std::cout, std::cerr, etc?

**Comment by matepek** [comment]
The "log" means here the extension's log not the test's logs.

All output (cout,cerr) should be in the output window. Please not that the extension runs the test executables special  parameters to generate xml output (except for gtest).
