### ISSUE TITLE
testMate.cpp.debug.configTemplate Setting Shows Incorrect Warning About Missing "Type" Property

### ISSUE THREAD

**Issue by tusharb86** [matepek/vscode-catch2-test-adapter#262]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

The `testMate.cpp.debug.configTemplate` setting complains about a missing "type" property in the schema file of settings.json, but the property is not required if it is set to behave differently per platform. For example, our project has this:

```
  "testMate.cpp.debug.configTemplate": {
    "linux": { "type": "lldb" },
    "osx": { "type": "lldb" },
    "windows": { "type": "cppvsdbg" },
    "program": "${exec}",
    "args": "${argsArray}",
    "cwd": "${cwd}",
    "env": "${envObj}",
    "environment": "${envObjArray}"
  }
```

This way, we use the VS debugger on Windows and lldb on Linux and OSX. This works functionally without an issue, which is fantastic for our scenario! The only problem is the settings.json file shows a warning: `Missing property "type".` See the screenshot pasted below.

**To Reproduce**

Set the `testMate.cpp.debug.configTemplate` mentioned above.

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/18296062/115761136-dcb07980-a356-11eb-8321-08419fc4c527.png)

**Desktop**

- Extension Version: v3.6.24
- VS Code Version: 1.55.2
- Catch2 / Google Test / DOCTest Version: Google Test - 1.10.0
- OS Type and Version: Windows 10/Debian
- Using remote-ssh/docker/wsl?: Local and Docker

**Regression bug?**

Not that I know of, since this is the first time I'm using the setting :)

**Comment by tusharb86** [comment]
I should also add that the documentation [here](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md) should be updated to indicate that a "type" property is not required if it is set for different platforms.

**Comment by matepek** [comment]
Hello,
In theory you are right but... it's hard to implement in that way.
One can silence the value with creating a dummy `type` value:

Like:
```
  "testMate.cpp.debug.configTemplate": {
    "type": "<overwritten by platform-specific value>"
    "linux": { "type": "lldb" },
    "osx": { "type": "lldb" },
    "windows": { "type": "cppvsdbg" },
    "program": "${exec}",
    "args": "${argsArray}",
    "cwd": "${cwd}",
    "env": "${envObj}",
    "environment": "${envObjArray}"
  }
```

Since all the platform versions will overwrite anyway it will work just fine. Other option is to overwrite it on windows only: 
```
   "type": "lldb", 
   "windows": { "type": "cppvsdbg" }
```

I could make it an optional but (I think) most of my users uses it on only 1 platform and for them the warning is actually helpful.

I will update the documentation. I like that you read it. My effort to write it wasn't in vain. :)

If you have other suggestion don't hold it back :)

**Comment by matepek** [comment]
Okay so I've discovered that this platform-specific settings doesn't work for `configTemplate` at all.
I'm fixing it

**Comment by tusharb86** [comment]
Thanks @matepek! Should this issue be re-opened to track or do you have another issue tracking this?

I found that the platform-specific settings do work, but only when I leave out a top-level "type" property. I get the expected behavior on Windows and Linux with this (I didn't test OSX):
```
  "testMate.cpp.debug.configTemplate": {
    "linux": { "type": "lldb" },
    "osx": { "type": "lldb" },
    "windows": { "type": "cppvsdbg" },
    "program": "${exec}",
    "args": "${argsArray}",
    "cwd": "${cwd}",
    "env": "${envObj}",
    "environment": "${envObjArray}"
  }
```

**Comment by matepek** [comment]
I fixed and released it I hope. 

But made small mistake so it was unstable. The fix of that is under process of the release pipeline.

What do you mean by 

> only when I leave out a top-level "type" property

?

**Comment by tusharb86** [comment]
Thanks @matepek! I can confirm that this works as expected now. Also, thanks for the awesome extension 👍
