### ISSUE TITLE
Notification for debug C++ test (gtest) Error while debugging test; Cannot read 'type' of undefined

### ISSUE THREAD

**Issue by hotspot-developments** [matepek/vscode-catch2-test-adapter#263]
*Symptom/Actual*
Clicking 'Debug' above the TEST or the bug icon in the tree view results in a pop-up notification:
Error while debugging test: TypeError: Cannot read property 'type' of undefined
Source: Test Explorer UI (Extension)

*Expected*
The individual test executes in debug mode, stops on breakpoints allows introspection of variables etc. - this used to work for me but now it doesn't.

*Background*
I'm developing for ESP chips (using arduino) via platformio on vscode.
Until recently I have been successfully writing cpp tests using the googletest library, and using your excellent extension along with the Test Explorer extension to execute and debug the code. After a period of inactivity I started a new project and found that the Debug command no longer works. Unfortunately I had taken the opportunity to update my platform so I'm unaware as to which update (if any) caused the issue. As an experiment, I revisited an old project and tried there also - with the same outcome.

*Platform*
Linux - Ubuntu 19.10
VSCode:
<pre>
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.3.0-64-generic
</pre>
Extensions:
C/C++ Tools  1.3.1
C++ TestMate 3.6.25
PlatformIO IDE 2.3.2
Test Explorer UI 2.19.6

Googletest library 1.10.0

I've attached a log file with stack trace.
[vscodeTestAdapterIssueLog.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/6378471/vscodeTestAdapterIssueLog.txt)

**Comment by matepek** [comment]
fixed in 3.6.26

**Comment by hotspot-developments** [comment]
Cool. Actually this partly a problem with Platformio - I think the reason it used to work fine was because I had a launch.json with gdb in it - but if you modify the config for platformio it will overwrite launch.json. 
I managed to overcome this by using a debug.configTemplate as described in your excellent documentation (but not before I accidentally made a typo in the property name adding to my confusion).
Thanks for the update.
