### ISSUE TITLE
how to use doctest and c++ testmate?

### ISSUE THREAD

**Issue by JWleo** [matepek/vscode-catch2-test-adapter#264]
i can't find some example to test the doctest on my vscode with c++ testmate. can anyone help?

i have set the setting.json just like below:

![121](https://user-images.githubusercontent.com/32316654/116362640-d7f73400-a834-11eb-870f-b2c7f1633216.JPG)

but the desk is empty like this:
![image](https://user-images.githubusercontent.com/32316654/116362747-f8bf8980-a834-11eb-9071-e17ddd78a945.png)

**Comment by matepek** [comment]
Seem right to me.

Check https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md
to see the logs.

**Comment by matepek** [comment]
you can PM me on gitter and I might can help you on remote.
