### ISSUE TITLE
sourceFileMap from .vscode/launch.json not used

### ISSUE THREAD

**Issue by milesfrain** [matepek/vscode-catch2-test-adapter#267]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

My launch configuration (`.vscode/launch.json`) contains a `sourceFileMap` entry, but this mapping is not used when debugging an individual test case. For example, when attempting to debug, I'll get errors like this:
> Unable to open 'calc.c': Unable to read file '/proc/self/cwd/src/calc.c' (Error: Unable to resolve non-existing file '/proc/self/cwd/src/calc.c').

This error is due to bazel paths, and is fixed with the following mapping:
```
 `"sourceFileMap": { "/proc/self/cwd": "${workspaceFolder}" `
```

A workaround I found is to add `sourceFileMap` to `testMate.cpp.test.advancedExecutables`, although I don't believe that should be necessary. I'm assuming that the `sourceFileMap` setting should be picked-up from `launch.json` as described here: https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md

**To Reproduce**

An easy way to reproduce this issue is by cloning the following repo and following the steps in the readme:
https://github.com/milesfrain/bazel-googletest

If you skip the `advancedExecutables` setup step (but still add `bazel-bin` to `testMate.cpp.test.executables`), then you should see the same `/proc/self/cwd` error.

If you then configure `advancedExecutables` and copy the `sourceFileMap` setting from `launch.json`, then the mapping errors go away and debugging works.

**Desktop**

- Extension Version: 3.6.26
- VS Code Version: 1.56.2
- Google Test Version: Current master
- OS Type and Version: Ubuntu 20.04
- Using remote-ssh/docker/wsl?: No

**Log**

[snip-log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/6605144/snip-log.txt)
Environment vars removed.

**Comment by matepek** [comment]
If you don't add `sourceFileMap` into `advancedExecutables` the navigation doesn't work I assume. So one should add there anyway. Therefore it might not necessary get from launch.json.

Does the navigation (jumb to test) work for you without adding `sourceFileMap` into `advancedExecutables`?

**Comment by matepek** [comment]
Added "unsupported" functionality in version >=4.0.2
