### ISSUE TITLE
support built-in test explorer

### ISSUE THREAD

**Issue by Trass3r** [matepek/vscode-catch2-test-adapter#270]
This issue is to track support for the new built-in Test Explorer: https://code.visualstudio.com/updates/v1_59#_testing-apis
I saw there's a branch already: https://github.com/matepek/vscode-catch2-test-adapter/compare/vscode-insider-proposed-test-api

**Comment by matepek** [comment]
The API has changed a lot since. I have to start from scratch.

**Comment by SizaSL** [comment]
Just in case if you want try out the vscode native test UI. Set the following settings in settings.json.

`"testExplorer.useNativeTesting": true`

This will use the test UI and you will be able to use most of it's features.

**Comment by Trass3r** [comment]
I see, so the UI is decoupled from the API: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer#migrating-to-native-testing

**Comment by SizaSL** [comment]
> I see, so the UI is decoupled from the API: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer#migrating-to-native-testing

I believe Microsoft provided [test adapter converter](https://marketplace.visualstudio.com/items?itemName=ms-vscode.test-adapter-converter) extensions. Test Explorer UI is depend on that to enable native UI.

**Comment by matepek** [comment]
Added [new activation events](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/package.json#L106) to support `"testExplorer.useNativeTesting": true`.

**Comment by SizaSL** [comment]
> I think I'm seeing [this behaviour](https://github.com/hbenl/vscode-test-explorer/issues/226#issuecomment-907831970) (Test explorer flask icon disappears when switching on native UI) using v3.6.30 with Test Explorer UI 2.21.1, can anyone reproduce

There is a PR waiting to be approved will fix this.

**Comment by Trass3r** [comment]
> Added [new activation events](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/package.json#L106) to support `"testExplorer.useNativeTesting": true`.

Test duration doesn't seem to get updated after the first run. Does that also happen for you guys? Is it a VSCode problem?

**Comment by matepek** [comment]
If it is updated while `"testExplorer.useNativeTesting": false` then I'm afraid this issue is not related to this extension but rather to test-explorer or vscode.

Out of scope, sorry.

BTW I'm working on the native vscode test api which will open the window for new features but also misses some. I'm not sure how I should proceed.
Thinking...

**Comment by Trass3r** [comment]
No it's with the native Test UI.
It also still has some missing features from the UI point of view, but we'll get there.
https://github.com/microsoft/vscode/labels/testing

Apparently the [next features](https://github.com/microsoft/vscode/issues/132467) are:
```
Provide support for tags vscode#129456 @connor4312
Support non-error output for test runs vscode#129201 @connor4312
💪 Explore APIs for test coverage vscode#123713 @connor4312
```

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.
