### ISSUE TITLE
Testmate seems to hang when searching for executables

### ISSUE THREAD

**Issue by AStefan93** [matepek/vscode-catch2-test-adapter#271]
Hi,
I'm trying to set up TestMate on a system in our company and for some reason the extension just hangs while searching for test executables for GTEST. It doesn't throw errors or warnings, it just seems to be working away at something.
The BUILD folder contains one file "dummy_gtest". The executable runs fine on the system if I run it from the command line.
To run it I have to run `"LD_LIBRARY_PATH=/path/to/necessary/libs BUILD/dummy_gtest`
I'm attaching the log as well (I edited it to remove potential sensitive data).

> [2021-08-07 12:56:01.307] [INFO] Creating adapter for /path/to/workspace
[2021-08-07 12:56:01.307] [INFO] Extension constructor <workspace-name> 0 /path/to/workspace linux v14.16.0 {
  node: '14.16.0',
  v8: '8.9.255.24-electron.0',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '87',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1',
  cldr: '38.0',
  icu: '68.1',
  tz: '2021a',
  unicode: '13.0',
  electron: '12.0.4'
} 1.56.2
[2021-08-07 12:56:01.310] [INFO] sentry.io is false
[2021-08-07 12:56:01.315] [INFO] context:config {
  test: {
    executables: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
    advancedExecutables: [ { pattern: 'BUILD/*', env: [Object] } ],
    workingDirectory: '${absDirpath}',
    randomGeneratorSeed: '',
    runtimeLimit: 600,
    parallelExecutionLimit: 1,
    parallelExecutionOfExecutableLimit: 1
  },
  discovery: {
    gracePeriodForMissing: 10,
    runtimeLimit: 5,
    testListCaching: false,
    strictPattern: true
  },
  debug: { configTemplate: null, breakOnFailure: true, noThrow: false },
  log: {
    logpanel: true,
    logfile: '/path/to/file/testMate.log',
    logSentry: 'disable_3',
    userId: '6597d16511eb33de5bee8f87cdb1ff2b45248e26'
  },
  gtest: { treatGmockWarningAs: 'nothing', gmockVerbose: 'default' }
}
[2021-08-07 12:56:01.316] [DEBUG] Active extensions activeVSCodeRemote(ms-vscode-remote.remote-containers) [
  'list of extensions'
]
[2021-08-07 12:56:01.317] [INFO] Registering adapter for /path/to/workspace
[2021-08-07 12:56:01.317] [INFO] load called
[2021-08-07 12:56:01.317] [DEBUG] canceled
[2021-08-07 12:56:01.318] [INFO] context:executables [
  {
    pattern: 'BUILD/*',
    env: {
      LD_LIBRARY_PATH: '/path/to/necessary/libs'
    }
  }
]
[2021-08-07 12:56:01.325] [INFO] load started
[2021-08-07 12:56:01.325] [INFO] Initialization finished
[2021-08-07 12:56:01.325] [DEBUG] ExecutableConfig.resolveVariable:  { value: 'BUILD/*', resolved: 'BUILD/*', strictAllowed: false }
[2021-08-07 12:56:01.325] [INFO] pattern BUILD/*  /path/to/workspace {
  isAbsolute: false,
  absPath: ' /path/to/workspace/BUILD/*',
  isPartOfWs: true,
  relativeToWsPosix: 'BUILD/*'
}

As you can see, the log just stops there. I was expecting it to show that it found some files at least.
On another system, the log shows all the files it went through and which ones didn't pass the initial checks at least.
Is there a way to debug this further? I don't expect a clear answer, but I'd like to have more information about why it doesn't work on this system.
Additional info:
- The google test executable works and runs on my environment. (with some different libraries linked)
- The extension itself works on a different laptop with similar settings.
- The logs look more or less identical on both environments, except the one attached simply stops when it should show which files it found and parsed.

**Comment by matepek** [comment]
Hello,

(Remark: You have to close the vscode to flush the full log (if it generates a log file).)

You can debug the extension by yourself, it is open source :)
Check [CONTRIBUTING.md](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/CONTRIBUTING.md#debug) for that.

I'm just guessing but you are using the `advancedExecutables` feature for the `env` I believe.

```
executables: '{build,Build,BUILD,out,Out,OUT}/**/{test,Test,TEST}',
advancedExecutables: [ { pattern: 'BUILD/', env: [Object] } ],
```

The `pattern` inside that is different than the one in `executables` which is ignored because the former exists. And that one is `BUILD/`. I guess you meant to write `BUILD/*`

**Comment by matepek** [comment]
The executables also seems incorrect.It should be something like: `"{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*"`.
Check [glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)).

**Comment by AStefan93** [comment]
> Hello,
> 
> (Remark: You have to close the vscode to flush the full log (if it generates a log file).)
> 
> You can debug the extension by yourself, it is open source :)
> Check [CONTRIBUTING.md](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/CONTRIBUTING.md#debug) for that.
> 
> I'm just guessing but you are using the `advancedExecutables` feature for the `env` I believe.
> 
> ```
> executables: '{build,Build,BUILD,out,Out,OUT}/**/{test,Test,TEST}',
> advancedExecutables: [ { pattern: 'BUILD/', env: [Object] } ],
> ```
> 
> The `pattern` inside that is different than the one in `executables` which is ignored because the former exists. And that one is `BUILD/`. I guess you meant to write `BUILD/*`

I did restart vscode. What I posted is a clean log file.
Yes, I am using the advancedExecutables. I am using it like this:
`"env": {
					"LD_LIBRARY_PATH": "path/to/libs",
				}`

I modified the path to the executables because the build environment I'm using doesn't generate OUT or BUILD directories. Like I mentioned in the post, I created a new folder BUILD and moved a dummy_gtest executable in there to see if it finds it.

**Comment by matepek** [comment]
I guess accidentally they are edited out again.
Should be:
```
executables: '{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*',
advancedExecutables: [ { pattern: 'BUILD/*', env: [Object] } ],
```

Well if the problem is not this then I'm running out of ideas.. I would follow the investigation with debugging.
I suspect that your system is special. According to the logs the next code piece uses `vscode.workspace.createFileSystemWatcher` and it might just that the underlying implementation is disabled/not installed/etc.. on that system.

**Comment by AStefan93** [comment]
Yes, they did get edited out. I can confirm the paths are correct however.
I will try to debug it then on this system.
I'll look through the tutorial on how to debug it and get back to you if there are any issues :).

**Comment by AStefan93** [comment]
Can you provide more info about vscode.workspace.createFileSystemWatcher please?

**Comment by matepek** [comment]
https://code.visualstudio.com/api/references/vscode-api

**Comment by AStefan93** [comment]
Thanks :) I closed the issue.

**Comment by matepek** [comment]
Success? Let us know what was the problem, might helps someone :)

**Comment by AStefan93** [comment]
Ah, I didn't solve it, I just thought I'd mark it as closed since it doesn't seem to be an issue with the extension itself and the system I'm using is very "special". In a "special" way. We can reopen it and post whatever results I find here if you think it's useful

**Comment by AStefan93** [comment]
The system I was trying on initially was Red Hat 7. I reopened everything in a docker container with Ubuntu latest and it seems to work fine. It might be useful to have some check to warn people of some missing underlying function calls.
