### ISSUE TITLE
[Feature request] native testing API of vscode support

### ISSUE THREAD

**Issue by findNextStep** [matepek/vscode-catch2-test-adapter#279]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
as vscode 1.59.1 released the testing api has offical support.

The test explorer now has support native API but not work will with cpp testmate

cpp test mate only acitve by the test explorer event, may be we need add testing.* into activationEvents or just use the offical API

![image](https://user-images.githubusercontent.com/26270464/131304275-f2346d35-6d60-44d7-9435-32e7974112a0.png)

**Comment by matepek** [comment]
Hello,
Support will be added later.

> test mate only acitve by the test explorer even

Tell me more about your use case.

**Comment by findNextStep** [comment]
> Hello,
> Support will be added later.
> 
> > test mate only acitve by the test explorer even
> 
> Tell me more about your use case.

after enable `testExplorer.useNativeTesting` , call testing.*command(such as testing.runAtCursor) will not active test mate and show test explorer

**Comment by SizaSL** [comment]
> > Hello,
> > Support will be added later.
> > > test mate only acitve by the test explorer even
> > 
> > 
> > Tell me more about your use case.
> 
> after enable `testExplorer.useNativeTesting` , call testing.*command(such as testing.runAtCursor) will not active test mate and show test explorer

Click on test explorer first and populate the tests. Then enable native test UI in Test Explorer UI settings and you will be able to use it afterward.

**Comment by findNextStep** [comment]
> > > Hello,
> > > Support will be added later.
> > > > test mate only acitve by the test explorer even
> > > 
> > > 
> > > Tell me more about your use case.
> > 
> > 
> > after enable `testExplorer.useNativeTesting` , call testing.*command(such as testing.runAtCursor) will not active test mate and show test explorer
> 
> Click on test explorer first and populate the tests. Then enable native test UI in Test Explorer UI settings and you will be able to use it afterward.

after enable testExplorer.useNativeTesting, the test UI disappre.

but `touch .vscode/testMate.cpp.json` work for me

**Comment by SizaSL** [comment]
> > > > Hello,
> > > > Support will be added later.
> > > > > test mate only acitve by the test explorer even
> > > > 
> > > > 
> > > > Tell me more about your use case.
> > > 
> > > 
> > > after enable `testExplorer.useNativeTesting` , call testing.*command(such as testing.runAtCursor) will not active test mate and show test explorer
> > 
> > 
> > Click on test explorer first and populate the tests. Then enable native test UI in Test Explorer UI settings and you will be able to use it afterward.
> 
> after enable testExplorer.useNativeTesting, the test UI disappre.
> 
> but `touch .vscode/testMate.cpp.json` work for me

In that case, I did disable and re-enable the native test UI then both Test Explorer UI and native UI shown up. Right click on title "TESTING" and disable Test Explorer UI from there. These are my current alternatives for using native UI.

**Comment by SizaSL** [comment]
I believe the bug which disappearing test explorer icon (laboratory flask) when native UI is enabled in Test Explorer UI settings is something to do with Test Explorer UI extension rather that C++ Testmate.

**Comment by matepek** [comment]
Added [new activation events](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/package.json#L106) to support `"testExplorer.useNativeTesting": true`.
