### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [matepek/vscode-catch2-test-adapter#28]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [ ] Fix the extension, submit an update to the marketplace
2) [ ] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by matepek** [comment]
Fixed, published,
```[I] ➜ npm ls event-stream flatmap-stream
vscode-catch2-test-adapter@2.2.1 /Volumes/Secure/repo/vscode-catch2-test-adapter
└─┬ vscode@1.1.22
  ├─┬ gulp-remote-src-vscode@0.5.1
  │ └── event-stream@3.3.4
  ├─┬ gulp-symdest@1.1.1
  │ └── event-stream@3.3.4  deduped
  ├─┬ gulp-untar@0.0.7
  │ └── event-stream@3.3.4  deduped
  └─┬ gulp-vinyl-zip@2.1.2
    └── event-stream@3.3.4  deduped
```

**Comment by kondratyev-nv** [comment]
@matepek You can also move `vscode` dependency from `dependencies` to `devDependencies`.

**Comment by matepek** [comment]
Thanks for the tip @kondratyev-nv,
But really? I'm using `vscode.Disposable` and `vscode.EventEmitter` in production code.
I'm new in js and node world, so I may miss some basic concept. Would you explain it to me, please?

**Comment by kondratyev-nv** [comment]
@matepek You don't need them (and also `typescript`, `@types/xml2js`, `@types/entities`) in the runtime (for `vscode` see description https://www.npmjs.com/package/vscode). In examples https://code.visualstudio.com/docs/extensions/samples you can see that `vscode` is a dev dependency. Also, you don't need to install dependencies with `--production` parameter. What will go to the package is defined by `.vscodeignore`, `devDependencies` are automatically ignored.
