### ISSUE TITLE
Tests are being accessed while building

### ISSUE THREAD

**Issue by ahoarau** [matepek/vscode-catch2-test-adapter#284]
This extension is very nice, but I'm facing a problematic issue. 
While building with ninja, and many cores a c++ application, I randomly have this message 

`mt.exe error ..... The process cannot access the file because it is being used by another process.`

On `_test.exe` s.

I believe the test framework is somehow accessing the ressource too soon, causing a stop in the build process. Restarting the build might eventually work. Disabling the extension removes the issue.
Anybody with the same issue ?

**Comment by matepek** [comment]
Try [waitForBuildProcess](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/CHANGELOG.md#added-2) option. Let me know how is that work for you.

**Comment by matepek** [comment]
Might related new feature: https://github.com/matepek/vscode-catch2-test-adapter/issues/406

**Comment by ahoarau** [comment]
So far the CMake option `-DCMAKE_CATCH_DISCOVER_TESTS_DISCOVERY_MODE="PRE_TEST"`  seemed to have done the trick.
