### ISSUE TITLE
Note in docuementation that auto-run relies on VSCode file watchers

### ISSUE THREAD

**Issue by Ipiano** [matepek/vscode-catch2-test-adapter#286]
**Checklist**

- [ x ] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**

My project was not auto-running tests as expected. It took me a while to discover that this was due to the fact that I had excluded `**/build/**` from VSCode file watchers (setting ID `files.watcherExclude`) because the large number of generated build files was causing issues. 

It was not clear to me that this feature would not work correctly because I had excluded the test executable from the watched files in this manner; I would like to see this indicated in documentation (or fixed to not be a problem). 

It would be nice if the extension could detect this issue and notify the user.

**Comment by matepek** [comment]
Hello, Added note to support.md
