### ISSUE TITLE
Catch exceptions in Google Benchmark?

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#290]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I very much like running benchmarks (Google becnhmark) in this test adapter. It generally works very well.
Recently one of the benchmarks would not run and remain gray in the GUI. When running it manually I found that it crashed (which is my fault, there was a bug in the benchmark). But it was not clear from the GUI what was going on.

**Describe the solution you'd like**
Would it be possible that the test adapter catches the crash, and shows the benchmark in error, similar to crashing tests? I.e. it would be awesome to have stderr of the process. Then it would be much more clear what happened.

**Describe alternatives you've considered**
I did not consider alternatives.

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
Please help me verifying it and let me know and I will reopen the issue.

**Comment by emmenlau** [comment]
Awesome, thank you!
