### ISSUE TITLE
Extension affects font settings for output

### ISSUE THREAD

**Issue by codemedic** [matepek/vscode-catch2-test-adapter#291]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

If you have the below config to set the font size for the output window, merely installing the extension makes it invalid (render ineffective)

```json
    "editor.fontSize": 14,
    "[Log]": {
        "editor.fontSize": 11
    },
```

I would assume that an extension like this would not change my preferences related to UI elements as it is not a concern for the said purpose of the extension.

**To Reproduce**

  Steps to reproduce the behavior.

1. Make sure extension `matepek.vscode-catch2-test-adapter` is not installed.
2. Open a dev-container project.
3. Open user settings file `~/.config/Code/User/settings.json` and add the above mentioned settings. Make sure you use two easily distinguishable font-sizes for `editor.fontSize` and `[Log].editor.fontSize`.
4. Reload the window if needed to make sure the above settings take effect. Ensure that the OUTPUT window has the chosen font-size.
5. Now install `matepek.vscode-catch2-test-adapter` and reload window.
6. You will see that the font settings are now lost.
7. Uninstall `matepek.vscode-catch2-test-adapter` and reload window.
8. You will see that the font settings are now restored.

**Desktop**

- Extension Version: C++ TestMate v3.6.32
- VS Code Version: 1.60.2
- Google Test Version: 1.8.1
- OS Type and Version: KDE Neon (Ubuntu 20.04) Linux x64 5.11.0-37-generic
- Using remote-docker?: YES (CentOS 7 based docker container)

**Regression bug?**

New to VSCode and this extension; not sure if it existed before.

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
Please help me verifying it and let me know and I will reopen the issue.
