### ISSUE TITLE
CPU throttling on ubuntu 21.04 in folders with deep symlinked dependencies (e.g. javascript+pnpm/rush projects)

### ISSUE THREAD

**Issue by MichaelBelousov** [matepek/vscode-catch2-test-adapter#292]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

the CPU is throttled by unceasing parallel ripgrep work in projects with lots of symlinks, such as javascript projects
using rush or pnpm.

I'm not sure how you would want to handle this, I haven't done any development of VS code extensions so I don't know
if it is an issue in their search API but I imagine it shouldn't take so much CPU for such a search or it could have a timeout, depending on how it's being done.

Maybe you should never follow symlinks in this particular search, or use a sane max depth like "only search up to 3 deep directories deep" and require people to configure it to search deeper than that?.

I was using this extension for a specific workspace, but now I have to disable it in certain workspaces to prevent this from killing my CPU everytime I open an unrelated javascript project.

**To Reproduce**

1. clone this open source project https://github.com/imodeljs/imodeljs
1. setup the repo with `rush install && rush build`
1. open it in vscode with this extension enabled with default settings
1. CPU usage via ripgrep will start going through the roof unless you disable ripgrep or symlink following in searches

**Screenshots**

![image](https://user-images.githubusercontent.com/16315257/138159590-35d5a480-a6ae-4a44-9870-fd8cf14314f6.png)

**Desktop**

- Extension Version: 3.6.33
- VS Code Version: 1.61.1  c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
- Catch2 / Google Test / DOCTest Version: N/A
- OS Type and Version: Ubuntu 21.04
- Using remote-ssh/docker/wsl?: nope

[testMate.log](https://github.com/matepek/vscode-catch2-test-adapter/files/7383861/testMate.log)

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
Please help me verifying it and let me know and I will reopen the issue.
