### ISSUE TITLE
Output/log colorization changed by plugin

### ISSUE THREAD

**Issue by hohlfma** [matepek/vscode-catch2-test-adapter#294]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

When the plugin is installed and enabled, the colorization in every "output" window as well as every log window gets changed, e.g. numbers and strings get highlighted and link/path highlighting is messed up (false-detection of links).

Other areas of the UI are not affected/changed and the plugin is fully functional.

I would expect no changes on my color scheme / output log colorization by this plugin or, if this is a "feature", it should be working correct (false link detection) and configurable to turn it off. 

**To Reproduce**

1. Install C++ TestMate plugin
--> Output colorization messed up

2. Disable C++ TestMate plugin & Reload VSCode
--> Output colorization back to normal

4. Re-Enable Plugin
--> Colorization messed up again

**Screenshots**

*Before the plugin or with plugin disabled:*

![image](https://user-images.githubusercontent.com/21358685/139230798-1211c7c3-0377-41de-a74c-b767042508db.png)

*Right after plugin gets enabled:*

![image](https://user-images.githubusercontent.com/21358685/139230928-db34492c-6492-4232-bbae-a0031df98316.png)

**Desktop**

- Extension Version: v3.6.33
- VS Code Version: v1.61.2
- Catch2 / Google Test / DOCTest Version: Catch2 v2.13.7
- OS Type and Version: Windows 10 (20H2)
- Using remote-ssh/docker/wsl?: No

Thank you in advance for having a look at this! I really like your plugin and would love to use it without my output window getting messed up :-)

**Comment by hohlfma** [comment]
Some more infos on this issue: 

Using the VSCode Scope Inspector makes clear that the messed up output colorization is due to C++ TestMate language highlighting (`testMate.cpp.testOutput`) which seems to get applied to all the output windows, so also for normal build output and not just when running tests (which would be expected behavior)


![image](https://user-images.githubusercontent.com/21358685/141295950-01706202-351a-4a83-8861-511a76ce38b4.png)

So I see multiple issues here:

- Scope of these highlighting rules is wrong - should be only applied to the output when running tests (if possible?)
- Pattern for detecting paths is buggy (see image in the first post)

**Comment by matepek** [comment]
Soon (1-6 days) a new version will be released without colorisation. Sort for the inconvenience.

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.

**Comment by hohlfma** [comment]
Very well, thank you!
