### ISSUE TITLE
Incorrect diagnostic on exception in REQUIRE

### ISSUE THREAD

**Issue by martin-schulze-vireso** [matepek/vscode-catch2-test-adapter#295]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

When an expression under `REQUIRE( x == y)` throws an exception, the error output just displays as if there was an unequal value (without the value expansion). This does not match the output from catch2.

**To Reproduce**

Compile and run the test in this file:

```
#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>
#include <exception>

int throws() {
	throw std::exception();
}

TEST_CASE("Misleading diagnostic on exception") {
	REQUIRE(throws() == 1);
}
```

Runnig the test case gives:

```
  Expression failed (at test.cpp:10):
    ❕Original:  throws() == 1
    ❗️Expanded:  throws() == 1
```

While the bare output from catch2 is:
```
test is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
Misleading diagnostic on exception
-------------------------------------------------------------------------------
test.cpp:9
...............................................................................

test.cpp:10: FAILED:
  REQUIRE( throws() == 1 )
due to unexpected exception with message:
  std::exception

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

**Desktop**

- Extension Version: 3.6.33
- VS Code Version: 1.61.2
- Catch2 / Google Test / DOCTest Version: 2.13.7
- OS Type and Version: Arch Linux 5.14.15
- Using remote-ssh/docker/wsl?: happens both locally and in docker

**Regression bug?**

Can't install another version, the option is greyed out.

**Comment by martin-schulze-vireso** [comment]
While trying to work around that I just noticed it also happens with `REQUIRE_NOTHROW`.

**Comment by matepek** [comment]
Dear User(s),

Version 4+ has been release. Hoping it makes this issue resolved.
If you disagree then please comment `!open`.

**Comment by martin-schulze-vireso** [comment]
I can confirm a fix. The diagnostic now says that an exception was thrown.
