### ISSUE TITLE
Debugging test uses different debug interface than Run

### ISSUE THREAD

**Issue by emartinfigma** [matepek/vscode-catch2-test-adapter#300]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)

**Describe the bug**

I have a catch2 project configured in my VSCode launch config with `type: lldb`.  When I run it via the Run and Debug pane I can type lldb commands like `print xyz` in the Debug Console.

Following [your docs](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md) I configured things so that your great extension can see all the tests.  If I click the 'play' button on a test it runs quickly.  If I click the 'debug' button on a test the Debug Console requires me to write `-exec print xyz` (with an extra `-exec` prefix) to run lldb commands.

So as best I can tell, it appears that the way your extension spawns lldb is different from how the Run and Debug pane does.  One thing I tried to diagnose this further was uninstalling my local lldb extensions (I was using vadimcn.vscode-lldb).  Once I uninstalled it, running via Run and Debug pops up a dialog: "Configured debug type 'lldb' is not supported."  But if I click debug from within your extension, it still brings up the debugger as described above!

From this I would guess somehow the extension isn't calling into the vadimcn.vscode-lldb extension or something like that.  I don't know how these are supposed to work together, but I would expect they somehow need to connect.

**To Reproduce**

I'm not sure, but maybe it's enough to have a program that is configured in launch.json and then also in the extension and try running it both ways.

**Screenshots** (optional)

Here's what I see in the Debug Console when I pick Run and Debug (with the vadimcn.vscode-lldb installed)

![image](https://user-images.githubusercontent.com/87043219/143096627-81433f77-d78e-4d2d-aca3-ec9de8a42bd7.png)

Here's what I see when I click debug via your extension.  Note the extra yellow text and how the interface is different.

![image](https://user-images.githubusercontent.com/87043219/143096893-6a620cce-0b73-41e4-8b4f-740fcc676b6d.png)

**Desktop**

- Extension Version: 4.0.4
- VS Code Version: 1.62.3
- Catch2 / Google Test / DOCTest Version:
- OS Type and Version: MacOS 11.6
- Using remote-ssh/docker/wsl?: no

**Log** (optional but recommended)

I think this is the relevant portion.  I'd have to review the full log for confidential info before sharing so if you want that let me know.

```
[2021-11-23 20:11:28.401] [DEBUG] debugConfigTemplate {
  debugConfigTemplate: {
    template: {
      name: '${label} (${suiteLabel})',
      request: 'launch',
      type: 'cppdbg',
      MIMode: 'lldb',
      program: '${exec}',
      args: '${argsArray}',
      cwd: '${cwd}',
      env: '${envObj}',
      sourceFileMap: '${sourceFileMapObj}',
      externalConsole: false
    },
    source: 'userDefined',
    launchSourceFileMap: {}
  }
}
[2021-11-23 20:11:28.593] [INFO] Debug: resolved debugConfig: {
  name: 'Zip, writeSync() (/Users/emartin/figma/figma/fullscreen/build/Debug/FullscreenTests) (${suiteLabel})',
  request: 'launch',
  type: 'cppdbg',
  MIMode: 'lldb',
  program: '/Users/emartin/figma/figma/fullscreen/build/Debug/FullscreenTests',
  args: [
    'Zip\\, writeSync()',
    '--reporter',
    'console',
    '--durations',
    'yes',
    '--break'
  ],
```

**Comment by matepek** [comment]
what is the content of your `launch.json`

**Comment by matepek** [comment]
The problem will be that the two scenario uses different debuggers.
If not, I will reopen this.

Comment more info and I will try to help on this
