### ISSUE TITLE
"Run Tests in Current File" only runs the first one

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#305]
**Describe the bug**

If you have multiple test cases within a single .cpp file, invoking the "Test: Run Tests in Current File" command only runs the first of these.

Looking at [the source code of this command in VS Code](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts#L823), it's obvious why: it iterates over all TestItems, and as soon as it finds one with a matching URI, it runs it and returns.

I don't think this is a bug; I guess the assumption is that there is a TestItem describing the whole file, and running that will run all test cases in that file.

Whether it's desirable to have extra nodes in the tree representing the individual cpp files may be a matter of taste; I would actually like that. But it seems it's a necessity for fixing the "Run Tests in Current File" problem.

FWIW: the Python extension works exactly like this, and "Run Tests in Current File" works fine there.

**Desktop**

- Extension Version: 4.0.7
- VS Code Version: 1.62.3

**Comment by matepek** [comment]
> representing the individual cpp files may be a matter of taste; I would actually like that

```
  "testMate.cpp.test.advancedExecutables": [
    {
      "pattern":"*.exe",
      "catch2": {
        "testGrouping": {
          "groupBySource": {}
        }
      },
      "gtest": {
        "testGrouping": {
          "groupBySource": {}
        }
      },
      "doctest": {
        "testGrouping": {
          "groupBySource": {}
        }
      }
    }
  ]
```

or 

```
  "testMate.cpp.test.advancedExecutables": [
    {
      "pattern":"*.exe",
      "catch2": {
        "testGrouping": {
          "groupByExecutable": {
            "groupBySource": {}
          },
        }
      },
      "gtest": {
        "testGrouping": {
          "groupByExecutable": {
            "groupBySource": {}
          },
        }
      },
      "doctest": {
        "testGrouping": {
          "groupByExecutable": {
            "groupBySource": {}
          },
        }
      }
    }
  ]
```

But this won't fix your issue currently because groups are not inherit's the location. 
Although some kind of improvement can be made..

A general solution would be if vscode iterates over and provides all the tests. The url of a test is a `readonly`/`constant` property so easy to create a map for that and do not iterate. How about starting a conversation in vscode repo? What do you think?

**Comment by stefanhaller** [comment]
Thanks for the tip about the grouping by source, that's useful.

As for the actual issue, I'll file a vscode issue when I have some time.

**Comment by stefanhaller** [comment]
VS Code issue is here: https://github.com/microsoft/vscode/issues/138007

**Comment by matepek** [comment]
Sorry for my lazyness but this vscode issue will solve this, right?

**Comment by matepek** [comment]
I added the `groupBySource` so it has an extra node above all the tests which has the `uri` property field but it still picks the first test which is a children of the "source"

- test.exe
  - source.cpp (has uri)
    - test1 (has uri)

So it picks "test1" though source.cpp has uri too.

**Comment by matepek** [comment]
Found the issue. The documentation was misleading or there is a vscode bug. Either way I have a workaround.
With `groupBySource` the "Test: Run Tests in Current File" will work since the next release.

Although the development from vscode would provide amore general soulution. +1

**Comment by stefanhaller** [comment]
Great, thanks. I agree that the vscode issue is still worth doing, but this is a great workaround for the time being.
