### ISSUE TITLE
Catch2 sections don't go away when they are deleted or renamed

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#306]
**Describe the bug**

Catch2 sections don't appear initially, but only after the test case is run for the first time. I realize that we can't do any better, because of the way Catch2 works.

However, if you delete a section, rebuild, and run the test case again, the deleted section doesn't go away from the test explorer. Also, if you rename a section, both the old and new name are shown after you run the test case again.

Also, there doesn't seem to be a work-around for this problem, short of reloading the window, as there is no Rescan button in the new testing environment.

**Desktop**

- Extension Version: 4.0.7
- VS Code Version: 1.62.3

**Comment by matepek** [comment]
Yes, no button. For cases like this there are two command added.
Search for TestMate in command palette.

Known issue. Too much feature to port and create since the new api. Also life is really short.

**Comment by matepek** [comment]
finxed in next rel

**Comment by stefanhaller** [comment]
Fantastic! I ran into this almost every day, and always found it confusing. Great that it's fixed, thanks!
