### ISSUE TITLE
envFile: format consistency with C/C++ extension debugging configuration

### ISSUE THREAD

**Issue by SpaceIm** [matepek/vscode-catch2-test-adapter#307]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Currently, this test adapter can take a "envFile" in json format (https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md#envfile). It's not consistent with envFile expected by C/C++ extension which is a dotenv file. It's not very convenient, since it requires a pre-process parsing the dotenv file to create another format.

**Describe the solution you'd like**
Use dotenv file instead of json in `envFile` property.

**Describe alternatives you've considered**
Either:
- Run my tests in the terminal, so basically not relying on Test adapter.
- after calling conan, parse generated dotenv file and produce a json file specifically for this extension.

**Additional context**
I'm using conan. conan can generate a dotenv file (as well as a .sh to source on Unix platforms & a .bat for windows) with runtime environment variables of dependencies (PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH with dependencies shared libs locations, and any specific env vars of frameworks). When those env vars are not defined while running the tests, tests depending on these dependencies obviously fail since they can't load the shared libs.

**Comment by matepek** [comment]
will be added in next release
