### ISSUE TITLE
Error on reload when groupBySource is nested inside groupByExecutable

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#311]
1. Use the following test file:
```
#include "gtest/gtest.h"

TEST(T, t1)
{
  EXPECT_TRUE(false);
}

int main(int argc, char** argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

2. Set `"testMate.cpp.test.advancedExecutables"` to
```
    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "build/*_test",
            "gtest": {
                "testGrouping": {
                    "groupByExecutable": {
                        "groupBySource": {},
                    },
                }
            }
        }
    ]
```

3. Open the window, or invoke "C++ TestMate: Reload Tests"; this correctly shows the test

4. Touch the executable (or rebuild) -> this triggers the error in https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/AbstractExecutable.ts#L848

- Extension Version: 4.0.9

I can't quite tell whether the error is harmless or not; the test browser looks ok afterwards.

Also, this may or may not be related to #310, I'm not sure.

**Comment by matepek** [comment]
if you could include the full log that would be welcome.

**Comment by matepek** [comment]
but I might found the problem. if yes, you wont see this error since the next release

**Comment by matepek** [comment]
closing this until you see it again
