### ISSUE TITLE
Test discovery and test running can get stuck with parallel execution

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#313]
I apologize for the vague report; I don't have a reproduction recipe, the failure happens only sometimes (but often enough to be annoying), and I can't exactly pinpoint the conditions under which it happens. Still, I thought I'd bring it up, in case you have any ideas already. (Also, I can't attach any logs, since I can only make it happen with my production environment at work.)

**Describe the bug**

When `parallelExecutionLimit` and `parallelExecutionOfExecutableLimit` are set to values greater than 1, test discovery sometimes gets stuck (the indeterminate progress bar at the top of the test browser never stops spinning). 

Also, running all tests of an executable often gets stuck. If that happens, it does run all the tests (I can tell by the number of tests shown at the top of the tests browser, e.g. `Running tests, 1027/1027 (100%)`), but the progress bar keeps showing, and the stop button is still visible. 

Clicking the stop button does nothing in that case. (Which is no surprise I guess, given the `TODO: add cancellation somehow` comment in `ParserInterface.ts`).

**Desktop**

- Extension Version: 4.0.10
- VS Code Version: 1.62.3

**Regression bug?**

Yes; it works fine with 4.0.9, so I suspect it's related to the streaming read.

**Comment by H-G-Hristov** [comment]
Looks like we got something similar here!

**Comment by AdrianPrzetocki** [comment]
Same here, infinite loop on test discovery, had to revert to 4.0.9

**Comment by clipitar** [comment]
Same here...  and I have the problem even with `parallelExecutionLimit `and `parallelExecutionOfExecutableLimit` both set to 1.

**Comment by matepek** [comment]
Which framework?

**Comment by stefanhaller** [comment]
I am seeing both problems (discovery getting stuck, and test running getting stuck) both with Catch2 (2.13.0) and with Google Test (some master commit after 1.10.0).

**Comment by matepek** [comment]
Please try the new release 🤞

**Comment by stefanhaller** [comment]
It does look like that fixed it. Thanks!!  ❤️

**Comment by clipitar** [comment]
Indeed!! Thank you :)
