### ISSUE TITLE
sourceFileMap parameter not documented

### ISSUE THREAD

**Issue by olivier-grech** [matepek/vscode-catch2-test-adapter#315]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
The `sourceFileMap` parameter is not documented.

**Describe the solution you'd like**
I would like the `sourceFileMap` to be documented, with an example if possible.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by matepek** [comment]
Added one to [documents/configuration/test.advancedExecutables.md](./documents/configuration/test.advancedExecutables.md]
