### ISSUE TITLE
Catch2 [!shouldfail] tag ignored when using SECTION

### ISSUE THREAD

**Issue by MuzickMan80** [matepek/vscode-catch2-test-adapter#316]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

A catch2 test containing failing sections, but containing the tag [!shouldfail] should not show as failed in TestExplorer.

For example, this test case is correctly handled, and will show as passing (though arguably it should be shown in yellow, and presented as an ignored test)
 
```
TEST_CASE("Catch2 Test", "[!shouldfail]")
{
  FAIL("Failed to do stuff!");
}
```

However this test case will show as failed:

```
TEST_CASE("Catch2 SectionTest", "[!shouldfail]")
{
  SECTION("Section 1") {
    FAIL("Failed to do stuff!");
  }
}
```

**To Reproduce**

1. Create a cpp file containing a TEST_CASE marked with a [!shouldfail] tag, and containing a failing SECTION.
2. Setup C++ TestMate extension to locate generated .exe file
3. Run the test case using Test Explorer

**Screenshots** (optional)

![image](https://user-images.githubusercontent.com/22546946/146554289-50221a74-ff9b-466b-80ca-a7baa58da299.png)

**Desktop**

- Extension Version: 4.0.15
- VS Code Version: 1.63.1
- Catch2 / Google Test / DOCTest Version: Catch2 v2.9.2
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

- Last extension version in which the feature were working: Unknown

**Log** (optional but recommended)

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.16**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>
