### ISSUE TITLE
Enable use of vscode launch configuration

### ISSUE THREAD

**Issue by Siltyx** [matepek/vscode-catch2-test-adapter#318]
**Checklist**

- [ x ] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
We make use of the vs code launch configurations in launch.json. 
This is auto configured via script for some complicated hardware dependent and/or cross Plattform remote debug stuff with a script.
So it would be very helpful if, instead of selecting the Google Test Executable and transferring this configuration to 
the testMate configuration, to have Test Mate just launch the test executable via the launch.json config.

**Describe the solution you'd like**
Instead of, for example, _**testMate.cpp.test.executables:**pattern-to-gtest-exec_, have something like _**testMate.cpp.test.launchConfig:**name_of_lauch_config_in_launch.json_".

**Describe alternatives you've considered**
- transfer launch config with the possible config options by testMate
- use _GoogleTest Adapter_ extension instead, which does exactly that (But Test Mate is just more useable and more reliable ;) )

**Comment by matepek** [comment]
Thanks for the compliment.
I don't understand your issue. :(
Are you familiar with [debugConfigTemplate](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md)

**Comment by matepek** [comment]
Added a new option to refer items by name. Check it out
