### ISSUE TITLE
Catch2 sections displayed in small, grey font

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#320]
As of a few versions ago, the names of catch2 sections are displayed in the smaller and grey font that is used for descriptions. Was this an intentional change? It looks like a bug to me.

- Extension Version: 4.0.17

**Comment by matepek** [comment]
It was smaller and grey font from the beginning (4.0.x).
It is intentional. 

<img width="300" alt="Screen Shot 2022-01-08 at 17 20 17" src="https://user-images.githubusercontent.com/16504598/148651628-2f16d5b0-5740-43d0-ac2b-e001b7f04391.png">

Is there anything wrong with that? I think they are less important. Also no filter works for them which actually "can be a feature"

Feel free to share your thoughts.

**Comment by stefanhaller** [comment]
Ok, I see that for the nested Given/When/Then style it makes some sense to display it this way.

In our code base, we mostly use `TEST_CASE` for test suites, with `SECTION`s being the individual tests of the suite. In many cases, a .cpp file only has a single `TEST_CASE`.

I think catch2 encourages this style of structuring the tests, because it makes it so easy to put the common setup code in the `TEST_CASE` so that you don't have to write a test suite with setup and teardown, or a test fixture.

And yes, now that you mention it, it has bothered me a few times that I can't filter for section names.

Any chance that you could introduce a setting for this? 😊

**Comment by matepek** [comment]
Now that I can see a use case I can change it but.. beware when (soon) run/debug of sections will be supported, only 1 can be started.

**Comment by matepek** [comment]
Question: How useful would be level1 (and maybe level2,...) tags for you?

**Comment by stefanhaller** [comment]
> Question: How useful would be level1 (and maybe level2,...) tags for you?

I wouldn't know what to use them for, to be honest.

**Comment by stefanhaller** [comment]
There's a regression here: after discovering sections for the first time, they look right, but after running the test a second time, I see all section titles twice; once in the normal black font, and again in the small grey font.

**Comment by matepek** [comment]
right..
