### ISSUE TITLE
Tests not discovered correctly until VS Code is restarted

### ISSUE THREAD

**Issue by cbuchart** [matepek/vscode-catch2-test-adapter#321]
I have several build folders related to different project configurations, for example `build_debug`, `build_debug_feature1`, and so on.

I've set the `test.executables` configuration to match only one of those folders: `"testMate.cpp.test.executables": "build_debug_feature1/**/*{test,Test,TEST}*"`, but when changing to another folder VS Code doesn't refresh correctly the list of test, showing tests for all the `build` folders so far. Only restarting VS Code solves this. Am I missing something?

- Extension Version: 4.0.22
- VS Code Version: 1.63.2
- Google Test Version: 1.10.0
- OS Type and Version: macOS 12.1
- Using remote-ssh/docker/wsl?: Docker

**Comment by stefanhaller** [comment]
Just for the record: this works well for me. I change the `testMate.cpp.test.executables` option very frequently (to switch between build folders), and the extension reliably rediscovers tests in the new folder when I do.

**Comment by matepek** [comment]
Sorry, but not much info to work with.
Are you aware of `testMate.cpp.test.advancedExecutables`? It is an array of patterns like 
```
[{"pattern": "x"}, {"pattern": "y"}]
```

**Comment by cbuchart** [comment]
Yes, I've also used `testMate.cpp.test.advancedExecutables` before. Now I gave a second try and it seems to be working as expected.

It happened to me two o three times in different days on different computers. Maybe something to do the first time the extension is installed?

**Comment by matepek** [comment]
It can be bug but need some stable reproduction steps and/or logs

**Comment by matepek** [comment]
Also there is a command which reloads the tests so you don't have to restart the whole vscode.
