### ISSUE TITLE
Add option to show tests collapsed by default

### ISSUE THREAD

**Issue by cbuchart** [matepek/vscode-catch2-test-adapter#322]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Every time I open VS Code, TestMate detects all the tests and show them to me... expanded. I have to collapse them manually (using the Collapse All button) in order to find the group I need.

**Describe the solution you'd like**
Some setting for collapsing the discovered tests by default.

**Comment by stefanhaller** [comment]
I have the same wish, and I also considered suggesting an option for this. However, I think a better solution would be for VS Code to remember the collapsed/expanded state of all test. You then only have to collapse the tests one last time, and then never again.

This is already implemented in the insiders build, so it will be in the next release; unfortunately it doesn't work completely, see https://github.com/microsoft/vscode/issues/140332.

**Comment by matepek** [comment]
This extension does not responsible for the UI. Please work with VSCode developers regarding to this. 🙏
