### ISSUE TITLE
Provide autorun support with the native testing API

### ISSUE THREAD

**Issue by rlivings39** [matepek/vscode-catch2-test-adapter#324]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

After upgrading the extension to a version using the native testing API, I realized that I lost the ability to auto-run Google test C++ tests. The `...->Enable Autorun` menu item is not present and a rebuild does not automatically rerun my tests. So for now, I'm switching back to the legacy extension. Am I missing the capability in the new version? If not, creating this feature request to support it.

**Comment by matepek** [comment]
Yeah, I'm missing that too.
Will take some time.. :/

**Comment by stefanhaller** [comment]
Yes, this is my only remaining big feature wish too.

However, the way I understand it, it first needs support from VS Code, see https://github.com/microsoft/vscode/issues/134941. While it might also be possible to implement this purely on the extension's side (by extending the context menu for test items), that's not an ideal solution because there wouldn't be a way to visualize which test(s) have auto-run enabled.

**Comment by matepek** [comment]
Feel free to nudge them on their issue. Let them feel that people care about the feature :)

**Comment by H-G-Hristov** [comment]
Is this related. Clicking on Refresh in the test panel produces: command 'python.refreshTests' not found

**Comment by matepek** [comment]
> Is this related? Clicking on Refresh in the test panel produces: command 'python.refreshTests' not found

It's not. That button is provided by the python test provider.

**Comment by matepek** [comment]
> connor4312 added this to the February 2022 milestone 11 days ago

🤞🤞

**Comment by matepek** [comment]
Good news, something is happening in the [neighbourhood](https://github.com/microsoft/vscode/issues/134941).
Currently it is scheduled for March.

**Comment by Trass3r** [comment]
And March it is: https://code.visualstudio.com/updates/v1_77#_finalized-support-for-continuous-test-runs

**Comment by matepek** [comment]
Will be released in `4.4.0` in hours..

I'm excited and a bit disappointed.
UI currently does not support selection of a set of tests to run continuously just everything.
API does support it and the extension supports it already too. It's only limited by the vscode UI.
One can request vscode developers for the feature.

Anyhow let's celebrate.. its a big day for us.

**Comment by Trass3r** [comment]
Ok that sounds bad, I wouldn't want to run e.g. long-running integration tests on every change. Though I guess then they shouldn't even be compiled.

I also wonder how it interacts with filtering: https://github.com/microsoft/vscode/issues/173017

**Comment by matepek** [comment]
https://github.com/microsoft/vscode/issues/178973
