### ISSUE TITLE
"Run tests in current file" runs all tests when invoked in the first source file

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#325]
**To Reproduce**

- In the test browser, click on the "Go to Test" icon of an executable that has several source files; this opens the first source file of that executable.
- Choose "Run tests in current file" -> this runs all tests in all files, not just the ones in the current source file.

The reason is that VS Code asks the extension to run all tests whose URI matches the current file, and since the executable's URI points to its first source file, the executable is included in the list of tests to run in this case.

I suppose the only way to fix this is to remove the URI from the executable again?

- Extension Version: v4.0.22
- VS Code Version: 1.64.0-insider (3dda6ea7ac)

**Comment by matepek** [comment]
Yes. And the URI a readonly property so I have to do some "magic" under the hood (basically recreating the item).
I've already reported that the URI is unwanted to be readonly but they said that "this is easier for them".
With more "magic" it could be solved.. maybe in the future.

**Comment by stefanhaller** [comment]
Why not remove the URI from the executable altogether? I don't find it very useful anyway. Would there be a problem with that?

**Comment by matepek** [comment]
Relates to this: https://github.com/matepek/vscode-catch2-test-adapter/issues/317

**Comment by stefanhaller** [comment]
Ah, but that one was about test suites, not executables. I'm not suggesting to remove URIs from test suites, those are useful, and needed for correct sorting.

**Comment by matepek** [comment]
I'm unsure about this but let's see what the user feedback is.

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.23**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by ryan-holt-1** [comment]
Thanks for working on this. However, I updated to the latest version and still have the same problem. I also still have the same problem as #329 . I do not see cout/cerr messages in the output.

I'm on Linux (Debian 10) if that matters.
