### ISSUE TITLE
dependsOn for rediscovery of tests, not just auto-run

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#326]
If I understand correctly, the `dependsOn` key of `advancedExecutables` is only used to trigger auto-run.

I was hoping that it could also be used to trigger rediscovery of tests. This would be useful for test runners that have some (or all) of their tests in dylibs instead of the main executable.

I understand that overloading `dependsOn` with this functionality is maybe not desired for existing users, so maybe we would need a separate key for that?

**Comment by matepek** [comment]
Interesting.
So you say that one executable depends on `0..*` dylib-s which actually contain the tests.
In advanced executable a `pattern` can mean `0..*` executables. In ideal case one dylib is only part of 1 executable.

Let's say there are two executables found by the pattern and `specialDependsOn` identifies the dylib-s. related to both.
That case both would be reloaded which is unnecessary.
Am I see the problem right?

I cannot think a way to define a pattern which collects multiple executables and set up correct `specialDependsOn`,
so I would say the usage will be that a pattern refers to 1 executable only and the `specialDependsOn` refers the corresponding dylib-s. Would that work for you?

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.24**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>
