### ISSUE TITLE
waitForBuildProcess doesn't work on Mac OS 12.2

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#328]
I experimented with `waitForBuildProcess` (in order to test #326, which will probably require it for me), and found that it doesn't work. Rediscovery is triggered in the middle of a build process for me.

I stepped through the code of ps-node to figure out what's wrong, and I found that it doesn't parse the table of the `ps` command output correctly. In my case, the TIME field appears as the first entry of what should be the COMMAND field.

When I call `ps lx` manually (the command that ps-node uses under the hood), I see that the table columns aren't aligned properly, so this is probably the issue. This may well be a Mac OS bug, I don't know.

One possible fix that may be worth trying is to use [find-process](https://www.npmjs.com/package/find-process) instead of `ps-node`. From a quick glance at the code, it seems to be higher quality; and the code was last changed 3 months ago, while ps-node was last changed 4 years ago (if this is any indication).

I don't have enough Typescript experience to try this myself, sorry...

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.25**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by stefanhaller** [comment]
Thanks for the fix. It doesn't work for me though, because of https://github.com/yibn2008/find-process/issues/56...

Once that is patched locally, it still doesn't work perfectly, because the search pattern could be improved a bit; see #330 for a fix for that.

**Comment by matepek** [comment]
Yeah, I can see. It worked for me with make.
Lemme know when they fixed find-process and we can upgrade.

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.26**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by matepek** [comment]
Might related new feature: https://github.com/matepek/vscode-catch2-test-adapter/issues/406
