### ISSUE TITLE
Should show std::cout and std::cerr test outputs

### ISSUE THREAD

**Issue by svak** [matepek/vscode-catch2-test-adapter#329]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

Consider test:

```cpp
#include <gtest/gtest.h>
#include <iostream>

TEST(Std, NoOutput)
{
    std::cout << "cout\n"; // (1)
    std::cerr << "cerr\n"; // (2)
}
```
When this test executed in terminal:

```sh
[ RUN      ] Std.NoOutput
cout
cerr
[       OK ] Std.NoOutput (0 ms)
```
We see both cout and cerr output.

But, when I press "Show output" button, there is no cout nor cerr output:

```sh
$6│ [ RUN      ] Std.NoOutput @ /home/user/testmate/main.test.cpp:31
$6│ [       OK ] Std.NoOutput (0 ms)
```

**Screenshots** (optional)

**Desktop**

- Extension Version: v4.0.24
- VS Code Version: 1.64.0 (commit #5554b12acf)
- Google Test Version: 1.11 (commit #14aa11db)
- OS Type and Version: Ubuntu 20.04.3 LTS
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

- Last extension version in which the feature were working:

Version v3.6.33 shows cout, but not cerr

```sh
[ RUN      ] Std.NoOutput
cout
[       OK ] Std.NoOutput (0 ms)
```
Version 4.0.0 - 4.0.9 shows cerr, but not cout

```sh
[#1] [ RUN      ] Std.NoOutput (at )
[#1] [       OK ] Std.NoOutput (0 ms)
[#1] ⬇ std::cerr:
[#1] |cerr
[#1] |
[#1] ⬆ std::cerr
```
Version 4.0.10 does not work at all
Versions 4.0.11 - 4.0.24 (latest) does not show cout or cerr output

**Log** (optional but recommended)

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.0.25**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by svak** [comment]
Awesome! Thanks!

**Comment by ryan-holt-1** [comment]
I mentioned in #323 that I still have this issue in the latest version.
