### ISSUE TITLE
Is there a way to read stdout from a test?

### ISSUE THREAD

**Issue by slysherz** [matepek/vscode-catch2-test-adapter#333]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a bug, a feature request or just me being a noob. I can't seem to find any way to look at the stdout for a given test while / after running it. When debugging a test I can see that information in the debug window, but sometimes debugging a test isn't practical (suppose the test failed once and never failed again, it's hard  to know what happened).

**Describe the solution you'd like**
Have a way to look at the stdout for each individual test while / after running it.

**Describe alternatives you've considered**
None.

**Additional context**
My tests are generated with Google test.
If I remember correctly, this used to work at some point and then it stopped working? I'm not sure. Maybe it was when the testing interface changed?

**Comment by matepek** [comment]
There is a new api with interface: Here:
<img width="289" alt="Screen Shot 2022-02-14 at 12 05 50" src="https://user-images.githubusercontent.com/16504598/153852783-6436a409-73af-45c1-99ae-96234d5a7638.png">
 ?

**Comment by slysherz** [comment]
Oh, I had never looked at that button lol. It works great, thanks a lot!

**Comment by matepek** [comment]
No problem, it's a new one
