### ISSUE TITLE
Possible to index only tests on open files?

### ISSUE THREAD

**Issue by juxeii** [matepek/vscode-catch2-test-adapter#335]
Hi,

in CLion, if you open a google test file, the IDE automatically detects the tests and you can run them directly from an annotation. Just like your extension does.
The difference here is that, CLion does not need to find and index all test executables first. I have no idea how it is done there, but it is much faster than just index all executables.

Normally, you only need a small subset of tests to run within one session.
Would it be possible to have the same (more efficient) experience as in CLion?
If would be great if we could tell the extension to just look for the tests in he current open file.

**Comment by matepek** [comment]
Hello,
I believe that CLion might support specific build systems to do this extra smart thing.
This project give a more general solution.

It could be done ofc but it is a big piece of work.
I'm a afraid it wont happen..

Unless someone contributes to this repo. Happy to be a guide.
