### ISSUE TITLE
Add a possibility to group Google Test using regexes on the test executable path/name

### ISSUE THREAD

**Issue by orzechow** [matepek/vscode-catch2-test-adapter#337]
First of all: thanks for this plugin! :+1: 

**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I have a workspace full of projects, each of which has multiple cpp test files. Each cpp test file produces one executable, containing multiple testsuites with again multiple tests.
So, I have four hierarchy levels:

- project / directory
  - test file / executable
    - test suite
      - test

Currently, it seems to me, that it is possible to group by the executable name, regex on the test suite / name / tags – but not by a regex on the test executable path. 

**Describe the solution you'd like**
I'd like to be able to group the tests by project. As the project name is given in the test executable path, it would be sufficient to be able to group by regex on the path.

In the end, I'd like to group by project and maybe aggregate all test executables of a project in the same group:

- project / directory
  - test suite
    - test

**Describe alternatives you've considered**
I tried a couple of things, including https://github.com/matepek/vscode-catch2-test-adapter/issues/231#issuecomment-718895542, but all of the approaches did not work. Grouping by tag regex for example doesn't help, as the tags contain only the test name in my case (how are these tags generated btw?).

**Additional context**
As an example for (part of) the source directory structure, see the [lanelet2 Project](https://github.com/fzi-forschungszentrum-informatik/Lanelet2). We use it within ROS with catkin/cmake as build tool.  
The resulting test files with directory structure:

```
.
├── lanelet2_core
│   └── lib
│       └── lanelet2_core
│           ├── lanelet2_core-gtest-test_area
│           ├── lanelet2_core-gtest-test_attribute
│           ├── lanelet2_core-gtest-test_lanelet
│           ├── lanelet2_core-gtest-test_lanelet_map
│           ├── lanelet2_core-gtest-test_lanelet_map_geometry
│           ├── lanelet2_core-gtest-test_lanelet_or_area
│           ├── lanelet2_core-gtest-test_lanelet_sequence
│           ├── lanelet2_core-gtest-test_linestring
│           ├── lanelet2_core-gtest-test_point
│           ├── lanelet2_core-gtest-test_polygon
│           └── lanelet2_core-gtest-test_regulatory_element
├── lanelet2_io
│   └── lib
│       └── lanelet2_io
│           ├── lanelet2_io-gtest-TestBinHandler
│           ├── lanelet2_io-gtest-TestLanelet2Io
│           ├── lanelet2_io-gtest-TestOsmFile
│           ├── lanelet2_io-gtest-TestOsmHandler
│           └── lanelet2_io-gtest-TestSimpleUsage
├── lanelet2_matching
│   └── lib
│       └── lanelet2_matching
│           ├── lanelet2_matching-gtest-lanelet2_matching
│           └── lanelet2_matching-gtest-lanelet2_matching_integration
├── lanelet2_projection
│   └── lib
│       └── lanelet2_projection
│           ├── lanelet2_projection-gtest-test_Mercator
│           └── lanelet2_projection-gtest-test_UTM
├── lanelet2_routing
│   └── lib
│       └── lanelet2_routing
│           ├── lanelet2_routing-gtest-test_lanelet_or_area_path
│           ├── lanelet2_routing-gtest-test_relations
│           ├── lanelet2_routing-gtest-test_route
│           ├── lanelet2_routing-gtest-test_routing
│           ├── lanelet2_routing-gtest-test_routing_graph_container
│           └── lanelet2_routing-gtest-test_routing_visualization
├── lanelet2_traffic_rules
│   └── lib
│       └── lanelet2_traffic_rules
│           └── lanelet2_traffic_rules-gtest-lanelet2_traffic_rules
└─── lanelet2_validation
      └── lib
           └── lanelet2_validation
                └── lanelet2_validation-gtest-lanelet2_validation
```

In this example, it would be handy to regex the executable name to get these groups:

- lanelet2_core
- lanelet2_io
- lanelet2_matching
- lanelet2_projection
- lanelet2_routing
- lanelet2_traffic_rules
- lanelet2_validation

**Comment by matepek** [comment]
How about 
```
"groupByExecutable": {
  "label": "${absDirpath[-1]}"
}
```
?

**Comment by matepek** [comment]
Also one nest the groupings:
```
"groupByExecutable": {
  "label": "${absDirpath[-4]}",
  "groupByExecutable": {
    "label": "${absDirpath[-1]}"
  }
}
```

**Comment by matepek** [comment]
I see. I will work on this

**Comment by orzechow** [comment]
Thanks :) I hope, it wasn't too confusing.

**Comment by matepek** [comment]
<details>
<summary>Fixed in **v4.1.0**.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by orzechow** [comment]
Great, thanks! :smiley: 
Now, this does exactly, what I was looking for :+1: 

```
"testGrouping": {
    "groupByExecutable": {
        "label": "${absDirpath[-1]}",
        "mergeByLabel": true,
        "groupByTags": {}
    }
}
```

**Comment by matepek** [comment]
Are you still using this feature?
I'm considering some refactoring. This stuff is on the way. Please tell me about your current use case
