### ISSUE TITLE
In-editor lenses for debug and run

### ISSUE THREAD

**Issue by H-G-Hristov** [matepek/vscode-catch2-test-adapter#338]
**Checklist**

- [ X] The issue is about this extension and NOT about a fork.
- [X ] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X ] The latest version of the extension was used.
- [X ] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [X ] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

Are in-editor lenses for debug and run planned? Being able to run Debug from the code editor will be very convenient.
What I mean is a clickable text or icon next/above each individual test in GTest to execute that action.

**Comment by matepek** [comment]
Should be working since the beginning of this project.
Pls. check your related settings.

Also please not if the test framework does not provide line information the extension won't know where to put them.

**Comment by H-G-Hristov** [comment]
![Screen Shot 2022-03-10 at 14 37 49](https://user-images.githubusercontent.com/47526411/157663357-41e9bd75-aea9-48b1-8fbe-15493e0ccd33.png)
![Screen Shot 2022-03-10 at 14 38 17](https://user-images.githubusercontent.com/47526411/157663428-deef12a5-95a9-46e4-bd07-31f6cf624a34.png)

I see the above icons next to test (gtest). Some are duplicated and so are the menu items in the context menu, which appears on right-click. Like for example I see two items "GetServiceLabel".

I don't know if these are part of the extension or VSCode's TestUI.

**Comment by H-G-Hristov** [comment]
Also why do I see sometimes double icons on the left as in the screenshot?

**Comment by matepek** [comment]
Double icons are there because the first one (line 15) is for the test class (multiple tests) and second is for the 1 test instance.

Fro in-editor lenses pls open an issue in vscode. This extension does not have intention to provide UI features.
