### ISSUE TITLE
config Help

### ISSUE THREAD

**Issue by endingly** [matepek/vscode-catch2-test-adapter#339]
If the test list is not displayed in the sidebar, it is just because I have not set `testMate.cpp.test.executables` right? Are there any requirements for the settings of `CMakeLists.txt` to use this plugin?

**Comment by matepek** [comment]
Probably yes.

This extension doesn't care much about cmake.

**Comment by endingly** [comment]
Well, my problem is solved, and I'm going to close the issue.

**Comment by matepek** [comment]
If you could describe what was the solution, that might help others who find their way here. 🙏

**Comment by endingly** [comment]
Oh, the problem is that you can't explicitly define the entry of the test program
