### ISSUE TITLE
Fails to find several of my test suites.

### ISSUE THREAD

**Issue by foxostro** [matepek/vscode-catch2-test-adapter#34]
**Describe the bug**
The extension fails to find several of my test suites. For the missing test suites, the log includes error messages like the following:

> [2018-12-09 23:24:59.165] [WARN] Couldn't load suite: [ TypeError: Cannot read property 'length' of undefined
> [...snip...]
> [2018-12-09 23:24:59.165] [ERROR] but it was a Catch2 executable

**To Reproduce**

1. My project is available on GitHub. Check out this repo: <https://github.com/foxostro/FlapjackOS>
2. Run ./scripts/test.sh to configure and build unit tests.
3. Open VSCode.
4. Click the "test" button in the sidebar.
5. Click the "reload tests" button in the test explorer.

**Expected behavior**
Expected: All executables matching the pattern are listed in the test explorer.
Actual: Only some executables are listed in the test explorer. The results are consistent.

**Screenshots**

**Desktop (please complete the following information):**

- Extension Version: 2.2.5
- VS Code Version: 1.29.1
- Catch2 Version: Catch v2.0.1
- OS Type and Version: macOS 10.13.6

**Log**
Attach log. (optional, Set: `catch2TestExplorer.logfile` and reproduce the bug.)
_Warning_: Log probably contains file and test names too. Consider security conserns before attach!
[catch2TestExplorer.logfile.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/2661139/catch2TestExplorer.logfile.txt)

**Additional context**
I hope that it is possible to diagnose this problem without actually going through the process of building my project. Please let me know if you need any additional information.

**Comment by foxostro** [comment]
Here's the output of that command:

> $ ./KernelTest "[.],*" "--verbosity" "high" "--list-tests" "--use-colour" "no"                                [on master]
> Matching test cases:
>   test_page_frame_allocator_default_ctor
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:7
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_deallocate
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     14
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_deallocate_free_page_frame
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     22
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocation_fails
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     31
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocation_succeeds
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     38
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_is_span_free_0
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     46
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_is_span_free_1
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     52
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_is_span_free_2
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     59
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_is_span_free_3
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     66
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_is_span_free_4
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     75
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_allocate_span_0
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     83
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_allocate_span_1
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     89
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_allocate_span_2
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     96
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_allocate_span_3
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     103
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_allocate_allocate_span_4
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:
>     110
>     (NO DESCRIPTION)
>       [page_frame_allocator]
>   test_page_frame_allocator_configuration_ctor
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/
>     test_page_frame_allocator_configuration_operation.cpp:38
>     (NO DESCRIPTION)
>       [page_frame_allocator_configuration_operation]
>   test_page_frame_allocator_configuration_configure_all_free
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/
>     test_page_frame_allocator_configuration_operation.cpp:44
>     (NO DESCRIPTION)
>       [page_frame_allocator_configuration_operation]
>   test_page_frame_allocator_configuration_configure_none_free
>     /Users/andrewfox/src/FlapjackOS/Kernel/test/
>     test_page_frame_allocator_configuration_operation.cpp:56
>     (NO DESCRIPTION)
>       [page_frame_allocator_configuration_operation]
> 18 matching test cases
>

**Comment by matepek** [comment]
I checked the file. Here is an example.
```
  test_page_frame_allocator_deallocate_free_page_frame
    /Users/andrewfox/src/FlapjackOS/Kernel/test/test_page_frame_allocator.cpp:22
    22
    (NO DESCRIPTION)
      [page_frame_allocator]
```
As you can see the line number is included in a new line too. It's weird. I assume it is a Catch2 bug.
There are no xml output for test-list, so I have to parse the text, and it has the following behaviour: It will start a new line after 80 characters. I think it is related to that.

My suggestions:
- Update your Catch2 to the latest
- `#define CATCH_CONFIG_CONSOLE_WIDTH 200` a big enough number. (see details [here](https://github.com/matepek/vscode-catch2-test-adapter/issues/21#issuecomment-439599804))

Please let me know if it it solves your problem.

**Comment by matepek** [comment]
Hey @foxostro ,
Did it work?

**Comment by foxostro** [comment]
I had a chance to try it out this morning, and it worked. The extension now sees my tests. Thank you!

So, I see that the README does mention this issue:
> (2018-11-17) Long (>80 character) filename, test-name or description can cause test-list parsing failures. Workaround: #define CATCH_CONFIG_CONSOLE_WIDTH 9999

In my opinion, the ideal fix is to change Catch2 so that it supports output test information in a machine readable format such as JSON or XML. Otherwise, would it be possible to have the extension try to detect this condition and log a message about CATCH_CONFIG_CONSOLE_WIDTH? I didn't realize this is what was happening.

**Comment by matepek** [comment]
Great.
I mentioned it to them. They say there will be a xml test-list output format in the next major release.
