### ISSUE TITLE
GTest: Print extra error infromation in test failure lens

### ISSUE THREAD

**Issue by russelltg** [matepek/vscode-catch2-test-adapter#340]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
When my tests fail and I have provided extra information by using `<<` on my `EXPECT_*` call, I need to open the terminal to get that information.

**Describe the solution you'd like**
I would like to see this information. For example, in screenshot below, would like to see "iteration x".

**Describe alternatives you've considered**
Going to the terminal is an alternative, but it's clumsy.

**Additional context**

![image](https://user-images.githubusercontent.com/7105082/159929237-f0feb5fe-3773-4e3e-9939-5941ae191561.png)

**Comment by ryan-holt-1** [comment]
I would also like to see stdout/stderr output in the test failure lens. It is especially problematic when the test seg faults or hits some kind of assertion because the test fails but the lens doesn't show any info.

**Comment by matepek** [comment]
You guys can see the FULL output in the "output window", right?
<img width="382" alt="Screen Shot 2022-04-26 at 18 33 37" src="https://user-images.githubusercontent.com/16504598/165291230-d8bd490d-d771-4330-96d5-6e480b6c3c52.png">

**Comment by matepek** [comment]
the problem with the `<< "msg";` is that I cannot really make difference between `cout` and that.

example:
```
[ RUN      ] TestCas3.test6
/Users/mapek/private/vscode-catch2-test-adapter/test/cpp/gtest/gtest2.cpp:50: Failure
Value of: v
Expected: has 3 elements where
element #0 is equal to 5,
element #1 is equal to 10,
element #2 is equal to 15
  Actual: { 5, 10 }, which has 2 elements
extra message
[  FAILED  ] TestCas3.test6 (0 ms)
```

**Comment by matepek** [comment]
I assume you guys missed that button. If not and you want some new feature to be implemented, let me kow and we can contine the discussion.
