### ISSUE TITLE
Google Benchmarks not detected

### ISSUE THREAD

**Issue by H-G-Hristov** [matepek/vscode-catch2-test-adapter#343]
**Checklist**

- [ X] The issue is about this extension and NOT about a fork.
- [X ] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [X ] The latest version of the extension was used.
- [X ] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [X ] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

I created a simple benchmark with he Google Benchmarks and I expected for it to appear along my Tests but it doesn't. Is this framework supported in the current extension? I checked the documentation but couldn't find that I need to do anything special to enable it.

I use Google Benchmark 1.6.1.

**To Reproduce**

**Screenshots** (optional)

**Desktop**

- Extension Version:
- VS Code Version:
- Catch2 / Google Test / DOCTest Version:
- OS Type and Version:
- Using remote-ssh/docker/wsl?:

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)

**Comment by matepek** [comment]
Hello,
Yes, it should work

**Comment by H-G-Hristov** [comment]
The benchmarks were detected only after I added a `pattern` setting in `settings.json`, e.g.

```json
    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "{build/vscode.}*/**/unicorn-test",
            "cwd": "${absDirpath}",
        },
        {
            "pattern": "{build/build.}*/**/unicorn-benchmark",
            "cwd": "${absDirpath}",
        },
    ]
```

or

```json
    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "{build/vscode.}*/**/*",
            "cwd": "${absDirpath}",
        },
    ]
```

**Comment by matepek** [comment]
This is not clear to me. I assume it is solved. If not please comment and I will reopen it.
