### ISSUE TITLE
Support GUnit framework

### ISSUE THREAD

**Issue by MattYoung50** [matepek/vscode-catch2-test-adapter#344]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Describe the solution you'd like**
I'm using GUnit which is built on top of GTest but only my pure GTest tests are discovered and displayed in the explorer. Running my tests with --gtest_list_tests shows all of my tests. I need a way to customize test discovery by telling TestMate what is a test after running --gtest_list_tests and then how to run that test by running --gtest_filters
https://github.com/cpp-testing/GUnit

**Additional context**
List All Tests with --gtest_list_tests. 5 tests are listed (CalculatorTests.(1), Calculator Tests(1), CalcAddition-AddTwoNumbers(3))
![image](https://user-images.githubusercontent.com/81185602/161050779-fda3a5c7-19d3-4ae3-9b88-237afb34a277.png)
![image](https://user-images.githubusercontent.com/81185602/161050865-a60659f9-98dc-465b-b21e-08b6d4948116.png)

Running CalculatorTests(1)
![image](https://user-images.githubusercontent.com/81185602/161052037-74ca93ae-71f4-41cb-a6d8-bb322a081df7.png)
![image](https://user-images.githubusercontent.com/81185602/161052079-85f71e1d-2b46-4684-9356-59ffe0805b9a.png)

Running Calculator Tests(1)
![image](https://user-images.githubusercontent.com/81185602/161052174-e730e383-c393-4f79-8c46-2ada5e2bffda.png)
![image](https://user-images.githubusercontent.com/81185602/161052215-bfd99628-0d14-4a28-ab81-6d48a93b643e.png)

Running CalcAddition BDD Tests(3)
![image](https://user-images.githubusercontent.com/81185602/161052355-b607e63e-1081-4e98-aeb3-9693c9636cec.png)
![image](https://user-images.githubusercontent.com/81185602/161052382-11560a16-ef0c-4bfc-aa5d-9eac93439a28.png)

**Comment by MattYoung50** [comment]
Clarification: Only my first test `CalculatorTests ShouldReturnCorrectSumOf2Numbers` shows up in the test window:
![image](https://user-images.githubusercontent.com/81185602/161052738-b729c1f1-753c-4019-9842-ca81c33e2974.png)

**Comment by matepek** [comment]
what is the output for `--help` ?

**Comment by matepek** [comment]
test executable

**Comment by MattYoung50** [comment]
![image](https://user-images.githubusercontent.com/81185602/161053139-2209512d-68bc-4436-8cd6-601c701f0ec7.png)

**Comment by matepek** [comment]
This is for the gunit?

and with `--gtest_list_tests --output=xml:tests.xml` ?

**Comment by MattYoung50** [comment]
My test executable links against GTest and GUnit. GUnit extends some of the capability of GTest. The above screenshot was from running that command against my executable that linked against GTest and GUnit.

output from `--gtest_list_tests --output=xml:tests.xml` is the same as with just `--gtest_list_tests`. No Xml file was created.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/81185602/161071451-eccea003-4552-4112-a9fc-56649bee8dc9.png">

**Comment by MattYoung50** [comment]
Any updates on this?

**Comment by matepek** [comment]
Check how version 4.1.1 works for you and let me know.
I might will need complete testa case examples in the future for wider support

**Comment by matepek** [comment]
closing now, but can be reopened
