### ISSUE TITLE
How group by tag in C++

### ISSUE THREAD

**Issue by XNerv** [matepek/vscode-catch2-test-adapter#348]
How group by tag in c++. The documentation is not clear. How can we interact with the vs code to run only tests of a specific tag? Great project, i apreciate any help.

**Comment by matepek** [comment]
Use the "Filter" option at the top of the "Testing" panel.

**Comment by XNerv** [comment]
> Use the "Filter" option at the top of the "Testing" panel.

Following the documentation I couldn't get it to work. How should I specify a group in the configuration below? Could you answer me with an example? I would be very grateful. The group name can be "IntegrationTests"

"testMate.cpp.test.advancedExecutables": [{
        "name": "${relDirpath[-1:]} (${relDirpath[1:-5]})",
        "description": "${filename}",
        "pattern": "build/**/artifact/ninja/bin/tests/**/*{unit}*",
        "cwd": "${absDirpath}",
        "env": {
          "PATH": "${os_env:PATH}${osPathEnvSep}${absDirpath}/../../"
        }
      }
    ],
