### ISSUE TITLE
Add Refresh Support

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#350]
VS Code now has an API to trigger a refresh, see https://github.com/microsoft/vscode/issues/139737. This would allow you to get rid of the "Reload Tests" command, hooking it up to the refresh button instead.

My main motivation for this is that if you use this also for rediscovering tests after e.g. the `testMate.cpp.test.executables` setting has changed, then apparently we would get a progress bar in this case too (see https://github.com/microsoft/vscode/issues/141182). I would find this very useful, as we have a ton of test runners and discovery can take a long time. And I'm changing `testMate.cpp.test.executables` very often.

**Comment by matepek** [comment]
That’s nice. Thanks for the note. 

Btw why are you changing it often?

**Comment by stefanhaller** [comment]
> Btw why are you changing it often?

At work we have our own extension that manages our build system. It has status bar items for choosing the build target, switching debug/release, and other things. It automatically changes `testMate.cpp.test.executables` according to the selected configuration, so that we only see the test executables that are currently being built.

**Comment by matepek** [comment]
btw which command works for you better?
`Reload tests by C++ TestMate` vs `Reload workspaces (in case of an issue) by C++ TestMate` ?

**Comment by matepek** [comment]
Now thinking the refresh should happen automatically in the background. if you click now refresh it will cancel out the already started refresh and start it over.

The problem is I cannot tell the vscode that I'm doing discovery only that I'm reloading part of the tree

**Comment by stefanhaller** [comment]
> Now thinking the refresh should happen automatically in the background.

I'm a little confused now. When changing `testMate.cpp.test.executables`, the refresh does happen automatically already.

> btw which command works for you better?
> `Reload tests by C++ TestMate` vs `Reload workspaces (in case of an issue) by C++ TestMate` ?

I rarely use either. In the case that something didn't refresh properly after changing `testMate.cpp.test.executables`, or after rebuilding, I have used `Reload tests by C++ TestMate` so far, and it seemed to do the job.

I did a quick test just now, and actually `Reload workspaces` seems to do a more thorough job of cleaning things up. I can go into more detail if you want.

**Comment by stefanhaller** [comment]
> > Now thinking the refresh should happen automatically in the background.
> 
> I'm a little confused now. When changing `testMate.cpp.test.executables`, the refresh does happen automatically already.

Oh I get it now, sorry, I misunderstood.

I guess the point of this issue is not so much to support the refresh button; but once you do that, you could use the same code for the automatic refresh (as if the user had clicked the refresh button). According to https://github.com/microsoft/vscode/issues/141182, this would then show a progress bar during the refresh, which it now doesn't.

**Comment by matepek** [comment]
> I did a quick test just now, and actually Reload workspaces seems to do a more thorough job of cleaning things up. I can go into more detail if you want.

I know what they do, I implemented them 😅
I'm merely thinking that is the simpler reload enough or a full reload is needed. the refresh button does the thorough one now but I might change it in the future or make it configurable.

> I rarely use either.

Thats good, In theory rarely should be a need for that.

> I guess the point of this issue is not so much to support the refresh button; but once you do that, you could use the same code for the automatic refresh (as if the user had clicked the refresh button). According to https://github.com/microsoft/vscode/issues/141182, this would then show a progress bar during the refresh, which it now doesn't.

(and)

> So now if you click refresh, the button turns into a cancel button. Shouldn't the same thing happen for the automatic background refresh? What's the problem with that?

I got that part but I didn't see a way on the api. Let me check referenced issue, maybe there are some enlightenment for me.

**Comment by matepek** [comment]
Yeah, sadly no... 
It just a callback and I don't have control over the progress bar and refresh button there. :(
