### ISSUE TITLE
Command for running tests

### ISSUE THREAD

**Issue by inhaledesign** [matepek/vscode-catch2-test-adapter#351]
**Checklist**

- [X] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I have a launch configuration that builds my GoogleTests in a standalone executable, then runs that executable. TestMate sometimes will update after I run this, but it is not reliable.

**Describe the solution you'd like**
If there were a command exposed for running tests, like testMate.cmd.reload-tests, it could be used as a [command variable](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables) in a task that could then be executed in postDebugCommand. Doing so would ensure that tests were run after every execution.

**Describe alternatives you've considered**
There doesn't appear to be a setting in VS Code to auto run tests after building.

**Additional context**
My understanding is that you can use a [command variable in the "command" field of a task](https://stackoverflow.com/questions/57470525/how-can-i-run-a-vscode-command-as-a-task), and that command will be executed. One catch is that the command must return a string, which is presumably ignored in this case. (I tried this with reload-tests but an error was thrown because it does not return a string.)

**Comment by matepek** [comment]
Actually there is a command like that.

**Comment by inhaledesign** [comment]
@matepek When I'm looking at description of C++ TestMate in VS Code's store, I only see:

ID | Command
testMate.cmd.reload-tests | Reload tests
testMate.cmd.reload-workspaces | Force reload workspaces (in case of an issue)

**Comment by matepek** [comment]
https://github.com/matepek/vscode-catch2-test-adapter#commands

**Comment by matepek** [comment]
How is that different from what you need?
