### ISSUE TITLE
TestMate not fetching GTest test cases

### ISSUE THREAD

**Issue by Lygaen** [matepek/vscode-catch2-test-adapter#352]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**
The extension is unable to find any test cases, giving me this message "No tests have been found in this workspace yet.".
I am using the latest version of VSCode, with the following settings for finding executables :
```json
{
    "testMate.cpp.test.executables": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
}
```
While checking the logs, It does seems to be an error.

**To Reproduce**
1. Clone [my repository](https://github.com/Lygaen/mineserver) I uploaded.
2. Open it with VS Code
3. Download the CMake Tools extension
4. Click on "Run CTest" on the status bar
5. Open the "Testing" tab on the left hand side

Here is my [top-level CMakelists.txt](https://github.com/Lygaen/mineserver/blob/master/CMakeLists.txt) and my [CMakelists.txt handling tests](https://github.com/Lygaen/mineserver/blob/master/tests/CMakeLists.txt). 

**Screenshots** (optional)
The testing tab :
![image](https://user-images.githubusercontent.com/53528937/175776015-7516db2a-3d85-4ba2-be89-a5b3f67d305e.png)
The files :
![image](https://user-images.githubusercontent.com/53528937/175776044-b604ae3e-a113-4a98-9276-adbb4a8e6fe9.png)

**Desktop**

- Extension Version: v4.2.2
- VS Code Version: 1.68.1 30d9c6cd9483b2cc586687151bcbcd635f373630 x64
- Google Test  Version: 1.11.0
- OS Type and Version: Arch Linux 5.18.6-arch1-1
- Using remote-ssh/docker/wsl?: No

**Log** (optional but recommended)

```log
[2022-06-25 13:51:48.017] [INFO] Activating extension
[2022-06-25 13:51:48.020] [INFO] Activation finished
[2022-06-25 13:51:51.828] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2022-06-25 13:51:51.830] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: 'build/tests/stream-test',
  resolved: 'build/tests/stream-test',
  strictAllowed: false
}
[2022-06-25 13:51:51.833] [INFO] pattern build/tests/stream-test /home/lygaen/code/mineserver {
  isAbsolute: false,
  absPath: '/home/lygaen/code/mineserver/build/tests/stream-test',
  isPartOfWs: true,
  relativeToWsPosix: 'build/tests/stream-test'
}
[2022-06-25 13:51:51.865] [DEBUG] Checking file for tests: /home/lygaen/code/mineserver/build/tests/stream-test
[2022-06-25 13:51:51.867] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${absDirpath}',
  resolved: '/home/lygaen/code/mineserver/build/tests',
  strictAllowed: false
}
[2022-06-25 13:51:51.868] [DEBUG] ExecutableConfig.resolveVariable:  { value: {}, resolved: {}, strictAllowed: true }
[2022-06-25 13:51:51.886] [DEBUG] Not a supported test executable {
  spawner: s {},
  execPath: '/home/lygaen/code/mineserver/build/tests/stream-test',
  stdout: '',
  stderr: ''
}
```

**Comment by Lygaen** [comment]
We can notice the `Not a supported test executable` at the bottom of the logs but the extension does not that it supports GTest.

**Comment by Lygaen** [comment]
Switched to the test lib `doctest` and it is now working.

**Comment by Lygaen** [comment]
Switched to the lib `doctest` and it is now working.

**Comment by rsehgalaka** [comment]
I am having the same issue. It works on a different setup but I have a new setup where it doesn't work. I am working on a remote ssh host. I do see the extension installed but can't see it under Output!
