### ISSUE TITLE
In VS Code Test Explorer, How to turn off the "play" icon in gutter?

### ISSUE THREAD

**Issue by ydmykr** [matepek/vscode-catch2-test-adapter#353]
In VS Code, with the Python, Text Explorer, and Python Test Explorer extensions, I am able to unit test great with pytest.

But two of the "gutter" icons interfere with each other, and I canoot figure out how to remove one of them.

There are two different windows for Test Explorer with this setup - one for the base Test Explorer, and one for the Python Test Explorer extension. They work basically the same but I find the organization of the tests better in the Python one, so I use that.

In the test code itself, there are various code lenses applied, and other decorators, that allow you to interact with the tests by running, debugging, opening that test in the test explorer window, etc.

These decorators include an icon that shows up in the gutter, which allows you to run the test, then changes afterward to show success or failure. If you right-click on that icon you get multiple test options, as shown below. There is also a secondary icon showing the status behind the triangle "play" icon in the image below:

![image](https://user-images.githubusercontent.com/100815370/179878545-41ec0504-a451-4bda-8624-9ee2ade57ce5.png)

The settings for test explorer allow removing the secondary icon in the background (the faint green circle with the checkmark behind the bright triangle "play" icon), with a setting called "Test Explorer: Gutter Decoration". Changing that removes this secondary icon:

Gutter Decorator True: ![image](https://user-images.githubusercontent.com/100815370/179878574-ed821ad8-4838-47e7-9157-86e0e275a02f.png)
Gutter Decorator False:![image](https://user-images.githubusercontent.com/100815370/179878591-f8c0cbae-1ed6-4fcb-8cf2-3bd1f7fe6f7e.png)

So, my question is - how do I remove the Test Explorer "play" icon from the gutter?

This icon appears to be the main icon connected to the main Test Explorer UI, rather than the Python one (the commands will go to the main UI window and run it's test runs, rather than the Python window). It gets in the way of the status gutter icon behind it that shows the status of the Python test runs and is unnecessary in my setup.

I recently had my PC wiped and I used to have this turned off somehow, but I can't find the setting now. Thanks!

**Comment by matepek** [comment]
Hello,
At first try to delete “Test Explorer” extension.
This extension does not spend on it anymore.
