### ISSUE TITLE
Add support for variable ${workspaceFolderBasename} and config namespace

### ISSUE THREAD

**Issue by ChrisIdema** [matepek/vscode-catch2-test-adapter#354]
Visual studio has several predefined variables: https://code.visualstudio.com/docs/editor/variables-reference, which they unfortunately don't support in settings.json for some reason. Extensions can support them. This Extension does support some of them. But one is I need is missing (it has a different name). It also uses a different namespace: `command:` instead of `config:`

I would like support for ${workspaceFolderBasename}.
The alternative is workspaceName, but I like to be consistent in my settings.json file. I use ${workspaceFolderBasename} in multiple json files.

Example
```
{
    "cmake.buildDirectory": "${workspaceFolder}/../build-${workspaceFolderBasename}",
    "testMate.cpp.test.workingDirectory": "${command:cmake.buildDirectory}",
    "testMate.cpp.test.executables": "${command:cmake.buildDirectory}/${workspaceName}_test.exe",
}
```

I would prefer it like this:
```
{
    "cmake.buildDirectory": "${workspaceFolder}/../build-${workspaceFolderBasename}",
    "testMate.cpp.test.workingDirectory": "${config:cmake.buildDirectory}",
    "testMate.cpp.test.executables": "${config:cmake.buildDirectory}/${workspaceFolderBasename}_test.exe",
}
```
Thus I want workspaceFolderBasename supported and I want `config:` to work too. I use `config:` notation also in tasks.json and launch.json. For example:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Nucleo openocd",
            "cwd": "${workspaceFolder}",
            "executable": "${config:cmake.buildDirectory}/${workspaceFolderBasename}.elf",
```

**Comment by matepek** [comment]
`${workspaceFolderBasename}` can be achieved with `${workspaceFolder[-1]}`.
Config is cool. I'm adding it

**Comment by ChrisIdema** [comment]
I've updated to version 4.2.3, but I don't know how to use config. If I replace command with config testmate doesn't see the tests:
This still works:
```
"testMate.cpp.test.workingDirectory": "${command:cmake.buildDirectory}",
"testMate.cpp.test.executables": "${command:cmake.buildDirectory}/${workspaceName}_test.exe",
```
This doesn't work:
```
"testMate.cpp.test.workingDirectory": "${config:cmake.buildDirectory}",
"testMate.cpp.test.executables": "${config:cmake.buildDirectory}/${workspaceName}_test.exe",
```

**Comment by matepek** [comment]
what is the value of your `cmake.buildDirectory`?

**Comment by ChrisIdema** [comment]
`"cmake.buildDirectory": "${workspaceFolder}/../build-${workspaceFolderBasename}"`
expands to

`~/git/stm32-template/../build-stm32-template`
or
`~/git/build-stm32-template`
According to the logs of CMake in VsCode

**Comment by matepek** [comment]
exactly.
so my extension works it just does not resolve the value recursively.

**Comment by ChrisIdema** [comment]
That's what I suspected. But the recursion does work with `command:` for some reason. Do you have plans to implement the recursion?

**Comment by matepek** [comment]
I think the `command` is basically resolved on the cmake extension's code.
VSCode does not provide an api for variable resolution, I can just query the configs.
Every extension provide their own resolution. Now I added some recursion but I'm not a fan of it. I wouldn't suggest you to depend on a lot but you can try out.
