### ISSUE TITLE
When debug, vscode show this message: Invalid variable reference ${suiteLabel} in string...

### ISSUE THREAD

**Issue by XNerv** [matepek/vscode-catch2-test-adapter#356]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

Running the last version of the plugin, when I try to debug a test, an error is displayed in the vscode UI.

![image](https://user-images.githubusercontent.com/3037797/180655397-4da6ca26-22f3-4906-93e0-431cf755e76b.png)

In the configuration file we don't have any reference to the ${suit Label}.
We tried to find but don't know what can be wrong.

This issue applies to any test. We run the test as in the figure below:
![image](https://user-images.githubusercontent.com/3037797/180655732-b1bd3381-071e-4520-8b49-e38b9d5ee150.png)

This is the configuration file settings.json:

```
"testMate.cpp.discovery.strictPattern": true,
    "testMate.cpp.test.advancedExecutables": [{
        "name": "${relDirpath[-1:]} (${relDirpath[1:-5]})",
        "description": "${filename}",
        "pattern": "build/**/artifact/ninja/bin/tests/**/*{unit}*",
        "cwd": "${absDirpath}",
        "env": {
          "PATH": "${os_env:PATH}${osPathEnvSep}${absDirpath}/../../"
        }
      }
    ],
    "testMate.cpp.debug.configTemplate": {
        "type": "cppvsdbg",
        "win32": { "type": "cppvsdbg" },
        "program": "${absPath}",
        "args": "${argsArray}",
        "cwd": "${absDirpath}",
        "env": {
            "PATH": "${os_env:PATH}${osPathEnvSep}${absDirpath}/../../"
        },
        "environment": "${envObjArray}",
        "console": "externalTerminal",
        "sourceFileMap": "${sourceFileMapObj}",
        "visualizerFile": "${workspaceFolder}/subprojects/eastl/doc/EASTL.natvis"
    },
```

**Desktop**

- Extension Version: v4.2.3
- VS Code Version: 1.69.2
- Catch2 / Google Test / DOCTest Version: 1.10.0
- OS Type and Version: Windows 11
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)

**Comment by matepek** [comment]
wow. so cool to see some people who actually using all these features. :D

It was removed a long-long time ago. (since v4.x)
Are you really need it?

**Comment by matepek** [comment]
Experimentally added: `${parentLabel}` which supports python indexing.
