### ISSUE TITLE
New release [4.2.4] - 2022-07-29 breaks finding any tests for me

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#357]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

Today the newest release [4.2.4] - 2022-07-29 was updated automatically for me. Since this moment, the test extesion does not show any tests any more. Clicking reload does not help. VSCode reports "the extension crashed 3 times in the last 5 minutes".

**To Reproduce**

    1. Install v4.2.3 of the extension
    2. Open the extension to see the tests, everything works, there are 20+ tests listed
    3. Update to v4.2.4 of the extension
    4. Open the extension, there are no tests and VSCode shows the extension as "hanging" while it tries to list tests

**Screenshots** (optional)

**Desktop**

- Extension Version: 4.2.4
- VS Code Version: 1.69.2
- Catch2 / Google Test / DOCTest Version: Google Test 1.11.0
- OS Type and Version: Ubuntu Linux 20.04 x86_64
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

- Last extension version in which the feature were working: Yes, regression against 4.2.3

**Log** (optional but recommended)

**Comment by psypdt** [comment]
I had the same issue, but I was running the extension in docker. The extension freezes and ends up crashing the VSCode instance

**Comment by matepek** [comment]
Darn. Sorry. Will fix asap

**Comment by emmenlau** [comment]
No worries, thanks for the quick help!

**Comment by g-ulli** [comment]
Same here, running with the Remote Containers extension.
