### ISSUE TITLE
Invalid variable reference ${osPathEnvSep} in string:

### ISSUE THREAD

**Issue by fuocor** [matepek/vscode-catch2-test-adapter#358]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [ ] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [ ] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

Hard to say... I am just trying to debug Unit Tests in VSCode when I get the following:

Invalid variable reference ${osPathEnvSep} in string: ${os_env:PATH}${osPathEnvSep}C:\nvidia\omniverse\usd-resolver/_build/target-deps/usd/debug/lib{osPathEnvSep}C:\nvidia\omniverse\usd-resolver/_build/target-deps/omni_client_library/debug.

Hard-coding the path separator changes nothing

![image](https://user-images.githubusercontent.com/15656129/181920872-fa005bfc-a1a3-48d0-b37b-a0ba04acb2e4.png)

- Extension Version: 4.2.5
- VS Code Version: 1.69.0
- DOCTest Version: 2.4.0
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: no

- Last extension version in which the feature were working: Not sure, I kept going back and had the same issue

**Comment by fuocor** [comment]
BTW - Debugging also stopped working. rolling cpptools back to 1.10.8 has everything working

**Comment by matepek** [comment]
It seems working on my computer.
Sorry, not enough info.

**Comment by matepek** [comment]
Cannot reproduce, 
Have you tried checking the logs?
