### ISSUE TITLE
Allow launching gtest suite in a debugger not just an individual test.

### ISSUE THREAD

**Issue by abhishekpandey07** [matepek/vscode-catch2-test-adapter#359]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I have a test executable with several test suites and each suite has several tests. I have botched up one of the suites such that the tests in the suite fail when I run the entire suite but pass when I run the tests individually. I want to debug this by running the entire suite in the debugger.
This is possible in pytest, where you can run an entire module under the debugger not just the individual tests.

**Describe the solution you'd like**
I would like a debug button on the test suite that launches the executable in the debugger and runs with a filter appropriate for running all the tests in the suite.

**Describe alternatives you've considered**
Adding a custom launch.json that uses selectionText to debug the suite - Why have 2 different approaches to debugging?

**Additional context**
N/A

**Comment by matepek** [comment]
Sorry, this extension is not suitable for that currently. (internal batching and other features...)
It should be rare case anyway so a custom `launch.json` solution seems good enough.
