### ISSUE TITLE
advancedExecutables.catch2.prependTestListingArgs not prepending args

### ISSUE THREAD

**Issue by RenSym** [matepek/vscode-catch2-test-adapter#360]
I'm trying to use TestMate with catch2 in a large project that can optionally be compiled with tests. Even in this state, the program can still be run. To run the tests, an optional arg is needed by the program, in this case: "runtests".
"prependTestListingArgs"/"prependTestRunningArgs" seem to be the configurations I need to set. However, this doesn't work. Testmate just runs the program without adding the arg, so it can't even find the tests. A log is attached.

I tried using testmate WITHOUT the optional arg, by statically setting it to "true" in the program itself. Then, testmate runs perfectly fine, all tests are found and testing works.

Is there something else I could have missed?

1. Bind the running of tests to an arg in your program
2. Add your arg to prependTestListingArgs and prependTestRunningArgs
3. Run the extension

**Desktop**

- Extension Version: 4.3.0

- VS Code Version: 1.71

- Catch2 / Google Test / DOCTest Version: Catch v2.13.9

- OS Type and Version: Latest Ubuntu LTS Jammy

**Regression bug?**

Tried a 3.*, same issue. 2.* doesn't seem to have this config yet.

- Last extension version in which the feature were working: No idea, first time using testmate while needing args

[testlog.docx](https://github.com/matepek/vscode-catch2-test-adapter/files/9489128/testlog.docx)

**Comment by RenSym** [comment]
We settled for just using environment variables as the docs suggest.

**Comment by matepek** [comment]
Hey,

Sorry for the late reply, I was AFK.
Happy it is solved. Are you satisfied with the solution or do you think I should look into for some better solution?

**Comment by RenSym** [comment]
We're satisfied, it's alright.

Thanks anyway!
