### ISSUE TITLE
Environment and configuration variable references do not work in settings

### ISSUE THREAD

**Issue by sfreed141** [matepek/vscode-catch2-test-adapter#362]
Right now neither [environment](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) nor [configuration](https://code.visualstudio.com/docs/editor/variables-reference#_configuration-variables) variable references work. It would be super handy if they did.

For example in settings.json
```
    "testMate.cpp.test.executables": "${workspaceFolder}/../Binaries/Debug/x64/bin/*.test.*.exe"
```
works as expected (test discovery succeeds and the testing window populates with my tests) but
```
    "testMate.cpp.test.executables": "${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe"
```
where the `XEF_OutputRoot` variable evaluates to the same path as `${workspaceFolder}/../Binaries` does not work (testing window says "No tests have been found in this workspace yet.").

**Comment by matepek** [comment]
Interesting.. it works for me. please send me logs.
Meanwhile I'm closing this.

**Comment by sfreed141** [comment]
Thanks for the quick response!

Here's what I see with `"testMate.cpp.test.executables": "${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe"`:
```
[2022-10-03 18:37:04.633] [INFO] `test.advancedExecutables` is not defined. trying to use `test.executables`
[2022-10-03 18:37:04.633] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe',
  resolved: '${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe',
  strictAllowed: false
}
[2022-10-03 18:37:04.634] [INFO] pattern ${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe c:\pix\src {
  isAbsolute: false,
  absPath: 'c:\\pix\\src\\${env:XEF_OutputRoot}\\Debug\\x64\\bin\\*.test.*.exe',
  isPartOfWs: true,
  relativeToWsPosix: '${env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe'
}
```
ExecutableConfig.resolveVariable doesn't seem to be evaluating the variable which then leads to the path being interpreted as relative.

Here's the output from a task just to show the values:
tasks.json
```
        {
            "label": "test",
            "type": "shell",
            "command": "echo",
            "args": [ "${env:XEF_OutputRoot}; ${config:testMate.cpp.test.executables}"]
        },
```
output
```
Executing task: echo 'C:\pix\Binaries; C:\pix\Binaries/Debug/x64/bin/*.test.*.exe' 

C:\pix\Binaries; C:\pix\Binaries/Debug/x64/bin/*.test.*.exe
```



Also, when you say it works for you was your variable reference in the middle of the string? It works for me if I do that:
settings.json
```
    "blah": "../Binaries/Debug",
    "testMate.cpp.test.executables": "${workspaceFolder}/${config:blah}/x64/bin/*.test.*.exe",
```
log output
```
[2022-10-03 18:41:47.484] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${workspaceFolder}/${config:blah}/x64/bin/*.test.*.exe',
  resolved: 'c:\\pix\\src/../Binaries/Debug/x64/bin/*.test.*.exe',
  strictAllowed: false
}
[2022-10-03 18:41:47.484] [INFO] pattern ${workspaceFolder}/${config:blah}/x64/bin/*.test.*.exe c:\pix\src {
  isAbsolute: true,
  absPath: 'c:\\pix\\Binaries\\Debug\\x64\\bin\\*.test.*.exe',
  isPartOfWs: false,
  relativeToWsPosix: '../Binaries/Debug/x64/bin/*.test.*.exe'
}
```
So I think this bug is specifically if the variable reference is at the beginning of the string

**Comment by matepek** [comment]
Have you tried putting it to the beginning of the string?
Btw use `os_env` instead of `env`.

**Comment by sfreed141** [comment]
Yes, having the variable at the beginning of the string is what appears to be the issue.

> Btw use os_env instead of env.

I hadn't heard of os_env, and it seems to work when using env vars at the beginning of the string. Thanks!
```
[2022-10-03 20:01:30.445] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${os_env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe',
  resolved: 'C:\\pix\\Binaries/Debug/x64/bin/*.test.*.exe',
  strictAllowed: false
}
[2022-10-03 20:01:30.445] [INFO] pattern ${os_env:XEF_OutputRoot}/Debug/x64/bin/*.test.*.exe c:\pix\src {
  isAbsolute: true,
  absPath: 'c:\\pix\\Binaries\\Debug\\x64\\bin\\*.test.*.exe',
  isPartOfWs: false,
  relativeToWsPosix: '../Binaries/Debug/x64/bin/*.test.*.exe'
}
```

Unfortunately it still doesn't work if I use os_env inside a config variable and then use that config variable in `executables`:
```
[2022-10-03 20:02:52.004] [DEBUG] ExecutableConfig.resolveVariable:  {
  value: '${config:winpix.binaries}/*.test.*.exe',
  resolved: '${os_env:XEF_OutputRoot}\\${env:Configuration}\\${env:Platform}\\bin/*.test.*.exe',
  strictAllowed: false
}
[2022-10-03 20:02:52.004] [INFO] pattern ${config:winpix.binaries}/*.test.*.exe c:\pix\src {
  isAbsolute: false,
  absPath: 'c:\\pix\\src\\${os_env:XEF_OutputRoot}\\${env:Configuration}\\${env:Platform}\\bin\\*.test.*.exe',
  isPartOfWs: true,
  relativeToWsPosix: '${os_env:XEF_OutputRoot}/${env:Configuration}/${env:Platform}/bin/*.test.*.exe'
}
```

**Comment by matepek** [comment]
> Unfortunately it still doesn't work if I use os_env inside a config variable and then use that config variable in executables:

No plan to support that. How unfortunate it is?
What is your use case?

**Comment by sfreed141** [comment]
It's annoying but not a blocker.

My use case is sharing a config variable between settings.json, tasks.json, and launch.json.

**Comment by matepek** [comment]
It sounds to me that it should work with config variables already.
I mean creating a variable in settings.json and the others can refer to it.

Or would you elaborate?

**Comment by sfreed141** [comment]
See [this comment](https://github.com/matepek/vscode-catch2-test-adapter/issues/362#issuecomment-1265967275) for what happens when I try using os_env inside of the config variable (the last code block shows the log output)
