### ISSUE TITLE
vadimcn.vscode-lldb stops working when debugger config template (`configTemplate`) is set

### ISSUE THREAD

**Issue by emmenlau** [matepek/vscode-catch2-test-adapter#369]
Thanks again for your great work, its highly appreciated!

**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

We have been using a debugger config template with the lldb debugger from `vadimcn.vscode-lldb` for a long time successfully on Linux. Recently this week I discovered that the debugger can not be started from this test adapter any more. When I click the debugger symbol next to a test, just nothing happens. I can not say when this stopped working precisely, because I did not use the debugger maybe in 4-6 weeks, hard to be precise. I can only say with certainty that I did not change the `testMate` config in the meantime, but possibly I updated `testMate` extension or `vadimcn.vscode-lldb` extension.

Now the curious part: When I completely remove the section for debugger config template (so the full entry for `configTemplate` in `settings.json`), the debugger immediately starts working again without problems.

Here is my debugger config template from `settings.json`:
```
    "testMate.cpp.debug.configTemplate": {
        "type": "cppdbg",
        "MIMode": "lldb",
        "program": "${exec}",
        "args": "${argsArray}",
        "cwd": "${cwd}",
        "env": "${envObj}",
        "environment": "${envObjArray}",
        "sourceFileMap": "${sourceFileMapObj}",
        "testMate.cpp.debug.setEnv": {
            "GTEST_BREAK_ON_FAILURE": "1",
            "GTEST_CATCH_EXCEPTIONS": "0"
        }
    },
```

**To Reproduce**

  Example:
    1. Install the `testMate` extension and the `vadimcn.vscode-lldb` extension
    2. Copy the above-mentioned debugger config template to `settings.json`
    3. Go to a test and click `debug test`
    4. Nothing happens

**Desktop**

- Extension Version: v4.3.5
- VS Code Version: Version: 1.73.1
- Catch2 / Google Test / DOCTest Version: Google Test 1.12.1 compiled from source with local modifications
- OS Type and Version: Ubuntu Linux 22.04 x86_64
- Using remote-ssh/docker/wsl?: No remote, only local

**Regression bug?**

This is a regression but I do not know against which version.

**Log** (optional but recommended)

Even when I set `testMate.cpp.log.logpanel: true` in `settings.json` there is no Window with name `Test Explorer: ...` in the output windows list. I'm not sure why this does not work, it used to work at some point before.

**Comment by matepek** [comment]
Thanks for the report. vscode has changed something. fix is in the pipeline

**Comment by jpz** [comment]
Thanks for the wonderful extension @matepek - it fills a real gap.  Your extension and the codelldb extension are a tremendous combination.  

I just wanted to report that I seem to have a similar issue, I can get codelldb 1.9.0 to run if it picks it up from the launch.json, but if I specify a config template it seems to launch the gdb debugger from the test window.

It would be good to use the configTemplate, as it gives me a bit more control over the current working directory in particular.

**Comment by matepek** [comment]
Hello @jpz ,

Make sure you specify well the configTemplate. Check codelldb documentation and my documentation regarding the to the configTemplate.
https://github.com/vadimcn/codelldb/blob/master/MANUAL.md
