### ISSUE TITLE
Catch2 macros not logged

### ISSUE THREAD

**Issue by Michal-Hubert** [matepek/vscode-catch2-test-adapter#372]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

The settings.json has an entry:
```
"testMate.cpp.log.logpanel": true
```
The relevant unit test part looks like:
```
if (<some condition>) {
  INFO("Condition failed !")
  FAIL();
}
```
If condition fails then whole unit test is correctly marked as failed but there is no any indicator where. Nothing is highlighted and nothing is printed in the output. If test has a few others such snippets it's very difficult to find out which one actually failed.

**Comment by matepek** [comment]
How about `FAIL( "This test case causes segfault, which breaks CI." );`

[deatials](https://github.com/catchorg/Catch2/blob/devel/docs/skipping-passing-failing.md#top)

**Comment by matepek** [comment]
interestingly my output for
```
TEST_CASE("log macros test") {
  INFO("Logging some INFO");
  FAIL();
}
```

test is:

```
$3│ [ RUN      ] `log macros test` @ /Users/matepek/priv/vscode-catch2-test-adapter/test/cpp/catch2/catch2v3_test1.cpp:94
$3│ │ Info:
$3│ │ │ Logging some INFO
$3│ [  FAILED  ] `log macros test` in 0.000533 second(s)
```

**Comment by Michal-Hubert** [comment]
@matepek thanks for response. I have tested it on a small project and works fine but on a larger one (~700 unit tests) the console output is pretty messy so that's the reason I macros outputs are barely visible. It looks like this: 
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/6475658/215451584-18179c68-4603-4c31-8bdc-3e12fb839702.png">
Is there any way I can debug it further ?  
Btw, shall test run output be also visible in `testMate.cpp.log.logfile' ? I don't see there anything related to test run.

**Comment by matepek** [comment]
Try setting `test.parallelExecutionLimit` to `1`.
That would help to understand more about the issue.

**Comment by Michal-Hubert** [comment]
I see tests being executed sequentially but still the output is messed up.

**Comment by Michal-Hubert** [comment]
@matepek problem solved ! As it's large project I bumped system's `fs.inotify.max_user_watches` and now output looks clean. It looks like it was not testmate specific issue as some other outputs were also messed up.
