### ISSUE TITLE
Cross compilation support - debug individual test cases

### ISSUE THREAD

**Issue by Blumentopf99** [matepek/vscode-catch2-test-adapter#375]
I'm cross-compiling for a different platform and use the `test.advancedExecutables[].executionWrapper` property in order to run our executable in an emulator. That works just fine for
- finding test cases, and
- running individual test cases

because I have full control about how to run the emulator since the `executionWrapper` has access to all the required information.

Now I'd like to _debug_ into individual test cases, in which the workflow is different. Here the emulator is started first using a `preLaunchTask` and then `gdb` connects to the remote server of the emulator. This issue is that I'm lacking some way to pass the parameters `${argsFlat}` provided by the plugin to the emulator (e.g. saying which test case is being debugged). All I can do is tell the emulator to run all tests rather than starting it for a specific test case (e.g. for googletest `gtest_filter=...`). This gets quite annyoing of course when the test suite is large.

Afaik in vscode there is no way to pass a parameter to a `preLaunchTask`, otherwise, I could define `"args": "${argsArray}"` in `debug.configTemplate` and forward it.
Then I thought about setting an environment variable using `debug.configTemplate.env` that I could evaluate in the emulator's task, however, it's not set in the `preLaunchTask'. 

Maybe I'm missing something but _is there any way I can pass a setting from the plugin to my emulator_ (e.g. by parameter, environment, settings file, ...) in the `preLaunchTask` so that I can call the emulator with the correct parameters when debugging individual test cases?

For completeness, this is my reduced debug configuration
```
"testMate.cpp.debug.configTemplate": {
    "type": "cppdbg",
    "program": "${exec}",
    "cwd": "${workspaceFolder}",
    "preLaunchTask": "Start emulator",
    "MIMode": "gdb",
    "miDebuggerPath": "/usr/bin/gdb-multiarch",
    "miDebuggerServerAddress": "localhost:1234"
}
```
with the following reduced `preLaunchTask`:
```
"tasks": [
    {
        "label": "Start emulator",
        "type": "shell",
        "isBackground": true,
        "command": "/usr/bin/qemu-aarch64-static -g 1234 -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/some/path /path/to/test-binary",
        "args": []
    }
]
```
Note that the `command` lacks a way to set a trailing parameter `${argsFlat}`, so always all tests will be executed.

**Comment by matepek** [comment]
Gee, you are probably my most advanced user of mine. When I implemented those features I wasn't sure that even half of them will be used. It warms my hearth.

**Comment by matepek** [comment]
I understand your issue. Will have to think about it.

**Comment by matepek** [comment]
How does your execution wrapper look like?

**Comment by matepek** [comment]
What you would really need is a emulator debugger extension which I'm not sure exists..
The issue comes from the conceptual difference.

**Comment by matepek** [comment]
I can try to help but please share as much information as you can. If must send me to my email address same as my username at gmail

I will delete this comment soon, you probably received an email about it already.

**Comment by Blumentopf99** [comment]
Meanwhile I also played around with the vscode plugin [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable). With that you can prompt for a variable from within `launch.json` and remember it in `tasks.json`. So far this is the only way I found how to propagate variables from `launch.json` to `tasks.json`.

**Comment by matepek** [comment]
So gdb connects to a remote debug session which is happening inside the emulator.

I have an idea... I'm not sure it's easy enough but let's brainstorm.. If can imagine that with gdb one can [call a function](https://sourceware.org/gdb/onlinedocs/gdb/Calling.html).
- loading the test executable as library
- calling it's main with parameters with [setupCommands](https://code.visualstudio.com/docs/cpp/launch-json-reference#_setupcommands)

And since `setupCommands` is inside the `configTemplate` it has access to all the parameters you are looking for.

**Comment by Blumentopf99** [comment]
A workaround is of course to build the unit tests for the host architecture, however, sometimes there may be architecture-specific differences. When we have binaries of different architectures (e.g. x86/64 and aarch64) then the testmate configuration must be adjusted depending on the specific architecture.
Is there a way to configure e.g. `test.advancedExecutables` and `debug.configTemplate` depending on the architecture?

**Comment by matepek** [comment]
try
```
"tasks": [
    {
        "label": "Start emulator",
        "type": "shell",
        "isBackground": true,
        "command": "/usr/bin/qemu-aarch64-static -g 1234 -L /usr/aarch64-linux-gnu -E LD_LIBRARY_PATH=/some/path  /path/to/test-binary ${command:testMate.cmd.get-debug-args}",
        "args": []
    }
]
```
with release 4.3.11.

Let's call it an experimental feature. if one day it stopped working then come back, I probably replaced it to something better.

**Comment by matepek** [comment]
Dont you need a variable for `/path/to/test-binary"`?

**Comment by Blumentopf99** [comment]
You made my day!

Thanks for those special commands, that works when I embed `${command:testMate.cmd.get-debug-args}` into additional double quotes since it carries double quotes as separators for the individual items - e.g. it expands to something like: `--gtest_color=no" "--gtest_filter=testSuite.testCase" "--gtest_also_run_disabled_tests" "--gtest_break_on_failure`
This is malformed without outer double quotes.
