### ISSUE TITLE
Memory leak when running debugger through 

### ISSUE THREAD

**Issue by ynain** [matepek/vscode-catch2-test-adapter#377]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Check the [known issues](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md#known-issues) list.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

When using C++ `std` library containers (but especially the `std::vector`, the debugger hangs indefinitely, and never resumes until the process is stopped. Even after this, the `lldb-mi` process will continue to run and will continue consuming memory until it is force stopped.

**To Reproduce**

Exactly the same issue as described here: https://github.com/microsoft/vscode-cpptools/issues/10176

**Screenshots** (optional)

Hanging indefinitely: 
<img width="357" alt="Screenshot 2023-03-26 at 6 45 22 PM" src="https://user-images.githubusercontent.com/22084517/227809483-379b3949-3026-4b35-8203-a6f7c13741d0.png">

Increased memory consumption within seconds:
<img width="977" alt="Screenshot 2023-03-26 at 6 46 00 PM" src="https://user-images.githubusercontent.com/22084517/227809551-d167b8da-a2e5-45e9-8deb-876417d69794.png">
<img width="977" alt="Screenshot 2023-03-26 at 6 46 07 PM" src="https://user-images.githubusercontent.com/22084517/227809552-21a96b5a-7e30-4742-bf35-de43d3b781fb.png">

After force stopping, the debugger in vscode fails.
<img width="1219" alt="Screenshot 2023-03-26 at 6 46 41 PM" src="https://user-images.githubusercontent.com/22084517/227809555-a5c335e6-8334-4396-9b36-a6671f6a74c4.png">

**Desktop**

- Extension Version: 4.3.12
- VS Code Version: 1.76.2 
- Catch2 / Google Test / DOCTest Version: Google Test 1.12.0
- OS Type and Version: MacOS 13.2.1
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

- Last extension version in which the feature were working:

**Log** (optional but recommended)

Example logs are defined in the issue linked previously: https://github.com/microsoft/vscode-cpptools/issues/10176

**Comment by matepek** [comment]
Hello,
This extension does not come with the debugger. It uses other vscode debugger extensions.
Therefore this issue is most likely unrelated.

**Comment by ynain** [comment]
Are we able to change the debugger that the extension is using? I am able to temporarily rectify the issue by using CodeLLDB as described here. https://github.com/microsoft/vscode-cpptools/issues/7240#issuecomment-1465106629

**Comment by matepek** [comment]
I recommend reading the documentation of this extension. Start with the README.md
