### ISSUE TITLE
Same Executable but Different Environment Variables

### ISSUE THREAD

**Issue by markibrahim88** [matepek/vscode-catch2-test-adapter#379]
Hello, 

I'm new to using catch2 and testmate but I think they're both awesome tools.
After reading through the "Advanced Executables" section to see how I can set an environment variable before running the tests.
This works well, but I was wondering, is there a way to get test mate to run the same tests twice, once using one environment variable and again using a different one?

I thought this would work but it doesn't seem to:
```
   "testMate.cpp.test.advancedExecutables": [
        {
            "name": "Test Suite 1",
            "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
            "env": {
                "CONFIG": "CONFIG_SETTING_1",
            }
        },
        {
            "name": "Test Suite 2",
            "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
            "env": {
                "CONFIG": "CONFIG_SETTING_1"
            }
        }
    ]
```
What am I doing wrong?
Is there some other way to get what I want done?

Thanks in advance,
Mark

**Comment by matepek** [comment]
Hello, 
Nothing, there is a deduplication logic to prevent user mistakes.. 
Let me think about your use case a bit more..

**Comment by matepek** [comment]
btw you probably want something like this:
```
  "testMate.cpp.test.advancedExecutables": [
    {
      "description": "[ENV1] ${relDirpath}/",
      "pattern":"gtest*.exe"
    },
    {
      "name": "${filename} [ENV2]",
      "pattern":"gtest*.exe"
    }
  ]
```
The two items are two examples but you should choose a pattern and stick to it.

**Comment by matepek** [comment]
<details>
<summary>Fixed in <b>v4.4.1</b>.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by matepek** [comment]
So now it is supported but in general you can achieve this with a little abstraction in your code. That's usually a preferable approach.

**Comment by markibrahim88** [comment]
Wow, that was fast, thanks!
How would I do it as part of version 4.4.1?
Can you help me understand how I would do with my own abstraction?

**Comment by matepek** [comment]
as part of the `4.4.1`: 
> Just exactly as you tried but see my suggestion above.

with abstraction: 
> Your code acquires the environment variable, right?
> You can create a service which can be mocked and then two separate tests can call the same functionality with different mocking.

**Comment by markibrahim88** [comment]
Got it, thanks again! Sorry about that.
