### ISSUE TITLE
Soft path to executables

### ISSUE THREAD

**Issue by zanaviska** [matepek/vscode-catch2-test-adapter#380]
Before the feature idea itself, I just want to thank you for your extension, because I searched for similar extension for a long time and have finally found you

**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
My build folder is changing depending on build type
```
"cmake.buildDirectory": "${workspaceFolder}/../vscode_build_${buildType}"
```

So now, each time I change my build type, I have to manually change executables path
```
"testMate.cpp.test.executables": "../vscode_build_Debug/Out/Debug/*",
//or
//"testMate.cpp.test.executables": "../vscode_build_Release/Out/Release/*",
```

**Describe the solution you'd like**
The easiest solution I came up is allowing usage of vscode variables inside pathes, that extension uses

**Describe alternatives you've considered**
Maybe it is a completely different feature(and may be useless, because is covered somehow), but it is connected in my case. I would like to keep everything as it is by default, but change default build folder, so I do not need write the whole path to executables, just to the top level build folder

**Comment by matepek** [comment]
You have two options:

First:

```json
  "testMate.cpp.test.advancedExecutables": [
    {
      "name": "${filename} [DEBUG]",
      "pattern":"../vscode_build_Debug/Out/Debug/*",
    },
    {
      "name": "${filename} [RELEASE]",
      "pattern":"../vscode_build_Release/Out/Release/*",
    }
  ]
```

Second:

```json
  "testMate.cpp.test.advancedExecutables": [
    {
      "pattern":"${command:cmake.cmakePath}",
    }
  ]
```

Though I haven't tested.

BTW the `..` somethin is usually not a good idea. Everything should be under your working directory in vscode. You can set up folders to be ignored.

**Comment by Debitsch-Faro** [comment]
`"testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "${command:cmake.buildDirectory}/**/*{test,Test,TEST}*"
        }
    ]`

works fine for me.
