### ISSUE TITLE
Use TestMate properly with CMake

### ISSUE THREAD

**Issue by dlschmidt** [matepek/vscode-catch2-test-adapter#381]
**Checklist**

- [X] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Currently I have to rebuild the whole CMake project every time before running a test:
```json
"testMate.cpp.test.advancedExecutables": [
  {
    "pattern": "build/*/*",
    "cwd": "${absDirpath}",
    "runTask": {
      "before": [ "prerun-task" ]
    }
  }
]
```
This is a suboptimal solution because often I just want to start a single TestSuite and not the whole project, then the whole rebuild would not be neccessary.

**Describe the solution you'd like**
I would like to give the task an variable which TestSuite actually will be started. For example, when starting "Run All Tests" this could be `null` but after starting a single test this could contain the full name of the test that will be started.

**Comment by matepek** [comment]
It works the other way around. You rebuild your executable and the
extension detects it and if autorun is enabled it will run it. Later on
vscode will support to select tests to autorun, now all the tests only.

**Comment by dlschmidt** [comment]
Thank you very much for your reply.
Yesterday I have seen that the Autorun Selection is already implemented in the Nightly Build of VSCode, but of course this needs to be implemented in the Test Adapter as well.

I will try to add a `--watch` mode to my utility scripts which will rebuild the executables as needed.

Does TestMate already interact with the new VSCode Testing API? I think there is a new boolean for watch support.
That would be great if TestMate would launch a filewatcher which then will rerun tests / executables when needed.

**Comment by dlschmidt** [comment]
I am very surprised that TestMate already supports the Watch mode. Therefore I can close this issue.

**Comment by matepek** [comment]
I'm not sure you are using the latest version of my extension. Test Explorer/Test Adapter API has been removed for a year, now it's native.

**Comment by matepek** [comment]
Btw the closed issues can be very helpful. there are al ot of similar cases

Also related: https://github.com/matepek/vscode-catch2-test-adapter/issues/324

**Comment by dlschmidt** [comment]
@matepek I am using the newest version of `matepek.vscode-catch2-test-adapter`, definitely the native one.
Yeah in the first place I did not take autowatch into consideration that this would solve my problem, but fortunately it did.

Thanks!
