### ISSUE TITLE
Logging with log.logpanel settings doesn't work

### ISSUE THREAD

**Issue by vakokako** [matepek/vscode-catch2-test-adapter#382]
**Describe the bug**

Neither of the following logging settings work:
```json
"testMate.cpp.log.logpanel": true,
"testMate.cpp.log.logfile": "/tmp/testMate.log",
```
The "/tmp/testMate.log" isn't created and I don't see any output in the log panel.

**Comment by emmenlau** [comment]
Oh yes, this is also a problem for me. I do not see any logging, not with these settings and also not in the output window.

**Comment by matepek** [comment]
Well I cannot reproduce.

Btw, one has to reload vscode after changing those flags.

**Comment by matepek** [comment]
I'm closing this. if the restart doesn't solve feel free to create a new issue according to the description

**Comment by vakokako** [comment]
After reloading logging still doesn't work.
