### ISSUE TITLE
Support for environment variables from .env

### ISSUE THREAD

**Issue by iluetkeb** [matepek/vscode-catch2-test-adapter#384]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
My tests require setting LD_LIBRARY_PATH (this is something coming from an external dependency which I can't change). Unless this is set, discovering the tests fails due to libraries not being found.

I have added the required paths to .env, but it seems testmate doesn't use this. I'm also using the VS Code "ros" extension which loads these variables as well, but apparently also not in a way that testmate can use.

**Describe the solution you'd like**
I'd like testmate to set environment variables from .env or those exposed by the ros extension prior to discovery.

**Additional context**
This is an example error from the testmate log 
```
[2023-04-28 11:12:31.941] [DEBUG] Not a supported test executable {
  spawner: s {},
  execPath: '/home/developer/bcr2/ros_ws/build/bcr2_online_coverage_path_planning/test_edge_extractor',
  stdout: '',
  stderr: '/home/developer/bcr2/ros_ws/build/bcr2_online_coverage_path_planning/test_edge_extractor: error while loading shared libraries: libbackward.so: cannot open shared object file: No such file or directory\n'
}
```

**Comment by matepek** [comment]
actually it is already supported. check the docs of advancedExecutables

**Comment by iluetkeb** [comment]
Thank you for the quick feedback. I've tried this by adding "${os_env:LD_LIBRARY_PATH}", which didn't work, and by adding all the variables explicitly, which did.
May I ask why you have implemented it this way, instead of using the .env-file approach that VS Code normally uses? Just curious.

**Comment by iluetkeb** [comment]
btw, just for context: In the ROS ecosystem that I work in, there are quite a few environment variables, and they change relatively frequently. the paths are dependent on which packages I'm currently developing on, and there are also some other variables. that's why the ROS extension loads a configuration script. I'm not sure why this is not available to your extension, though. Maybe I need to ask the ROS extension author.

**Comment by matepek** [comment]
There should be an envFile variable under the advancedExecutable. Have you
tried that?
