### ISSUE TITLE
Add commands for run test and debug test

### ISSUE THREAD

**Issue by thirtytwobits** [matepek/vscode-catch2-test-adapter#386]
I really love the ability to debug individual googletests using your plugin (amazing work by the way). The one thing that'd keep my fingers on the keyboard more would be a way to designate an individual test or test suite as the target for a vscode command. This would allow my to then map that command to a keyboard shortcut. This is similar to how the cmake tools work where you can right-click on a target in the cmake sidebar and "set as build target". I'd like your adapter to support "set as debug command" or "set as run command" in the same manner.

Thanks.

**Comment by matepek** [comment]
Hey, Thanks.

What is a "target"?
What do you wanna achieve? (A fully explained expected workflow werehelpful)
I'm afraid I don't really get you..

**Comment by thirtytwobits** [comment]
In the cmake panel you can right-click on a test binary and set it as the current build/debug target:

<img width="437" alt="Screenshot 2023-06-04 at 7 08 09 PM" src="https://github.com/matepek/vscode-catch2-test-adapter/assets/19180861/c5560649-8d43-4248-9665-28986b595546">

I'd like the same ability in your plugin so I can quickly hit F5 and be debugging just the one google test:

<img width="510" alt="Screenshot 2023-06-04 at 7 07 44 PM" src="https://github.com/matepek/vscode-catch2-test-adapter/assets/19180861/9daaab23-79bb-4884-b9a7-42f4f559ea25">

**Comment by matepek** [comment]
First, this extension doesn't really do anything related to the UI. That vscode does it natively. So if you have UI related requests you can do it on their github repo.

Secondly, I think the following feature is very close to what you re looking for.

<img width="733" alt="Screenshot 2023-06-05 at 11 41 05" src="https://github.com/matepek/vscode-catch2-test-adapter/assets/16504598/b3bd2a82-a7dc-4a2e-9e53-9487afed678f">
