### ISSUE TITLE
Auto-run doesn't work with Catch2 sections

### ISSUE THREAD

**Issue by stefanhaller** [matepek/vscode-catch2-test-adapter#387]
**Describe the bug**

I'm thrilled to see that auto-run now works, even on a per-test-case level. This is fantastic!

However, for Catch2 it only seems to work for `TEST_CASE`s, not for `SECTIONS`. I can turn on the Continuous Run icon for those, but it doesn't seem to have any effect. Interestingly, they are also not sorted to the top if I sort by status. When turning on auto-run for a `TEST_CASE`, it does get sorted to the top.

I'm not sure it's technically possible to support auto-run for sections, but if it isn't, it would be great to get some sort of error or other feedback to indicate that this doesn't work.

**Desktop**

- Extension Version: v4.4.2
- VS Code Version: 1.79.0-insider, Commit: a8e719eeed4
- Catch2 Version: v3.1.0

**Comment by matepek** [comment]
It seems to me that sorting is working on the same level only. But maybe can be changed in the "..." menu.
Anyway it is not related to this extension. UI related stuff should be reported to vscode's github page.

**Comment by matepek** [comment]
<details>
<summary>Fixed in <b>v4.4.3</b>.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by stefanhaller** [comment]
Nice, thanks for the quick fix!
