### ISSUE TITLE
Add mergeByLabel to groupByExecutable

### ISSUE THREAD

**Issue by abmantis** [matepek/vscode-catch2-test-adapter#389]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**

I have the following file tree:

```
integration/testI.cpp
unit/testA.cpp
unit/testB.cpp
```

---

I want to group them as 

- integration
  - TestIClass
    - Test1
    - Test2
- unit
  - TestAClass
    - Test1
    - Test2
  - TestBClass
    - Test1
    - Test2

---

But currently I can only get:

- integration
  - TestIClass
    - Test1
    - Test2
- unit
  - TestAClass
    - Test1
    - Test2
- unit
  - TestBClass
    - Test1
    - Test2

**Describe the solution you'd like**
Having a `mergeByLabel` option on `groupByExecutable` that would merge the groups that have the same label.

**Comment by matepek** [comment]
It has this functionality already. I can achieve what you are looking for.
```json
{
"testMate.cpp.test.advancedExecutables": [
    {
      "pattern":"integartion/**/test*.exe",
      "gtest": {
        "testGrouping": {
          "groupByExecutable": {
            "mergeByLabel": true,
            "label": "Integration",
            "groupByTags": {}
          }
        }
      }
    },
    {
      "pattern":"unit/**/test*.exe",
      "gtest": {
        "testGrouping": {
          "groupByExecutable": {
            "mergeByLabel": true,
            "label": "unit",
            "groupByTags": {}
          }
        }
      }
    }
  ]
}
```

**Comment by abmantis** [comment]
That works, but requires having individual settings for each of the directories, including repeating the same executionWrapper and so on. 

Also, we have a different use case at the moment where we have:

- domainA
  - app1
  - app2
- domainB
  - app3
  - app4
- domainC
  - app5

But since `mergeByLabel` is not working for `groupByExecutable`, TestMakes shows the following:
- domainA
  - app1
- domainA
  - app2
- domainB
  - app3
- domainB
  - app4
- domainC
  - app5


Our settings:
```
{
    "pattern": "/build/src/**/**ut*",
    "cwd": "${absDirpath}",
    "gtest": {
        "testGrouping": {
            "groupByExecutable": {
                "label": "${absDirpath[3]}",
                "mergeByLabel": true,
                "groupBySource": {
                    "label": "${sourceRelPath[-2:]}",
                    "groupByTags": {}
                }
            }
        }
    }
}
```
