### ISSUE TITLE
Embedded Usage?

### ISSUE THREAD

**Issue by duaneellissd** [matepek/vscode-catch2-test-adapter#390]
**Checklist**

- [ ] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**

I am very frustrated that I cannot find an embedded friendly test framework that works with an IDE.
one of my team showed us how this works on a Linux application under VS CODE - we all  think it is well done.

But I also think making this work for embedded systems is nearly impossible. I want to be proven wrong.

**Describe the solution you'd like**

As a very trivial example, setup a Cross Compile environment on an X86 Linux machine to cross compile to an RASPBERRY PI (My actual use case is far more complicated)

Here is an example of how to create a simple hello world application and run it on the r-pi.

https://deardevices.com/2019/04/18/how-to-crosscompile-raspi/

In the most basic case, I want to do exactly that with your tool.  BUT - my actual target is not supported by QEMU - their step #4 does not work for me. Instead I just jump directly to step 5 - copy(deploy) the application to RPI via some script and then run the application. Which I can do via gdb-remote and a gdb server.

NOTE: However my specific case my actual target is not an R-PI, it is an chip that is similar to the STM32 or ESP type chips (Note: for example google test runs on the ESP chips)

**Describe alternatives you've considered**
I am trying to find a solution like this.

**Additional context**

**Comment by matepek** [comment]
I'm not sure what you want.
Do you want to run you tests on the embedded system?
You can use [executionwrapper](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/test.advancedExecutables.md#executionwrapper)

**Comment by duaneellissd** [comment]
The execution wrapper is only part of this 
Being able to debug is also required

debug requires both copy image to the target ( on Linux this is SCP on embedded it is flashing the board )

then the next step is launching the debug server on the remote machine on Linux that is starting GDB remote on the target for an embedded system this launching something like open ocd on ether the local machine or the remote machine

then the gui needs to launch GDB locally and tell it to connect to either local host or the remote host 

then gdb loads (or flash loads the device)

**Comment by matepek** [comment]
For advanced debugging, one can use [testMate.cpp.debug.configTemplate](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md). There any custom task can be run. See [preLaunctask](https://code.visualstudio.com/docs/editor/debugging).

**Comment by matepek** [comment]
Assuming the doc covers your case I'm losing this
