### ISSUE TITLE
doctest group by suite

### ISSUE THREAD

**Issue by gruenedd** [matepek/vscode-catch2-test-adapter#391]
Using doctest and given

```cpp
TEST_SUITE("First")
{
  TEST_CASE("MyTest") { FAIL(""); }
}

TEST_SUITE("Second")
{
  TEST_CASE("MyTest") { FAIL(""); }
}
```

Testmate only shows "MyTest [Second]" (MyTest [First] is not shown)

I would expect that it automatically groups via suite and shows both unless grouping is defined otherwise.

```
First
`-- MyTest
Second
`-- MyTest
```
Even if this is not the default, how group suits (or other scoped constructs like fixtures and such)?

Cheers

**Comment by matepek** [comment]
<details>
<summary>Fixed in <b>v4.5.0</b>.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by matepek** [comment]
Harder than I thought. Have to revert it

**Comment by matepek** [comment]
doctest command line interface has some limitations... I'm not sure I can give a proper solution

**Comment by matepek** [comment]
should work now
