### ISSUE TITLE
Test executable does not find files in same directory

### ISSUE THREAD

**Issue by mkuehn94** [matepek/vscode-catch2-test-adapter#394]
**Checklist**

checked

**Describe the bug**

I have a single Googletest Executable under Windows. name it Test.exe. However It used various XML settings files and DLLs
in the same directory. It need those for initialization or it crashes. When I run a test, the executable crashes, when it searches for the 
XML files, however when i run the same with cmdline arguments copied to the console, everythings works fine. My assumtion is, that it is executed in another direcory, altough this is hard to debug.

I tried:
 -> setting the "cwd" of the childprocess to the correct path inside the spawn function
 ->using these settings:
`"testMate.cpp.test.advancedExecutables": [
        {
          "pattern": "Test.exe",
          "cwd": "C:\\Users\\me\\ExeDir",
        }
      ],`

it always finds all the tests and lists them correctly but fails while looking for the .xml files it needs. Is this an error on my side or known behaviour?

**To Reproduce**

Compile a googletest binary that looks parses xml settings files from the same folder, before it executes a test. Then load the executable into the extesion and run any test.

**Desktop**

- Extension Version: v4.5.1
- VS Code Version: 1.18.1
- Catch2 / Google Test / DOCTest Version: 1.11.0
- OS Type and Version: Microsoft Windows 10 Enterprise 10.0.19045 Build 19045
- Using remote-ssh/docker/wsl?: no

**Regression bug?**

seems not

**Log** (optional but recommended)

https://pastebin.com/macQhyVL

**Comment by matepek** [comment]
Hello,

`cwd` seems properly set. Are you sure that the environment variables are the same for command line and vscode?
You can see the vscode's envs in the log.

**Comment by mkuehn94** [comment]
thanks for your answer,
they are basically identical, except VSCode related vars. 
the only env var that is not present in VSCode is: 
PROMPT=$P$G
which should not change anything (i even checked by adding it)

However I assume this issue is not related to your extension but rather the configuration of the project.
I'll update this thread if I find the issue and it's relevant to the extension
