### ISSUE TITLE
Pass command line arguments to Googletest

### ISSUE THREAD

**Issue by appls** [matepek/vscode-catch2-test-adapter#395]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Description**
In my Googletest project I pass command line parameters to define a communication interface for testing.
I have not yet understood where I can set an argument (e.g. "-ComPort 3") in testMate.cpp.test.advancedExecutables to use it in the test application.

**Example.cpp:**
```
// ...
int main(int argc, char** argv) {
  int port{ 0 };
  std::vector<std::string> const vArgs{ argv + 1, argv + argc };
  for (auto const& it : vArgs) {
    if (it == "-ComPort") {
      port = std::stoi(*std::next(&it));
    }
  }
  //std::cout << "Port " << port << std::endl;
  //...
  return RUN_ALL_TESTS();
}
```
The test project is executed like: `.\Test.exe -ComPort 3`

**Describe the solution you'd like**
I would like to have a plain argument list that can be fillied in testMate.cpp.test.advancedExecutables.
E.g.:
```
"testMate.cpp.test.advancedExecutables": [
  {
    "argv": "-ComPort 3 -SomeMoreArg 42",
  }
]
```
Chances are high that I simply didn't find the right way to to pass the commandline arguments. Can you please give some advice?
Cheers,
Tobias

**Comment by mkuehn94** [comment]
I don't know if there is a VSCode argument for that, but you can compile the extensions and pass the arguments inside:
https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/framework/GoogleTest/GoogleTestExecutable.ts
_getRunParamsCommon

like:
`	execParams.push('-ComPort')
	execParams.push('3')
	execParams.push('-SomeMoreArg')
	execParams.push('43')`
	
that's how I do it, if there is a way to achieve this without recompiling the whole extension I would like to know as well

**Comment by matepek** [comment]
Sounds like you figured it out. 👍
