### ISSUE TITLE
Do your test exectuable depend on some dynamic library?  What if they do?

### ISSUE THREAD

**Issue by jandrewmc** [matepek/vscode-catch2-test-adapter#399]
I've seen this question asked in a few issues and it is listed on the support page.

My question to you is, what if my tests do depend on some dynamic library?  Will test mate never be able to pick it up?  Do I need to relocate the shared libraries?  Do I need to ensure the location of the shared libraries are in the PATH in the env section of advancedExecutables?

Thank you

**Comment by jandrewmc** [comment]
I finally found a solution.  I set the following in advancedExecutables:
`            "env": {
                "LD_LIBRARY_PATH": "${os_env:LD_LIBRARY_PATH}${osPathEnvSep}<PATH_TO_SHARED_LIBRARIES>"
            },
`
And all my tests showed up.  

Also, the path was set up as a global environment variable.  Does test mate use a clean environment?

**Comment by matepek** [comment]
> My question to you is, what if my tests do depend on some dynamic library?

As for every dynamically linked executable the dynamic libraries has to be accessible for the executable. This is true in general. There are several ways to do that, there are good articles about it.

Testmate envs from vscode which inherits them from the caller. That means the global envs usually available for testmate.
