### ISSUE TITLE
Add `ctest` parsing

### ISSUE THREAD

**Issue by zanaviska** [matepek/vscode-catch2-test-adapter#401]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I have problem working with your extension with my everyday project. In most cases it fails to load test executable that I mostly work with. Our development process heavily relies on cmake. That is why ctest is able to find all our test executables without any problems. Here on screen you can find tests list that extension generated and `ctest --show-only` output. Only 6 test out of 9 were in common. 
![зображення](https://github.com/matepek/vscode-catch2-test-adapter/assets/31745527/a5daee09-fb81-4c67-a48e-3ec0c697e6a8)

**Describe the solution you'd like**
So my proposal is to add cmake integration
1) Check for some flag in settings.json(for example "testMate.useCmake")
2) check if workspace contain cmakelists.txt file
3) fetch from cmake-tools extension path to build directory
4) execute command ctest --show-only=json-v1 and parse output to find all tests and executables
5) integrate those results into ui

**Describe alternatives you've considered**
I considered developing my own [extension](https://github.com/zanaviska/ctest-test-explorer), but there is a tonn of things that I'd like to add to my extension. So I decided that it would be easier and faster to add such approach to existing solution.
P.S. I am not trying to promote my extension. As soon as I find existing solution, I will archive my extension and move to existing solution

**Additional information**
If needed I will be able to help with developing such functionality

**Comment by matepek** [comment]
Hello,

I have considered this approach before and I decided not to support it for several reasons. It is a different tool for different purpose. The reason why you cannot run your executables with this extension because of the cmake magic happening under the hood.

I believe you can set this extension up with config variables  `${config:<varname>}` such as [${config:buildDirectory}](https://github.com/microsoft/vscode-cmake-tools/blob/main/package.json#L1669), etc..

**Comment by matepek** [comment]
A lot of key features could not be supported.
