### ISSUE TITLE
'Unexpected error from debug' when debugging googletest test case using 'Native Debug' extension

### ISSUE THREAD

**Issue by w0utert** [matepek/vscode-catch2-test-adapter#405]
When debugging a test case detected by TestMate while the 'Native Debug' WebFreak extension is installed, TestMate will pop up a notification with the following error message:

```Unexpected error from debug: Error: Abandoning waiting for termination of debug session```

Interestingly after just waiting a bit the test case does start and the debugger will stop on the breakpoint I set. So this error message is not really breaking but mostly a nuisance

**To Reproduce**

- Install 'Native Debug' extension and configure it to use GDB (haven't tested with LLDB)
- Install TestMate
- Open project that uses google-test and make sure TestMate finds some test cases
- In the list of detected tests in the 'Testing' panel, pick one to debug and click the 'Debug Test' button

The test will start and (in my case) open the notification with the error message. This test binary is quite large and has a lot of tests, so it could be the case that it is hitting a timeout that may not happen for smaller test binaries.

- Extension Version: v4.6.2
- VS Code Version: 1.84.1
- Catch2 / Google Test / DOCTest Version: 1.11.0
- OS Type and Version: Ubuntu 22.04
- Using remote-ssh/docker/wsl?: no

**Log file**
I have a log file for a failing run but I cannot attach it verbatim because it seems to be full of potentially sensitive data (detected test case name, source file names, etc). If needed I can snip out and redact the relevant parts (the file is ~48K lines long though so it's hard for me to figure out what the interesting bits for this issue are).

**Comment by matepek** [comment]
fixed. thanks for the report
