### ISSUE TITLE
Add access to gdb command to modify arguments

### ISSUE THREAD

**Issue by jnz86** [matepek/vscode-catch2-test-adapter#407]
I have debugging working, but as soon as I click it, it runs through and exits with `status 0` if I forget to put a breakpoint in. I'd like to automatically halt at `test()` or `main()`. 

I'm using Linux, remote dev, gdb, cpptools. 

I want to add this to GDB before it is executed: ` --eval-command=\"break main\"`

This is my settings.json entry:
```
    "testMate.cpp.debug.configTemplate": {
        "type": "cppvsdbg",
        "linux": { "type": "cppdbg", "MIMode": "gdb" },
        "program": "${exec}",
        "args": "${argsArray}",
        "cwd": "${cwd}",
        "env": "${envObj}",
        "environment": "${envObjArray}",
        "sourceFileMap": "${sourceFileMapObj}",
      }
```

This likely already exists, I just don't see it. If it doesn't, it would be helpful to have a little more access to the command-line of the debugger.

**Comment by matepek** [comment]
`configTemplate` as its name says its a template for the debug adapter. You can use any fields which are supported by the `cppvsdbg`. Therefore no development is needed here. I'm sure they already support this. If not, ask them.

**Comment by matepek** [comment]
https://code.visualstudio.com/docs/cpp/launch-json-reference#_stopatentry

**Comment by jnz86** [comment]
I see the difference here. 

I don't have a launch.json entry defined. So I didn't look at the launch.json commands. I'm using your extension settings like:

```
    "testMate.cpp.debug.configTemplate": {
        "type": "cppvsdbg",
        "linux": { "type": "cppdbg", "MIMode": "gdb" },
        "program": "${exec}",
        "args": "${argsArray}",
        "cwd": "${cwd}",
        "env": "${envObj}",
        "environment": "${envObjArray}",
        "sourceFileMap": "${sourceFileMapObj}",
      }
```

Which yea, now that I look at it... Seems like you're just passing that straight to launch.json, so this all makes sense. I'm not sure how I would have known you're just passing those in instead of using a similar format for your own code and practice.

But, you're right. Adding `"stopAtEntry": true,` to that section of my settings worked exactly as intended. Thanks.
