### ISSUE TITLE
Status bar name is just "Extension status", and not ex. "TestMate C++". This makes it hard to find it if you want to hide the status.

### ISSUE THREAD

**Issue by nfogh** [matepek/vscode-catch2-test-adapter#409]
I was trying to clean up my statusbar, and I noticed that the TestMate label is just named "Extension Status". See the attached picture.

![testmate](https://github.com/matepek/vscode-catch2-test-adapter/assets/17196968/b4cf51fd-c192-4dbd-a927-d65312d64396)

This is a bit confusing. Please give it a better name.

**To Reproduce**

Right click on the status bar, and disable "Extension status". This removes the "TestMate C++" label

- Extension Version: v4.6.3
- VS Code Version: 1.84.2

**Comment by matepek** [comment]
I think it is a `vscode` issue, not related to this extension. Feel free to report it to them.
