### ISSUE TITLE
Improve performance by allowing "Files: exclude" rules when collecting test binaries

### ISSUE THREAD

**Issue by kmARC** [matepek/vscode-catch2-test-adapter#414]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
We are using `advancedExecutables` in a large bazel project (see context 1.) and collect all test binaries that are currently built (context 2.) in a subdirectory of the git repositories. Since TestMate [invokes `findFiles` with `null`](https://github.com/matepek/vscode-catch2-test-adapter/blob/17cae68227125af461dcd36fd6264f26b7fabc6e/src/util/FSWatcher.ts#L97) as its `exclude?` parameter (context 3.), during test detection, an `rg` process is invoked (context 4.) which takes up a lot of resources and time to find the test binaries.

Unfortunately, on our project, we are talking about 10-20 seconds each time, on a box of 100CPU cores per user. This could be done in ~50ms.

**Describe the solution you'd like**
There are two ways we could work with:

1. Set `findFiles`'s `exclude?` parameter to `undefined` instead of `null` ([here](https://github.com/matepek/vscode-catch2-test-adapter/blob/17cae68227125af461dcd36fd6264f26b7fabc6e/src/util/FSWatcher.ts#L97)) and let users configure their exclusion rules. 
2. Introduce a boolean configuration setting to TestMate which lets the user choose if they want to "reset" the VSCode exclusion rules.

**Describe alternatives you've considered**
1. I already forked the plugin and replaced `null` to `undefined`. Works perfectly.
2. Moving our symlinks out of `workspaceFolder`, so that the [`GazeWrapper` ](https://github.com/matepek/vscode-catch2-test-adapter/blob/17cae68227125af461dcd36fd6264f26b7fabc6e/src/ConfigOfExecGroup.ts#L79-L81) implementation finds the symlinks. Works perfectly too.

Both of these alternatives resulted in <50ms spent on collecting tests binaries, instead of 10-20 seconds.

**Additional context**
1. Bazel creates (at least) four symlinked directories in the workspaceFolder that point to its CAS for cached build results. These directories (all in the form of `bazel-*/`) might contain millions of files: think of it as `node_modules`, `build` and `tmp` together. When TestMate invokes `findFiles(..., null, ...)`, VS Code runs `rg` on those million tiny files, and tries to glob-match (`-g`) the `pattern` that is configured for `advancedExecutables`
2. We have around multiple thousands of test binaries, deeply buried somewhere under `bazel-out`; we symlink each of these under a subdirectory (`./support/vscode/testmate/...`) and point testmate's `pattern` to find them. It works like a charm, testmate only traverses a handful of files, a good 10-100 or so, depending on how many a developer built on their local environment. Note that we even symlink the unbuilt binaries (rresulting in broken symlinks) but TestMate is happily ignoring those, which is exactly what we want. 
4. According to the [VSCode API](https://code.visualstudio.com/api/references/vscode-api), `findFiles`'s `exclude?` parameter can be used as follows:
    > A [glob pattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) that defines files and folders to exclude. The glob pattern will be matched against the file paths of resulting matches relative to their workspace. When `undefined`, default file-excludes (e.g. the `files.exclude`-setting but not `search.exclude`) will apply. When `null`, no excludes will apply.

    Note that `.gitignore`d files are still included in the search.
    
    I believe TestMate's behavior here is too intrusive; VSCode has two "levels" of excluding files: "Files: exclude" and "Search: exclude"; the API would let us work with the intention of "when an extension uses the API for _searching_, we want it to find certain files, like the ones under  `bazel-out`, but if there are excluded files in a project for whatever user-defined reason, we respect that". However, TestMate currently chooses to ignore the user's wish to use exclusions.

5. VS Code [uses ripgrep internally with its `--no-config` option](https://github.com/Microsoft/vscode/issues/49283)

**Comment by matepek** [comment]
Loved your detailed feature request.

Seems to me they improved a lot on the documentation and the features.

I was checking the `files.watcherExclude` option. 

> Configure paths or [glob patterns](vscode-file://vscode app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) to exclude from file watching. Paths can either be relative to the watched folder or absolute. Glob patterns are matched relative from the watched folder. When you experience the file watcher process consuming a lot of CPU, make sure to exclude large folders that are of less interest (such as build output folders).

How would `findFiles(..., watcherExclude, ...)` work for you?
The `vscode.workspace.createFileSystemWatcher` has been already respecting it so regardless we find those executables change events won't be coming.

**Comment by kmARC** [comment]
Thanks! :-)

I tried `vscode.workspace.getConfiguration("files").get("watcherExclude")`, and indeed it works like a charm!

We'd be super happy if this got fixed upstream.

**Comment by matepek** [comment]
<details>
<summary>Fixed in <b>v4.8.0</b>.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by matepek** [comment]
CI closed it but this change is a bit tricky, I reopen it until verification.

- what exactly the value of `vscode.workspace.getConfiguration("files").get("watcherExclude")` ?
- what is a typical path of your test exec?
- where are the files which meant to be ignored?

**Comment by kmARC** [comment]
Overnight the plugin got automagically upgraded to `4.8.0`, and this immediately started to work, possible for everyone, super fast!!! Thank you!

> what exactly the value of vscode.workspace.getConfiguration("files").get("watcherExclude") ?

besides the default nodejs-related entries, I added

```gitignore
bazel-*/**
external/**
```

Works with this, either added here or simply under `files.exclude`.

> what is a typical path of your test exec?

All test executables are under `bazel-bin/`, on a (sometimes deep) path which is the same as the git-committed Bazel BUILD file defines the binary. Example:

* If there is a `cc_test` called MyTest defined in `long/path/for/my/test/BUILD.bazel`
* Then the `MyTest` GoogleTest ELF binary will reside in  `bazel-bin/long/path/for/my/test/MyTest`
* And it is symlinked as `support/vscode/testmate/long/path/for/my/test/MyTest`

Under `support/vscode/testmate` only these symlinks exist, none of the unrelated Bazel stuff. 

> where are the files which meant to be ignored?

Under `bazel-bin/` there are many more files, these must be excluded. (And bazel brings in some other symlinked directories like `bazel-out`, `bazel-gitreponame`, `bazel-testlogs`. Just to see the difference it makes for us, an example from our repo:

```sh
# All the Bazel overhead:
± find bazel-bin/ | wc -l
367510

# Our trimmed down symlinks
± find support/vscode/testmate | wc -l
7996

# A realistic developer environment, with actual non-broken symlinks (tests that are built):
± find support/vscode/testmate -type l -not -xtype l | wc -l
10
```

**Comment by kmARC** [comment]
Additional note:

* `bazel-out`, `bazel-bin`, and the likes are actually symlinks to `$USER/.cache/_bazel/...`; they are created by Bazel.

Somewhat unrelated, but now that I understand more correctly that this is an actual FS **Watcher**, it's meant to watch these binaries and once they are updated (by a Bazel build recompiling them), TestMate supposedly recognizes them...?

If this is the case, this actually never worked for us.

**Comment by matepek** [comment]
There is a `FSWatcher` and a `findFiles`. findFiles makes sure that already exiting files/executables are listed (if the testing framework is supported). The `FSWatcher` makes sure that new executables are added, changed ones are reloaded.

> If this is the case, this actually never worked for us.

I heard from other users that symlinks are not followed by the watchers.

Now that you excluded

I'm not familiar with bazel build system and other users have issues too. It might worth to look into it a bit sometime.
As far as my understanding goes is that bazel produces the output to `$USER/.cache/_bazel/...` and the workspace folder only contains symlinks to the actual folders (as yourself explained too).
Symlinks broke the `FSWatcher` but listing works (two different endpoint and functionality).
This could be bypassed with some checking and `GazeWatcher` could operate nicely outside of workspace folder but I'm concerned that what is happening when rebuild is done. Ex. does bazel keep the old binaries and rewrites the symlink, etc.. I can imagine a lot of magic. 

(If that's a the case you can try adding the symlink to `dependsOn`. That would trigger reloads.)

I will have to dig deeper of bazel. [This article](https://bazel.build/remote/output-directories) I found just now.
I will need some time to play around.

One more question: what is your `pattern`?

**Comment by kmARC** [comment]
I did some more experimentation, especially with moving my symlinks (the ones that I create for testmate to be recognized) "close" to the bazel caches, so that there is no file system boundary crossing (our dev envs have ~/.cache  mounted separately)

Although then it's the GazeWrapper that is being used, however, automated test detection/reload works. The reason for that I think, is that once the symlinks are resolved (by Gaze, vscode, the kernel, or whatever layer), the inode will still be on the same filesystem, and thus kernel's inotify would cover it. 

Now I am on mobile, but will post an update about my findings next week.

**Comment by matepek** [comment]
I had to realise changing the default behaviour was a mistake. `v4.10.0` reverts `v4.8.0`: `files.watcherExclude` is not applied by default anymore.
Added new setting: `testMate.test.advancedExecutables` -> `exclude` which can be `"files.watcherExclude"` or any setting path.

**Comment by matepek** [comment]
How do you specify the `cwd` for bazel?

**Comment by kmARC** [comment]
> How do you specify the cwd for bazel?

We use `advancedExecutables`, and have a shell script for intercepting TestMate's logic (`testmate-wrapper.sh`) around detecting tests. It's quite sophisticated as in setting up some paths, conditionally analyzing the test binary (`readelf`) and eventually, for test invocation, dispatching to Bazel itself (so that tests are rebuilt on-demand).

Bazel's approach of having many (as in, thousands of) test binaries makes it a bit hard to work with this plugin; we had to implement our per-file "test detection" mechanism, which is also done through the same wrapper, but what it really does, is compiling the particular file's nearest Bazel target. The massive amount of test binaries also caused performance problems, like this very report.

We don't like this too much. In fact, we are looking into improving the UX by trying to parse the test .cpp files for GoogleTests so that our users don't have to compile them. If you are interested in this, we should think about some kind of collaboration.

**Comment by matepek** [comment]
Hello,
FYI, [New release](https://github.com/matepek/vscode-catch2-test-adapter/blob/v4.20.0/CHANGELOG.md) contains some symlink resolution logic.
