### ISSUE TITLE
Add custom file extension pre-filter

### ISSUE THREAD

**Issue by Abasz** [matepek/vscode-catch2-test-adapter#415]
**Checklist**í

- [ x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Currently on windows anything that "NOT ends with .exe, .cmd or .bat." will be filtered out.

My compiled test files are ending with an `.out` extension. This is due to other external requirements and cannot be changed, so I cannot have .exe or any other extension that would not get filtered out.

**Describe the solution you'd like**
I would like to have the option to set a regex matcher (or specify additional extension) which are not filtered out. 

**Describe alternatives you've considered**
Currently I edit the main.js file manually and I add the `.out` text it to `l=new Set([".exe",".cmd",".bat"])` (which is basically the `win32NativeExecutableExtensionFilter` variable in the source code)

**Comment by matepek** [comment]
<details>
<summary>Fixed in <b>v4.8.3</b>.</summary>

This issue was mentioned in [CHANGELOG.md](./CHANGELOG.md) under a released entry so it is assumed to be fixed.
User verifications are always welcome.
</details>

**Comment by Abasz** [comment]
Tested and works fine. I appreciate your help!
