### ISSUE TITLE
The ambiguous explanation of the test.parallelExecutionLimit and the test.parallelExecutionOfExecutableLimit

### ISSUE THREAD

**Issue by suikan4github** [matepek/vscode-catch2-test-adapter#416]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**
This is considered a documentation problem. 

The explanation of the test.parallelExecutionLimit and the test.parallelExecutionOfExecutableLimit are ambiguous. In other words, the difference of both settings is not clear.  

In the [README](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/README.md#configuration), the explanation is like this : 

testMate.cpp.___ | Description
-- | --
test.parallelExecutionLimit | Maximizes the number of the parallel test executions. 
test.parallelExecutionOfExecutableLimit | Maximizes the number of the parallel execution of executables. 

Sorry to say, I can not understand what that means. I have read the source, too. But I could not understand  ( I am not familiar with the typescript ). 

I guess, these might be re-written as : 
testMate.cpp.___ | Description
-- | --
test.parallelExecutionLimit | Maximum parallel execution number of a single executable. 
test.parallelExecutionOfExecutableLimit |  Maximum total parallel execution number of multiple executables. 

To test my guess, I need a multiple executable test set. But I don't have it. So, this is just a guess. 

I appreciate it if you made it clear. 

**To Reproduce**
No.  This is considered a documentation problem.

**Screenshots** (optional)
This is a screenshot of the  [README](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/README.md#configuration).
![image](https://github.com/matepek/vscode-catch2-test-adapter/assets/26223147/3fde4d3b-2053-4b42-9bf4-d1a396c56649)

**Desktop**

- Extension Version: 4.8.0
- VS Code Version: 1.85.1
- Google Test  Version: 1.10.0
- OS Type and Version: Windows 11 
- Using wsl?: Yes.

**Regression bug?**
No.

**Comment by matepek** [comment]
Hello,

Sure, let's discuss it. I'm happy if we can improve this.

Let me ask you a question just to make sure we have the same understanding on some basics.

What is a `test` and what is an `executable` and what is the relationship between them for you?

**Comment by suikan4github** [comment]
Hi. 

I am a GoogleTest user. So, 

- Test: A unit test. 
- Executables: An executable file on Windows or Linux. 

In my case, an executable file contains multiple unit tests.

**Comment by Ext3h** [comment]
> test.parallelExecutionLimit: Maximizes the number of the parallel test executions.

Maximum number of parallel executions of the same test executable. This does not further distinguish between different test cases or permutations / iterations of the same test case.

Limit this if you have resources which are instanced only a limited number of times per test executable.

Warning: There is no concept of  resource groups spanning multiple executables!

> test.parallelExecutionOfExecutableLimit: Maximizes the number of the parallel execution of executables.

(Global) total number of parallel executions of any test executable.

This is the number of processes which will be running concurrently at peak.

**Comment by suikan4github** [comment]
Thank you very much. This is clear and easy to understand.

**Comment by matepek** [comment]
This is not correct. Ah, I definitely should clear this up..

## `test.parallelExecutionLimit`

Maximum parallel run of tasks. Tasks are *'running a set of tests'*, *'test executable discovery'* and *'reload of the executable's test list'*. NOTE: If your executables depend on the **same resource** exclusively then this **could cause a problem**. 

## `test.parallelExecutionOfExecutableLimit`

Maximum number of execution of the same executable. With this config it can be allowed that one executable is running at the same time as multiple processes and those processes *'running a set of tests'* parallel. Useful if one executable has a lot of tests which can be run parallel. It won't have effect unless the `test.parallelExecutionLimit` is adjusted too. To enable this just for specific executables use the `testMate.cpp.test.advancedExecutables` -> `parallelizationLimit`. NOTE: if your **test cases** depend on the **same resource** exclusively then this **could cause a problem**.


I hope it's clear now. I will update the docs
