### ISSUE TITLE
runTask always reporting "Task not found"

### ISSUE THREAD

**Issue by Ext3h** [matepek/vscode-catch2-test-adapter#418]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

***Expected behavior***
- The configured task is executed before test execution.
- If the task has failed, the task ***name*** is included in the error message.

***Actual behavior***
- According to the log, the task is found and run.
- Actually the task has ***not*** been run.
- Instead a "Task not found" is reported as an error.
- The error message does not name the task that has failed.

**To Reproduce**

I have a task configured in `tasks.json` in my VSCode user directory:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cmake",
			"label": "build_all",
			"command": "build",
			"targets": [
				"all"
			],
			"preset": "${command:cmake.activeBuildPresetName}",
			"group": "build",
			"problemMatcher": [],
			"detail": "CMake template build task"
		}
	]
}
```

I can run this task via `Tasks: Run Task` by the name `build_all` - so I'm confident that the task exists and it can run without errors.

I have configured TestMate to run this task:

```json
    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern":  "${command:cmake.buildDirectory}/**/test*",
            "runTask": {
                "before": [
                    "build_all"
                ]
            }
        }
    ]
```

1. Go to Test Explorer
2. Click on "Debug" Icon next to any test
3. See error

**Screenshots** (optional)

![image](https://github.com/matepek/vscode-catch2-test-adapter/assets/7760870/8454582a-111e-4903-b677-02a30b51c3a9)

**Desktop**

- Extension Version: v4.8.0
- VS Code Version: 1.85.2
- Catch2 / Google Test / DOCTest Version: Catch2
- OS Type and Version: Windows 10
- Using remote-ssh/docker/wsl?: None

**Log**

testmate.log redacted by matepek

**Comment by matepek** [comment]
I think the issue is related to this extension. This variable resolve to empty: `"preset": "${command:cmake.activeBuildPresetName}",`. 
And this causing issue.

**Comment by matepek** [comment]
Sorry but I'm not familiar of cmake extension.
