### ISSUE TITLE
Don't re-indent `std::cout` output

### ISSUE THREAD

**Issue by pweiskircher** [matepek/vscode-catch2-test-adapter#421]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
When I output for example JSON using `std::cout` in a test for debugging purposes it re-indents the JSON making it pretty hard to read.

**Describe the solution you'd like**
Be able to not re-indent the output.

**Additional context**
For example (only pasting part of the output):
<img width="426" alt="Screenshot 2024-01-31 at 3 52 10 PM" src="https://github.com/matepek/vscode-catch2-test-adapter/assets/1521642/d73ffc16-daa8-4574-affd-574b196d9b3d">

When I use the debugger, it looks like this:
<img width="394" alt="Screenshot 2024-01-31 at 3 53 01 PM" src="https://github.com/matepek/vscode-catch2-test-adapter/assets/1521642/532cd0bf-d0db-4985-818e-7e54828814b3">

Not sure if this is something you'd consider, but I figured it's worth a try. Not too big of a problem because I usually don't debug things like this anyway.

**Comment by matepek** [comment]
It should indent it and it works fine for me. I was not able to reproduce. 
Please open a BUG. 🙏
