### ISSUE TITLE
[Catch2] Custom main file not being picked up

### ISSUE THREAD

**Issue by ricardomatias** [matepek/vscode-catch2-test-adapter#422]
**Checklist**

- [x ] The issue is about this extension and NOT about a fork.
- [ x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x ] The latest version of the extension was used.
- [x ] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x ] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

I've got a working cmake configuration that allows me to use [ApprovalTests.cpp](https://github.com/approvals/ApprovalTests.cpp) with catch2. It does so by creating an executable for each file depending **on a custom main.cpp** file and then the test file. This doesn't seem to work with Testmate, the test case where ApprovalTests is used exits with a FatalErrorCondition which I've traced to the ApprovalTests library not being initialized (which happens on the custom main_config.cpp file). I've added the "_config" to the pattern finding configuration but to no avail. Am I doing something wrong?

**Desktop**

- Extension Version: 4.8.3
- VS Code Version: 1.86.0
- Catch2 / Google Test / DOCTest Version:  3.3.2
- OS Type and Version: Mac OS 13.6.3
- Using remote-ssh/docker/wsl?: No

**Comment by matepek** [comment]
Can you run your exec from command line?
try to check the logs.

**Comment by ricardomatias** [comment]
@matepek I ran from the command line and the error was the same, so this is not a problem with this extension. Thanks for the help.
