### ISSUE TITLE
[Abritrary Test grouping] : allow to make custom groups based on several config for advancedExecutables

### ISSUE THREAD

**Issue by bebenlebricolo** [matepek/vscode-catch2-test-adapter#432]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
I wonder if that would be possible to abitrarily group tests in the test explorer.
This is available with regex, and labels and so on ; but I have the following use case where it might be nice to have a top-grouping node : I'm sometimes building my projects both in `Debug` and `Release` mode.
My current test discovery config looks like this : 
```json
    "testMate.cpp.test.advancedExecutables": [
        {
            "name": "[Dbg] : ${filename}",
            "pattern": "build/**/Debug/*",
            "cwd": "${relDirpath}",
        },
        {
            "name": "[Rls] : ${filename}",
            "pattern": "build/**/Release/*",
            "cwd": "${relDirpath}"
        }
    ]
```
It gives me a flat list with both [Rls] and [Dbg] tests at the same level of the data tree, like (which is fine as I can select which test I want to run, and I can still debug the Debug version if need be.)
```
* [Rls] test 1
* [Rls] test 2
* [Rls] test 3
* [Dbg] test 1
* [Dbg] test 2
* [Dbg] test 3
```

**Describe the solution you'd like**
It would be very nice to have the possibility to group them like that :
```
* [Release]   <───┐
  * test 1        │
  * test 2        │
  * test 3        │
                  │
* [Debug]     <───┴─── Both "root configuration nodes" are collapsible
  * test 1
  * test 2
  * test 3
```
I don't know if such a thing is already possible with some clever configuration?

Thanks for your great work, this extension is a very handy tool to have !

**Comment by matepek** [comment]
Hello, 
`4.12` will have new grouping `groupByLabel`. See the  changelog for example.
