### ISSUE TITLE
Continuous run only selected tests

### ISSUE THREAD

**Issue by tysolov** [matepek/vscode-catch2-test-adapter#435]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
Although the UI supports selecting individual tests to autorun, you must select the topmost tree element to actually run the tests.

Interestingly, the Test Results pane does show a new "Test run at <date>, <time>" entry, but with a gray circle (no fail/success symbol); right-clicking to see results reveals a message: "The test run did not record any output."  This is not the case when the top-most tree element is selected for autorun.

**Describe the solution you'd like**
I'd like the selected tests to run.

**Describe alternatives you've considered**
None.

**Additional context**
Looks like you opened an issue at vscode repo that's since been closed here: https://github.com/microsoft/vscode/issues/178973, but it doesn't seem to have been picked up here (unless I'm missing something). 

Tested with:
- vscode 1.81.0 with c++ testmate 4.5.2 
- vscode 1.85.1 with c++ testmate 4.12.0

**Comment by matepek** [comment]
Hello,
This extension does not have much UI components merely implements an interface for vscode.
I'm afraid it won't be done at this side. You can talk with vscode devs and link this issue for reference. ^^

**Comment by elad-eyal-ns** [comment]
@tysolov did this ever resolve for you? It seems to be that the vscode APIs are in place but the extension doesn't run the correct things? happens to me also

**Comment by csorvagep** [comment]
@elad-eyal-ns, I have the same issue for a long time. Today I checked the logs and the only difference (expect the output of the started process) is this:
`[2025-02-10 07:34:34.579] [INFO] skipping because it is under "/CMakeFiles/" <obj file path>`
Can this be the cause why is it ignored?

**Comment by elad-eyal-ns** [comment]
@csorvagep I don't see such a log message. I guess you should not be monitoring a file under CMakeFiles anyway.

My latest finding is that when  `touch` works (triggeres the tests) but updating it with `ninja` does not

**Comment by csorvagep** [comment]
Then my problem might be a different issue. If I touch the executable or do a rebuild with cmake, the extension does a new test discovery, but no tests are run. Only runs all the tests if I select the executable. 
If it's unrelated, I'll create a new issue.

**Comment by elad-eyal-ns** [comment]
I think you get `The test run did not record any output` when trying to run the test executable in the state where its size is 0. So this maybe happens when trying to run the test too early. I finally seem to manage to resolve it by specifying a regex in `waitForBuildProcess`

**Comment by csorvagep** [comment]
I tried this, but did not help. The extension finds no build process to wait for.

**Comment by matepek** [comment]
Maybe related: https://github.com/microsoft/vscode/issues/242148

**Comment by csorvagep** [comment]
It works now for me, thanks!
