### ISSUE TITLE
Swettings for test discovery environment

### ISSUE THREAD

**Issue by alex-the-new-guy** [matepek/vscode-catch2-test-adapter#438]
**Checklist**

- [X] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

This is kind of an edge-case, but sometimes tests need environment variables (in my case, specifically, PATH) for test executables to launch properly and thus for individual tests inside of them to be discovered. In my case specifically, test executables need DLLs which can't be located without setting up the environment.

So the output is:
![image](https://github.com/matepek/vscode-catch2-test-adapter/assets/113210169/405d2e65-9b59-4151-b1c7-383947a6b851)

Instead of:
![image](https://github.com/matepek/vscode-catch2-test-adapter/assets/113210169/5b5bf5c8-b69e-4977-aa15-e359efa2f241)

While there are settings which adjust the environment they're running in, there aren't any settings to adjust the environment in which test discovery is happening. 

A more or less ideal solution would be a similar setting to configTemplate but for test discovery. Or just PATH or something. 

A sort of hacky fix is to edit the PATH of the environment VSCode is running in, but that brings all sorts of problems of the "I have multiple versions of the same compiler installed and they all are in there, so who knows what is actually compiling my program" variety.

**Comment by matepek** [comment]
Hello Alex,
I believe it has been supported already. Check the advancedExecutables.

**Comment by alex-the-new-guy** [comment]
@matepek 

This works, thanks for the help.
But:

- "env" affects test discovery for advanced executables and not for regular ones. I guess it's sort of counter-intuitive.
- After fairly carefully reading advancedExecutables documentation, nowhere it is stated, this setting affects executable discovery. I think, clarification is needed.

**Comment by matepek** [comment]
Regular ones? Wdym?

If you think about discovery and running tests are the same from the perspective of loading DLLs. (Exception exists but rare and not interesting for us)

**Comment by alex-the-new-guy** [comment]
>regular ones

To my understanding, the objects in `advancedExecutables` array have the same structure as the `configTemplate` object in settings.json.
If custom environment specified in `configTemplate`, it is apparently not used for test discovery, while `env` field in advancedExecutables is

Being more specific:

Scenario 1:
---
`settings.json`
```
    "testMate.cpp.debug.configTemplate": {
        "type": "lldb",
        "request": "launch",
        "program": "${exec}",
        "cwd": "${cwd}",
        "args": "${argsArray}",
        "env": {
            "path": "C:/devel/tools/msys2/ucrt64/bin;"
        },
        "environment": "${envObjArray}",
        "sourceFileMap": "${sourceFileMapObj}",
        "preLaunchTask": "Cmake clean reconfigure + rebuild Interface tests"
    },

    // "testMate.cpp.test.advancedExecutables": [
    //     {
    //         "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*.exe",
    //         "env": {
    //             "PATH": "C:/devel/tools/msys2/ucrt64/bin;"
    //         },
    //     }
    // ],
```
result:
![image](https://private-user-images.githubusercontent.com/113210169/344111726-405d2e65-9b59-4151-b1c7-383947a6b851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODUzMTgsIm5iZiI6MTcxOTU4NTAxOCwicGF0aCI6Ii8xMTMyMTAxNjkvMzQ0MTExNzI2LTQwNWQyZTY1LTliNTktNDE1MS1iMWM3LTM4Mzk0N2E2Yjg1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxNDMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGRlY2FlNmFkZWQxMjJiN2M5ZGI1MGYzNGE1Mzc0MzJhNDI1YTZlNTEwY2Y1NzI4ZDZmNTJlZGFlNTJhYWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ctwpJrLz1bkMAOpFmm3N1UAXZ26y4vDaDj5EfwBJ2WI)

Scenario 2:
---
`settings.json`
```
    "testMate.cpp.debug.configTemplate": {
        "type": "lldb",
        "request": "launch",
        "program": "${exec}",
        "cwd": "${cwd}",
        "args": "${argsArray}",
        "env": {
            "path": "C:/devel/tools/msys2/ucrt64/bin;"
        },
        "environment": "${envObjArray}",
        "sourceFileMap": "${sourceFileMapObj}",
        "preLaunchTask": "Cmake clean reconfigure + rebuild Interface tests"
    },

    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*.exe",
            "env": {
                "PATH": "C:/devel/tools/msys2/ucrt64/bin;"
            },
        }
    ],
```
result:
![image](https://private-user-images.githubusercontent.com/113210169/344115521-5b5bf5c8-b69e-4977-aa15-e359efa2f241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODUzMTgsIm5iZiI6MTcxOTU4NTAxOCwicGF0aCI6Ii8xMTMyMTAxNjkvMzQ0MTE1NTIxLTViNWJmNWM4LWI2OWUtNDk3Ny1hYTE1LWUzNTllZmEyZjI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxNDMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjNjNmI0ZTY0MDViNTMxMTg2MjFkN2MxN2I0YTE0ZGZjNWVlNWEzNzZjMTZjOThiY2ExN2JiOTcyNDFkMGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6HksgUVnSj-SctkVC3le8uBt7EafLAalGoyv5rFvqY)

Now looks more like a bug. I hope this is more helpful.

**Comment by matepek** [comment]
I can’t see the results pictures for some reason, but I can tell that config template is using the env from the advanced executable by design and not the other way around. One should specify the environment variables in the advanced executable and just reference it with the variable in the debug config template

**Comment by alex-the-new-guy** [comment]
Pictures are the same as comment #1, didn't want to reupload so copy-pasted the links. Updated now.

If you have a Win test machine, here is a repo where I've tried to isolate the issue:
https://github.com/alex-the-new-guy/testmate_env_test_repo

Probably should also build on Linux or whatever with some settings tweaking.
