### ISSUE TITLE
`executionWrapper` doesn't support having `${cmd}` in path

### ISSUE THREAD

**Issue by bwrsandman** [matepek/vscode-catch2-test-adapter#441]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

This is half a bug half feature request.
My usecase is this: I have an API that I test with GTest and multiple drivers that implement the api. The tests run against the API and not the drivers directly. I have gtest command line arguments but also I have `--driver` that gets piped into the initialization of the api.

The gtest runner in Visual Studio can do this with `Additional test execution parameters`.
Looking at the documentation, it seemed that `executionWrapper` could do this if I configured it like so:

```json
"testMate.cpp.test.advancedExecutables": [
  {
    "name": "${filename} [driver=APPLE1]",
    "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
    "executionWrapper": {
        "path": "${cmd}",
        "args": [ "${argsFlat}", "--driver", "APPLE1" ]
    }
  },
  {
    "name": "${filename} [driver=APPLE2]",
    "pattern": "{build,Build,BUILD,out,Out,OUT}/**/*{test,Test,TEST}*",
    "executionWrapper": {
        "path": "${cmd}",
        "args": [ "${argsFlat}", "--driver", "APPLE2" ]
    }
  }
]
```

There are two issues as far as I can tell:
1. The advanced executable shows up only once (if it were env, it would be twice).
2. Running the executable does not send the driver.

I'm not very familiar with javascript but I tried debugging it and I found the following:
1. There's a check in the spawner that looks for `${cmd}` in the `args`. In this case it won't find it so it errors out. This is easily fixed by also checking `path`.
2. Eventually, it will run `path/to/${cmd} --help` but it doesn't expand `${cmd}` to the real value. I guess this can be fixed with a getter for the command.

**Alternatives and why I can't use them**
* Using env: some of my drivers are on platforms that gtest supports but they don't support environment variables
* Using a config file: Same as env, some patforms don't have filesystem support from gtest
* Splitting off into one test per driver: This could work but it's a hassle and would make the project much more difficult to maintain.
* Using a `.bat`/`.sh` file to inject the driver and then call the test. I tried this and it would work for making `*Tests.bat` files show up in the test explorer but when running I would get errors about command line length. Using a `Tests.ps1` file would not show up in the explorer.

**To Reproduce**
1. Go to settings.json
2. Add an `executionWrapper` in `testMate.cpp.test.advancedExecutables`. The `cmd` must be in `path` and not in `args`. The most simple case would be this
```json
    "executionWrapper": {
        "path": "${cmd}",
        "args": [ "${argsFlat}" ]
    }
```

**Desktop**

- Extension Version: [4.12.0](https://github.com/matepek/vscode-catch2-test-adapter/releases/tag/v4.12.0)
- VS Code Version: 1.92
- Catch2 / Google Test / DOCTest Version: gtest from this repo
- OS Type and Version: MacOSX, Windows 11
- Using remote-ssh/docker/wsl? no

**Logs**

I did my best but setting `testMate.cpp.log.logfile` to `/tmp/testMate.log` and reloading the tests in test explorer did not create any files and `testMate.cpp.log.logpanel` does not add anything related to tests in the OUTPUT tab drop down menu.

**Comment by matepek** [comment]
Hey,

So you want extra parameter for your executable and you were trying to use `executionWrapper` for that. That's all or did I misunderstand something?

Have you noticed the `prependTestRunningArgs` and `prependTestListingArgs` features? Sound to me that these might be the droids you are looking for.

Let me know.
