### ISSUE TITLE
Catch2 test cases with same name show up only once

### ISSUE THREAD

**Issue by qustrolabe** [matepek/vscode-catch2-test-adapter#443]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

Catch2 test cases allow same name if tags are different. Test Results on the VSCode **Panel** work fine, but issue lies in "Testing" section on VSCode **Activity Bar** - there **only one** of these tests show up

**To Reproduce**

```cpp
TEST_CASE("Test123", "[MyTag1]") { REQUIRE(true); }
TEST_CASE("Test123", "[MyTag2]") { REQUIRE(true); }
TEST_CASE("Test123", "[MyTag3]") { REQUIRE(true); }
```

1. Create and run tests shown above
2. Open Testing on Activity Bar
3. Notice how only one Test123 shows up

**Screenshots** (optional)

![Screenshot 2024-08-23 204005](https://github.com/user-attachments/assets/bf385801-740d-4439-ba0a-573f3a781fe4)
**Desktop**

- Extension Version: v4.12.0
- VS Code Version: 1.92.2
- Catch2 Version: 3.7.0
- OS Type and Version: Windows 11
- Using remote-ssh/docker/wsl?: No

**Comment by matepek** [comment]
Hey,
Thanks for the report.
It ringed a bell so I checked the code.
So the thing is that there is no way to identify runtime the test based on a **name** + **tag** combo.
Therefore it would not work.

```
./catch2v3_test1.exe 'Scenario: some scenario' --reporter xml
<?xml version="1.0" encoding="UTF-8"?>
<Catch2TestRun name="catch2v3_test1.exe" rng-seed="2992006806" catch2-version="3.1.1" filters="Scenario: some scenario">
  <TestCase name="Scenario: some scenario" tags="[.][integration]" filename="./test/cpp/catch2/catch2v3_test1.cpp" line="47">
    <Section name="Given: a widget, a gadget, a whoozit, a whatzit, and a thingamajig" filename="./test/cpp/catch2/catch2v3_test1.cpp" line="48">
      <Section name="When: foo is barred" filename="./test/cpp/catch2/catch2v3_test1.cpp" line="49">
        <Section name="Then: bif is bazzed" filename="./test/cpp/catch2/catch2v3_test1.cpp" line="50">
          <OverallResults successes="1" failures="0" expectedFailures="0"/>
        </Section>
        <OverallResults successes="1" failures="0" expectedFailures="0"/>
      </Section>
      <OverallResults successes="1" failures="0" expectedFailures="0"/>
    </Section>
    <OverallResult success="true"/>
  </TestCase>
  <OverallResults successes="1" failures="0" expectedFailures="0"/>
  <OverallResultsCases successes="1" failures="0" expectedFailures="0"/>
</Catch2TestRun>
``` 

I'm sorry but live feedback is more valuable feature than this.
