### ISSUE TITLE
Gtest links to files does not work

### ISSUE THREAD

**Issue by sonofR9** [matepek/vscode-catch2-test-adapter#446]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Describe the solution you'd like**
I want to change paths in teastmate output from relative to absolute: it will allow to click on the link to file:line and open it in vscode.

**Additional context**
Now links does not always work. For example, I have:
```
project_dir = TestMate...WorkingDirectory = ${absDirpath}
 ├ build
 |    └─ Debug
 |        └─test
 |              └ subfolder
 |                     └------ executables
 └─ test
      └- subfolder
         └─ my code
```
$3│ [ RUN      ] Test.Name @ ./test/subfolder/test.cpp:22
$3│ │ Failure @ ./test/subfolder/test.cpp:24

And link does not work (vscode can't find it). Interestingly enough test/subfolder/test.cpp:22 works just fine.
At the same time gtest outputs absolute path when run from console and vscode can use it just fine (as link to source file),

**Comment by sonofR9** [comment]
Sorry, it is probably not yours fault: vscode itself does not recognise correctly formed links sometimes.

**Comment by matepek** [comment]
Hey,

Yeah its a tricky one. I remember I had been tinkering a lot how I could manage this to work.
So far couldn't get a better solution. If the output window would allow to interpret markdown or that what would be so cool but that should come from vscode dev side..
Feel free to bug them and reference this issue. :)

[related](https://stackoverflow.com/questions/74537129/how-can-i-make-clickable-file-position-links-in-an-output-channel-that-open-the)
