### ISSUE TITLE
Cancel running test case

### ISSUE THREAD

**Issue by khteh** [matepek/vscode-catch2-test-adapter#449]
**Checklist**

- [ x] The issue is about this extension and NOT about a fork.
- [ x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [ x] The latest version of the extension was used.
- [x ] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [ ] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

There is no way for me to cancel a running test case in error except to `killall code` on Linux!?!
![image](https://github.com/user-attachments/assets/6c5f9488-9a08-477e-b774-d001f26ed5f0)

**To Reproduce**

**Screenshots** (optional)

**Desktop**

- Extension Version: 4.12.0
- VS Code Version: 1.94.2
- Catch2 / Google Test / DOCTest Version: 1.14.0
- OS Type and Version: Ubuntu 24.04
- Using remote-ssh/docker/wsl?: No

**Regression bug?**

- Last extension version in which the feature were working:

<details>
  <summary>**Log** (optional but recommended)</summary>

```js
  <paste logs here>
```

</details>

**Comment by matepek** [comment]
You don't have this button?

<img width="283" alt="SCR-20241019-rovp" src="https://github.com/user-attachments/assets/aa6e6351-5b31-43f7-913d-afc439ded757">
