### ISSUE TITLE
Using ${label} and ${parentLabel} on preLaunchTask to start gdbserver of the selected Gtest binary

### ISSUE THREAD

**Issue by andreucv** [matepek/vscode-catch2-test-adapter#450]
**Checklist**

- [x] The issue is about this extension and NOT about a fork.
- [x] Checked the [ALL the SUPPORT](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md) document.
- [x] The latest version of the extension was used.
- [x] It is not related to remote-vscode or I checked the following [issue](https://github.com/matepek/vscode-catch2-test-adapter/issues/201)
- [x] Imagine yourself into my position and think how hard to debug the issue without insufficient information.
      I understand that you have privacy concerns and I expect you to understand that this extension is developed for free.
      Thanks.

**Describe the bug**

**Situation:**
To run a GTest binary I create a docker container with the sdk and the toolchain needed to execute it. I created a wrapper to execute them using your extension, and it works good. 
I build multiple GTest binaries from different components in my repository.
In order to improve performance, how I do it is to maintain the docker container started, and use the `executionWrapper` setting to execute the GTest binary using a `docker exec container_id sh -c ./gtest_component_name_binary`.

**Problem:**
Then, as a next step, I want to apply the debug configuration.
I'm blocked, as to be able to debug, when I am clicking on the test's debug button I need to start a gdbserver session for the GTest binary selected (I thought on using the `${parentLabel}` which I set to be the GTest binary name). 
I thought on doing that on the `preLaunchTask`. 

However, I have not found any way to pass parameters to the `preLaunchTask`, as it can only be set as a name of a task inside `tasks.json`, and I cannot pass the binary name or the testname to do it automatically. 
I would like to avoid any other user interaction.
Do you know how I could do that?

**To Reproduce**
    1. Go to Testing Section
    2. Click on Debug Test button
    
**Desktop**

- Extension Version: v4.12.2
- VS Code Version: 1.95.1
- OS Type and Version: Ubuntu 24.04
- Using remote-ssh/docker/wsl?: remote-devcontainers

How I use `debug.configTemplate`:
![image](https://github.com/user-attachments/assets/57d99517-7468-4263-846b-304b93b94887)

How I thought it could be used (and doesn't work, this task is not recognized as a task):
![image](https://github.com/user-attachments/assets/b202a992-2eb6-4a45-8bde-8b46b1ad763c)

**Comment by matepek** [comment]
A tons of variabale should be available for tasks too:

- https://github.com/matepek/vscode-catch2-test-adapter/blob/3dc483b012d34d6f80ff76a19b70144caec6c34b/src/WorkspaceManager.ts/#L450-L476
- https://github.com/matepek/vscode-catch2-test-adapter/blob/3dc483b012d34d6f80ff76a19b70144caec6c34b/src/WorkspaceManager.ts/#L351-L359

**Comment by matepek** [comment]
Ah, got confused. That works for the 

```json
"runTask" {
  "before": ["task"],
}
```
 only.

**Comment by matepek** [comment]
What you can use from any tasks are `${testMate.cmd.get-debug-exec}` and `${testMate.cmd.get-debug-args}`.

Ex
