### ISSUE TITLE
Ability to specify visualizerFile (and other launch configuration options) in debug config

### ISSUE THREAD

**Issue by twhittock-disguise** [matepek/vscode-catch2-test-adapter#453]
**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**
When debugging my tests, it is frustrating that I am unable to use C++ natvis visualisation files. This is because they are added to my launch configurations in the `visualizerFile` section.

I am unable to use my launch configurations as it's unclear if/how the executable name and arguments are passed to the configuration.

**Describe the solution you'd like**
I'd like to either be able to use a generic launch configuration with this extension filling in the appropriate executable and command line arguments, or be able to specify all the launch configuration options in the `debug.configTemplate` section.

**Describe alternatives you've considered**
There is a workaround - copy the .natvis files from my project into `~/.vscode(-insiders)/extensions/ms-vscode.cpptools-x.y.z/debugAdapters/vsdbg/bin/Visualizers` but this will frequently break due to the cpptools extension being updated.

**Additional context**
None

**Comment by matepek** [comment]
Hello, 

Did you find this [doc](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md)?

**Comment by twhittock-disguise** [comment]
Hi yes I read the documentation - I didn't see anything around specific launch commands though? Did I miss it?

**Comment by matepek** [comment]
At first read, I think the usable variables section answers your question. If not, please elaborate on your issue.

**Comment by matepek** [comment]
This extension does not do any debugging, it uses the debug adapters/extensions.

Don't depend on launch config. Try setting your `testMate.cpp.debug.configTemplate`. All the mentioned variables are available there.

**Comment by twhittock-disguise** [comment]
Yes, debugging works fine using the `debug.configTemplate` configuration. This issue was raied due to the lack of several things which are present when debugging using a launch command instead.

Specifically, the `visualizerFile` option is not applied when debugging tests. Also things like the `preLaunchTask` are helpful checks to ensure I am always debugging the latest code. There are a few of these, those are the ones I use, especially the `visualizerFile`, as some of my types are a pain to debug without it.

**Comment by matepek** [comment]
`preLaunchTask` not run I'm not sure it is the issue of this extension because this extension just passes whatever debug config it gets. That applies to other json properties.

check log message `'debug config data'` and `'resolved debugConfig:'`.

`preLaunchTask` probably can be circumvented with advancedExecutable `before` property.
