### ISSUE TITLE
Opening this issue to tell you how much I love gmockVerbose

### ISSUE THREAD

**Issue by javierfileiv** [matepek/vscode-catch2-test-adapter#454]
Please still support it!

**Checklist**

- [x] Checked [Support page](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/support.md)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matepek** [comment]
First I was like what is this about?!
Then I refreshed my memory. It made my day 😂

I think I wanted to deprecate because there are other ways to achieve the same but I might just underestimated the convenience factor..

Thanks for the issue. :)

**Comment by javierfileiv** [comment]
I thought it was a funny way to point it out in code.... so I did what you said ;) 


have a nice one!
