### ISSUE TITLE
Grouping src files for unittesting

### ISSUE THREAD

**Issue by GirishTabaraddi** [matepek/vscode-catch2-test-adapter#457]
Hi,

I am configuring testmate for executing and debugging unittest for my project. I want to know how to group the source files before even executing. To understand clearly, I want to list all my source files under Testing in VSCode, so that when a developer wants run a task, he/she can click the run button to execute the VSCode tasks. Below is my code, which I expected it to load the cpp files, but it is not. It only does when you have generated the exe for the component.

    "testMate.cpp.test.advancedExecutables": [
        {
            "pattern": "${workspaceFolder}/Appls/code/**/*.cpp",
            "strictPattern": true,
            "cwd": "${workspaceFolder}",
            "runTask": {
                "before": ["Execute Unittest for DUT"],
                "after": ["Print Unittest Coverage for DUT"]
            },
            "gtest": {
                "testGrouping": {
                    "groupBySource": {
                        "label": "📝${sourceRelPath[-3]}",
                        "groupUngroupedTo": "📝Unknown Src File"
                    }
                }
            }
        }
    ],
    "testMate.cpp.debug.configTemplate": {
        "name": "Debug Test",
        "type": "cppdbg",
        "request": "launch",
        "program": "${exec}",
        "args": ["--gtest_filter=*"],  
        "cwd": "${workspaceFolder}",
        "MIMode": "gdb",
        "miDebuggerPath": "${workspaceFolder}/Appls/build_tools/mingw64/bin/gdb.exe",
        "stopAtEntry": false,
        "environment": [],
        "externalConsole": false
    },
    
    Correct me if I am doing anything wrong here. Thanks

**Comment by matepek** [comment]
Hello,
The pattern should find executables, not `cpp` files. Cpp files are just text files and c++ is not an interpreted language like python or javascript so this won't work like this.

**Comment by matepek** [comment]
`testMate.cpp.debug.configTemplate` seems wrong. pls check documentation.

**Comment by GirishTabaraddi** [comment]
Hi @matepek 
Thanks for the inputs.

With regards to debug code, I tried the below changes as per the document that I understood and it failed to find the executable.

    "testMate.cpp.debug.configTemplate": {
        "name": "Debug Test",
        "type": "cppvsdbg",
        "win32": { "type": "cppvsdbg" },
        "request": "launch",
        "program": "${workspaceFolder}/Appls/out/UnitTest_Dir/**/build/unittests/*.exe",
        "args": [],  
        "cwd": "${workspaceFolder}/Appls/out/UnitTest_Dir",
        "MIMode": "gdb",
        "miDebuggerPath": "${workspaceFolder}/Appls/build_tools/mingw64/bin/gdb.exe",
        "stopAtEntry": false,
        "environment": [],
        "console": false
    },
Can you point to me what configuration is wrong here? 

Below Config was able to hit the breakpoint and debug
    "testMate.cpp.debug.configTemplate": {
        "name": "Debug Test",
        "type": "cppdbg",
        "win32": { "type": "cppdbg" },
        "request": "launch",
        "program": "${exec}",
        "args": [],  
        "cwd": "${workspaceFolder}/Appls/out/UnitTest_Dir",
        "MIMode": "gdb",
        "miDebuggerPath": "${workspaceFolder}/Appls/build_tools/mingw64/bin/gdb.exe",
        "stopAtEntry": false,
        "environment": [],
        "console": false
    },
    
The difference is in the type "cppdbg" and "cppvsdbg", and the program variable. I would like to know more on these varaibles, as I didn't find much information on the Github of TestMate.

Thanks

**Comment by matepek** [comment]
This one is wrong: `"program": "${workspaceFolder}/Appls/out/UnitTest_Dir/**/build/unittests/*.exe",`

You have to understand that this extension is not a debug adapter, it passes `"testMate.cpp.debug.configTemplate"` to other debug adapters after variable resolution.

[doc](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/documents/configuration/debug.configTemplate.md)
