### ISSUE TITLE
Cannot run a parameterized GoogleTest

### ISSUE THREAD

**Issue by OpenNingia** [matepek/vscode-catch2-test-adapter#46]
**Before you file an issue, please check the [README.md](https://github.com/matepek/vscode-catch2-test-adapter#known-issues)'s known issues section.**

**Describe the bug** (A clear and concise description of what the bug is.)
Nothing happens after running a parameterized test.

**To Reproduce** (Steps to reproduce the behavior:)
1. Try to run any parameterized test.
2. Nothing happens

**Expected behavior** (A clear and concise description of what you expected to happen.)
The test should run and display its result.

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Desktop (please complete the following information):**

- Extension Version: 2.3.7
- VS Code Version 1.30.1
- Catch2 Version: N/A
- OS Type and Version: Windows 10 Pro x64

**Log** (Attach log. (optional, Set: `catch2TestExplorer.logfile` and reproduce the bug.) _Warning_: Log probably contains file and test names too.)

[2019-01-03 09:38:25.442] [INFO] proc started: [ 'redacted.exe',
  [ '--gtest_color=no',
    '--gtest_filter=Test2Instance/Test2.DispatchResponse/0  # GetParam() = (false, false)',
    '--gtest_also_run_disabled_tests' ] ]
[2019-01-03 09:38:25.624] [INFO] proc finished: 

**Additional context** Add any other context about the problem here.

I think the issue here is the --gtest_filter that is too specific ( AFAIK you shouldn't specify the 'GetParam()' part there )

**Comment by matepek** [comment]
Hello,
I can you run your test from command line with --gtest_filter=... ?
And what is the name of the test exactly?

**Comment by OpenNingia** [comment]
> 
> 
> I think I see your problem:
> Are you using: INSTANTIATE_TEST_CASE_P macro?
> Parser isn't prepared for this.

Yes, exactly. 
About `--gtest_output=json` if you're going to rely on that the extension won't work on googletest releases older that 1.8.x. 
The one I use ATM only has --gtest_output=xml support.

**Comment by matepek** [comment]
I'm on it

**Comment by matepek** [comment]
fixed in version > 2.3.7
