### ISSUE TITLE
Glob syntax to find tests executable not work for path outside the workspace

### ISSUE THREAD

**Issue by DPD85** [matepek/vscode-catch2-test-adapter#48]
**Describe the bug**
The glob syntax to find tests executables ("catch2TestExplorer.executables.pattern" setting) not work when the path point to a folder outside the workspace.

**To Reproduce**

1. Clone my test repository: https://github.com/DPD85/Catch2VSCodeExtensionIssue;
2. Open the repository with VSCode and build everything;
3. Open Tests Explorer tab;
4. See that there is no tests, see first screenshot.

**Expected behavior**
See one test from Tests.exe called "Factorials are computed", see second screenshot.

**Screenshots**
1. ![bad](https://user-images.githubusercontent.com/1238383/50651169-db3ec580-0f82-11e9-9e70-af8cfb81dbbb.png)
2. ![good](https://user-images.githubusercontent.com/1238383/50651171-dbd75c00-0f82-11e9-8878-861617b51ef5.png)

**Desktop:**

- Extension Version: 2.3.8
- VS Code Version: 1.30.1
- Catch2/Google Test Version: Catch2 v2.5.0
- OS Type and Version: Windows 10, version 1809 (build OS 17763.195), 64 Bits

**Log**
Log file when the error occur: [catch2TestExplorer.log](https://github.com/matepek/vscode-catch2-test-adapter/files/2724664/catch2TestExplorer.log)

**Comment by matepek** [comment]
Excellent bug report! 💙

Sadly, this is the expected behaviour. 
The **vscode API** has this limitation. 😔

The documentation isn't good enough:
> `pattern`: A relative pattern (to workspace) or an absolute file-path.

Should be something like this:
> A relative pattern (to workspace (also it has to be inside the workspace folder)) or an absolute file-path (this case it can be outside of the workspace folder too).

I'm gonna fix it.

If it helps, change your workspace folder to `..` and use the vscode's `files.exlude` option:
```
  "files.exclude": {
    ".git": true,
    "node_modules": true,
    "out": true
  }
```

**Comment by DPD85** [comment]
Unfortunately not works for me becuase of [this](https://github.com/vector-of-bool/vscode-cmake-tools/issues/533) other issue of vscode-cmake-tools 😔.
But for now, I can convert my project configuration to create a single executable containg all the tests and use a simple relative path (without glob syntax).

I will keep in mind you solution and I will try again when the vscode-cmake-tools issue will be solved.

Thanks!

**Comment by matepek** [comment]
You may don't need that. We had been using it, but then we threw away.

https://code.visualstudio.com/docs/editor/tasks

```
    {
      "label": "(Debug) cmake configure",
      "type": "shell",
      "group": "build",
      "command": "cmd.exe",
      "args": [
        "/C",
        "cd . && mkdir Debug & cd Debug && vcvarsall.bat amd64 && cmake -D CMAKE_BUILD_TYPE=Debug .. && cd ."
      ],
      "options": {
        "cwd": "${workspaceFolder}/build"
      },
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true
      },
      "problemMatcher": []
    },
```

You only have to add to `PATH` env the directory of `vcvarsall.bat`.

**Comment by DPD85** [comment]
hum, interesting. I did not know about the tasks inside the VSCode.
I will try with this solution.

Thanks.

**Comment by DPD85** [comment]
hum, interesting. I did not know about the tasks inside the VSCode.
I will try with this solution.

Thanks.
