### ISSUE TITLE
Discovery of gtest tests hangs

### ISSUE THREAD

**Issue by kondratyev-nv** [matepek/vscode-catch2-test-adapter#59]
The test adapter never stops loading (refresh icon continue spinning) and no tests appear when it discovers gtest tests with default parameters. I tried to wait about 20 minutes, but still no success. If I set `catch2TestExplorer.executables` to discover tests within a specific executable, e.g. 
```
    "catch2TestExplorer.executables": [
        {
            "name": "${filename} (${relDirpath})",
            "pattern": "build/training_test",
            "cwd": "${workspaceFolder}/test"
        }
    ]
```
tests are discovered just fine.

This is happening for the C++ part of my repo https://github.com/kondratyev-nv/training/tree/master/cpp.

Also, I'm using both Windows and Linux, and this affects only Linux (Ubuntu 18.04). With a little bit of debugging, it looks like discovery hangs on executing some python script from gtest, but I'm not sure about it. Maybe it works on Windows because python scripts are not executable by itself in there.

Log: [cpp-test-adapter-linux.log](https://github.com/matepek/vscode-catch2-test-adapter/files/2814144/cpp-test-adapter-linux.log)

- Extension Version is 2.3.15
- VS Code Version is 1.30.2

**Comment by matepek** [comment]
Hey,

Thanks for the report. 
Would the checking of the file's executable flag solve the problem? What do you think?
I'm not using linux and my VM is on the shelf.
Would you check it a python file's flags for me please? (`ls --all`)

**Comment by matepek** [comment]
I release something which hopefully fixes this. (version2.3.16)
Thanks again for the issue

**Comment by kondratyev-nv** [comment]
@matepek Thank you for the quick fix! It looks like right now test discovery is pretty fast.

I was thinking about the execution timeout. However, force stopping a process execution can be harmful. And the solution with the ignore list might work better. 

Also, as a notice, this issue probably was caused _because_ the executable flag is set for files. In Linux files not marked as executable cannot be executed. For example, I can create a python script
```
$ cat hello_world.py
#!/usr/bin/env python

print "Hello, world!"
```
Try to execute it by default
```
$ ./hello_world.py
zsh: permission denied: ./hello_world.py
```
But when I mark it executable
```
$ chmod u+x hello_world.py
$ ./hello_world.py
Hello, world!
```
It executes just fine.

And in the gtest folder there are a lot of executable
```
..cpp/build$ find ./ -executable -type f -name "*test*"
./training_test
./lib/gtest/src/googletest/googletest/scripts/gtest-config.in
./lib/gtest/src/googletest/googletest/scripts/fuse_gtest_files.py
./lib/gtest/src/googletest/googletest/scripts/upload_gtest.py
./lib/gtest/src/googletest/googletest/scripts/gen_gtest_pred_impl.py
./lib/gtest/src/googletest/googletest/test/googletest-output-test.py
./lib/gtest/src/googletest/googletest/test/gtest_testbridge_test.py
./lib/gtest/src/googletest/googletest/test/gtest_test_utils.py
./lib/gtest/src/googletest/googletest/test/gtest_xml_test_utils.py
./lib/gtest/src/googletest/googletest/test/googletest-throw-on-failure-test.py
./lib/gtest/src/googletest/googletest/test/googletest-catch-exceptions-test.py
./lib/gtest/src/googletest/googletest/test/gtest_help_test.py
./lib/gtest/src/googletest/googletest/test/googletest-color-test.py
./lib/gtest/src/googletest/googletest/test/googletest-env-var-test.py
./lib/gtest/src/googletest/googletest/test/googletest-break-on-failure-unittest.py
./lib/gtest/src/googletest/googletest/test/gtest_xml_output_unittest.py
./lib/gtest/src/googletest/googletest/test/googletest-shuffle-test.py
./lib/gtest/src/googletest/googletest/test/googletest-filter-unittest.py
./lib/gtest/src/googletest/googletest/test/googletest-list-tests-unittest.py
./lib/gtest/src/googletest/googletest/test/gtest_xml_outfiles_test.py
./lib/gtest/src/googletest/googletest/test/googletest-uninitialized-test.py
./lib/gtest/src/googletest/googlemock/scripts/generator/cpp/gmock_class_test.py
./lib/gtest/src/googletest/googlemock/test/gmock_test_utils.py
./lib/gtest/src/googletest/googlemock/test/gmock_output_test.py
./lib/gtest/src/googletest/googlemock/test/gmock_leak_test.py
./lib/gtest/src/googletest-build/CMakeFiles/feature_tests.bin
./CMakeFiles/feature_tests.bin
```

**Comment by matepek** [comment]
Good to hear. :)

> I was thinking about the execution timeout.

Since this release it has filtering by extension and executable bit, and has 5 sec timeout too.

**Comment by matepek** [comment]
I will enable .sh, .py file-s again. The execution timeout is 30 seconds now.
Let me know if you experience any problem with it.
