### ISSUE TITLE
Add Catch2 SECTIONs to TextExplorer test list

### ISSUE THREAD

**Issue by BlackZork** [matepek/vscode-catch2-test-adapter#66]
**Is your feature request related to a problem? Please describe.**
It is hard to debug single catch2 SECTION

**Describe the solution you'd like**
Show list of TEST_CASE SECTIONs in Test Explorer panel. Allow to run and debug single section.

**Describe alternatives you've considered**
If it is hard to add next level to TestExplorer tree it would be great if TEST_CASE and its SECTIONs could be displayed next to each other on single list.

**Comment by matepek** [comment]
The Catch2 framework doesn't support it. :/
See this [issue](https://github.com/catchorg/Catch2/issues/1387) for details.

What I could do to generate the executable parameter list for the failing sections. Then it would be easy to set up a [launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations).

Would you use it?

**Comment by matepek** [comment]
I made something for you (like 👵 makes 🍪). It will be released soon in version > 2.3.21
Tell me how you like it.

**Comment by BlackZork** [comment]
Thanks. Now I manually edit launch configuration when debugging a section. OTOH I replaced most of my sections with test cases, it is much easier to run them from TestExplorer.

**Comment by matepek** [comment]
You have to run the test beforehand you debug it.
If you use windows or linux, I wouldn't mind a screenshot about the new feature. Curious about how it looks like on those platforms.

**Comment by Trass3r** [comment]
The sections do get reported in the xml output.
Could the test tree maybe be updated to include the sections _after_ the tests are run?

**Comment by matepek** [comment]
Yes. In version 4.x it will be able to.
It's on the roadmap but I have a main job and life is just a little bit busier than usual. (In a good way :)

**Comment by Trass3r** [comment]
Nice!
One thing to keep in mind for the implementation is that generators aren't well integrated.
For me it doesn't report generated values like sections so I get multiple copies of the same subtree.

**Comment by matepek** [comment]
Dear User,

Version 4+ has been released recently.

It is still missing

> Allow to run and debug single section.

but it is on the todo list and I will look into it.

I'm closing this issue for now. If you disagree then please comment `!open`.
