### ISSUE TITLE
Timeout while checking the executable for tests

### ISSUE THREAD

**Issue by davidbroetje** [matepek/vscode-catch2-test-adapter#67]
**Describe the bug** (A clear and concise description of what the bug is.)
In the test panel no executable and no test is shown. When the "Reload tests" button is clicked, the arrow spins a few times but no executable and test is loaded. In the logfile there is the following (PATHS AND EXECUTABLES ARE HIDED):

[2019-03-01 07:23:41.807] [WARN] Not a test executable: ABSOLUTE_PATH_AND_NAME_OF_TESTEXECUTABLE_HERE reason: [Error: FsWrapper.spawnAsync timeout: 5000
	at Timeout.setTimeout [as _onTimeout] (ABSOLUTE_PATH_TO_EXTENSION_FOLDER_HERE\.vscode\extensions\matepek.vscode-catch2-test-adapter-2.3.21\out\FsWrapper.js:47:28)
	at ontimeout (timers.js:427:11)
	at tryOnTimeout (timers.js:289:5)
	at listOnTimeout (timers.js:252:5)
	at Timer.processTimers (timers.js:212:10)]

A timeout is happening when checking the executable for tests. 

With Version 2.3.15 of the Catch2 extension it is still working. When the "Reload tests" button is clicked the arrow spins for about 30 secs and then the tests are shown.

**Expected behavior** (A clear and concise description of what you expected to happen.)
The tests are loaded and shown in the test panel.

**Desktop (please complete the following information):**

- Extension Version 2.3.21 (With version 2.3.15 it was working. Since version 2.3.16 it fails)
- VS Code Version 1.31.1
- Catch2 v2.6.1
- Windows 7

**Comment by matepek** [comment]
Hello,

If you run your executable with 
> "[.],*" "--verbosity" "high" "--list-tests" "--use-colour" "no"

does it produces a valid output? And how long does it take? I can increase the timeout if it turns out that solves your problem.

**Comment by davidbroetje** [comment]
Hey,

yeah it outputs all the testcases (name, source location and description). It takes about 7-8 seconds.

**Comment by matepek** [comment]
Okay,
It is increased to 30 sec in version > 2.3.21
I will release it soon, just wanna finish another feature.
