### ISSUE TITLE
Tests wrapped by script does not work anymore

### ISSUE THREAD

**Issue by pgrabas** [matepek/vscode-catch2-test-adapter#73]
Hello,

Executing tests wrapped by script are not working anymore since last update.
I know it is not standard way, but my tests must be executed on remote target not locally.

Log:
```
[2019-03-15 09:53:34.870] [INFO] [at load.suiteCreationAndLoadingTasks.push.c2fs.isNativeExecutableAsync.then (.vscode/extensions/matepek.vscode-catch2-test-adapter-2.3.24/out/TestExecutableInfo.js:81:34)] Not an executable: .vscode/target_ut.sh [Error: Not a native executable (filtered because of its extension): .vscode/target_ut.sh
	at Object.isNativeExecutableAsync (.vscode/extensions/matepek.vscode-catch2-test-adapter-2.3.24/out/FsWrapper.js:97:35)
	at TestExecutableInfo.load (.vscode/extensions/matepek.vscode-catch2-test-adapter-2.3.24/out/TestExecutableInfo.js:68:52)]
```

**Comment by matepek** [comment]
Hi.

Oh, sorry. I haven't expected that anybody uses it with script. 
Gonna fix today.

**Comment by pgrabas** [comment]
Hi,

I have found another small issue. Because I am stuck old version of gtest there is no 'file' and 'line' attributes in xml output. This causes parsing to fail. I can make workaround for this if you do not wish to support old framework. My wrapper script already merges output of several ut's so I can easily  insert dummy attributes.

BTW your plugin is great.
Thanks in advance.

**Comment by matepek** [comment]
But has your gtest version's xml test list output without file and line?

**Comment by pgrabas** [comment]
Yes. I have no such attributes. I have fix it by pipe'ing produced xml through sed, so this is not an issue for me any longer.

**Comment by matepek** [comment]
I'm gonna fix it. But if you can provide file and line information the navigation will work.

**Comment by pgrabas** [comment]
I can go without it navigation. The most important for me is to execute all ut's with one click.

**Comment by matepek** [comment]
Released.
Now it should work with xml with missing file and line information.

**Comment by matepek** [comment]
> BTW your plugin is great.

Thanks for your feedback ^^

You probably already aware of it, but If you `touch` your executable/script then it will reload the tests automatically. So you can add a `touch .vscode/target_ut.sh` as a build step in case you expect your executables being modified.
