### ISSUE TITLE
Skiped test's in the tree

### ISSUE THREAD

**Issue by aey76** [matepek/vscode-catch2-test-adapter#75]
When skipping a test with GTEST_SKIP() the tree shows the nest test as skipped.
see the screenshot:
![Screenshot from 2019-03-17 22-11-09](https://user-images.githubusercontent.com/26801754/54497294-a1365c00-4901-11e9-8318-4c0fae6817a3.png)

the skipped test is test_1 but the tree show test_2 as skipped.

**Comment by matepek** [comment]
I haven't know about this gtest feature. Gonna look after it.
Is it regression? I guess it isn't.

**Comment by matepek** [comment]
released
