### ISSUE TITLE
Feature request - execution time next to the test name

### ISSUE THREAD

**Issue by csorvagep** [matepek/vscode-catch2-test-adapter#79]
It would be nice to see the execution time of each test next to the test name inside the test explorer.  I'm currently using google test, maybe it is there for other test environments?

**Comment by matepek** [comment]
So the thing is, that there are no nice solution just hacky ones.
As you can see, I referred an issue. You can upvote it.

**Comment by csorvagep** [comment]
I see, that is unfortunate, but I hope this will change in the future. Thanks.

**Comment by matepek** [comment]
I mean upvote my comment on the issue :)

The issue itself is related but not the same. So your current vote is misleading.

**Comment by csorvagep** [comment]
Sorry, fixed that :D

**Comment by csorvagep** [comment]
It seems the Test Explorer is updated and now it shows the execution times. Thanks!

**Comment by matepek** [comment]
YW
It also shows the accumulated execution time too, but that part is a bit buggy.
If that bothers you, you can upvote this [issue](https://github.com/hbenl/vscode-test-explorer/issues/54).
