### ISSUE TITLE
Code lens / gutters with OpenCppCoverage (Windows)

### ISSUE THREAD

**Issue by Shelim** [matepek/vscode-catch2-test-adapter#80]
**Is your feature request related to a problem? Please describe.**
It is hard to get which part of the code are checked against which tests (and where do they fail). I believe Test Explorer has code lens and gutters for coverage for each test, but Catch2/GTest Adapter cannot generate data for it, because it does not give information about lines that run for given tests.

**Describe the solution you'd like**
Actually there is a FOSS tool (unfortunately Windows only) that can feed that information; [OpenCppCoverage](https://github.com/OpenCppCoverage/OpenCppCoverage) takes PDB and verify, for each executable run, which lines were actually executed and which were not. It generates `cov.xml` (format recognizable by Coverage Lens in VSCode).

It would be great if Catch2/GTest Adapter could use that data to populate lens and gutters at least on Windows.

**Describe alternatives you've considered**
There is no similiar tool for Linux / OS X I am aware of. There is no other plugin for GTest for VSCode as well.

**Additional context**
If effort would not be acceptable on Your side for any reason, I can implement this in fork, then propose PR. I would ask only for some basic directions. Still, it would be great, if You can add this feature directly - you know your code much better than myself.

**Comment by matepek** [comment]
Hello,

I don't understand you.
This extension (and the Test Explorer also) is for parsing test executables, showing the tests and running them. It is not showing coverage information.

Test Explorer has code lens for tests. It is for to mark the test lines which are failing. If I understand you  correctly, you would like to use it to mark the untested code-lines. Am I right? 

Neither Catch2 or GTest generates coverage informations. So what should it process?
Do you run your tests through OpenCppCoverage?

Maybe you need a custom [TestController](https://github.com/hbenl/vscode-example-test-controller).
You could subscribe onto `testStates` events like [here](https://github.com/hbenl/vscode-example-test-controller/blob/master/src/controller.ts#L52) and add your code lens and gutters as you wish through *vscode API* ([reference](https://code.visualstudio.com/api/references/vscode-api#CodeLensProvider))

**Comment by Shelim** [comment]
Hello,

Sorry for my rusty english :)

No, I want to mark the test lines that are failing - and I believe this is hard to do by using GTest executable only. That's why I proposed OpenCppCoverage as solution;

So the workflow would be to:
1.) Run given single test via OpenCppCoverege
2.) If succed, mark all lines from cov.xml as "Passing this test"
3.) If not, mark all lines from cov.ml as "Failing this test"
4.) Agregate above data into lens like -> "Failed 1/2 tests"

**Comment by matepek** [comment]
I'm sorry too, my understanding is not perfect.

I quickly searched for "coverage" and I [found](https://marketplace.visualstudio.com/search?term=coverage&target=VSCode&category=All%20categories&sortBy=Relevance) a couple of promising tools.

Usually these coverage tools produces similar outputs and these tools were built on those formats. It seems that OpenCppCoverage also uses this format ("--export_type:binary"). Hooray!

Generating and using coverage report is usually related but a bit different from testing. GTest cannot do that.

What you can do to achieve a result close to your proposal is that:
- You run your tests through some coverage tool (OpenCppCoverage)
- You create a Test Controller (which subscribes to `testStates`, etc...)
- Activate an existing coverage extension to show the result: For example: *ryanluker.vscode-coverage-gutters*: `extension.displayCoverage`.
- Or you can decorate your own code through vscode API.

I hope I helped.

Bests,

**Comment by Shelim** [comment]
Okay, I think we still misunderstand each other - I am not taking about coverage report :)

I want to achieve something like this for C++:
![obraz](https://user-images.githubusercontent.com/4707644/54814970-2074b880-4c91-11e9-9dc1-a4597c13e721.png)

The OpenCppCoverage is a tool that will generate information which lines were used in given execution run. I believe we can use that tool to populate the information into source code, which part of source code were used by given tests (for example that failed).

**Comment by matepek** [comment]
I see, I think I understand you now fully. Thanks for explaining it to me. :)

I still think that a custom TestController could be a solution. I don't intend to implement this really specific feature.

**Comment by Shelim** [comment]
The problem is you need to change executable run for tests (instead of `your_app.exe` you need to call `opencppcoverage.exe -- your_app.exe`), and you need to run tests one-by-one. Both things requires changes in your code.

I made a fork of your repo and started implementation. The first part is done (it is able to provide me with `conv.xml` for each test pass containing file lines used for that pass). Now for the lens and some bugfixing :)

**Comment by matepek** [comment]
Have fun :)

**Comment by Shelim** [comment]
I had, thank you - my typescript is a bit rusty (well - maybe more than a bit) :-)

![test](https://user-images.githubusercontent.com/4707644/54873596-78b6d200-4dd9-11e9-8248-58b559bd1068.png)

I will publish that into VS extensions repo soon :)

**Comment by matepek** [comment]
Hello, 
There is a new API for integrating coverage tools: [check it out if interested](https://github.com/matepek/vscode-catch2-test-adapter/issues/519)
