### ISSUE TITLE
Let's talk about experimental `enableTestListCaching`

### ISSUE THREAD

**Issue by matepek** [matepek/vscode-catch2-test-adapter#84]
> (Experimental) In case your executable took too much time to list the tests, one can set this. It will preserve the output of `--gtest_list_tests --gtest_output=xml:...`. (Beware: Older Google Test doesn't support xml test list format.)

**Please subscribe** to this issue at **Notifications**  👉👉👉
if you would like to be updated about the changes.
Also I will have questions too.

👍if you like it.
👀if you tried it but didn't feel the difference.

Comment if you don't feel the difference or has some feedback. I'm interested about the situations when it has performance benefits (with details: file count; avg. test count/file ...)

**Comment by AnakinMac** [comment]
Rightnow we are using an old version of Google Test (1.7.1), so haven't tried the feature yet.
