### ISSUE TITLE
test list for gtest typed test are not parsed correctly

### ISSUE THREAD

**Issue by pgrabas** [matepek/vscode-catch2-test-adapter#92]
Gtest tests listing is not parsed correctly when gtest typed test are in use.

Output goes like this:
InstallationMasterServiceTest/0.  # TypeParam = <type>
  RevokeInvokesRevokeEvent
InstallationMasterServiceTest/1.  # TypeParam = <type>
  RevokeInvokesRevokeEvent

Regex in GoogleTestSuiteInfo.js about line 115 is not prepared to handle the #...

This issue causes any test after the typed ones to be ignored by extension.

**Comment by matepek** [comment]
What is the version of you google test?

**Comment by matepek** [comment]
Also,

please run your test executable with the following arguments:
`--gtest_list_tests --gtest_output=xml:output.xml`.

What is the content of the `output.xml` file?

**Comment by pgrabas** [comment]
Hello,

I am stuck with some old version, probably 1.8.1
Running with args --gtest_list_tests --gtest_output=xml:output.xml  does not produce xml file.
However without --gtest_list_tests result is generated.
[output.xml.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/3186879/output.xml.txt)

There are logs generated during ut execution. Error is raised at the first of the typed tests.
[test_log.txt](https://github.com/matepek/vscode-catch2-test-adapter/files/3186909/test_log.txt)

**Comment by matepek** [comment]
will be fixed in 2.4.8

**Comment by dvirtz** [comment]
I still see this behavior with 2.8.6. I'm on gtest 1.7.0. 
The output from listing the tests is
```
SrtSocketTest/0.  # TypeParam = std::__1::integral_constant<bool, false>
  ConnectAndListen
  SendAndRecieve
SrtSocketTest/1.  # TypeParam = std::__1::integral_constant<bool, true>
  ConnectAndListen
  SendAndRecieve
```

**Comment by dvirtz** [comment]
found the problem on my settings (wrong env configuration)
