### ISSUE TITLE
Executables in "catch2TestExplorer.executables" in folder settings are not used.

### ISSUE THREAD

**Issue by pgrabas** [matepek/vscode-catch2-test-adapter#97]
Hello,

It looks like since version 2.4.10 catch2TestExplorer.executables from folder or workspace settings are not used. I had to move my configuration to user settings to be effective.
Version 2.4.9 works fine.

There is no errors in the logs. Only default configuration is being used to search for tests executables.

**Comment by matepek** [comment]
Let me check it

**Comment by matepek** [comment]
What is your OS? And what is your VSCode version?

**Comment by matepek** [comment]
Nevermind, I think I figured it out. Will be released soon.
